baseURL = "https://lalithavn.github.io"
languageCode = "en-us"
title = "Blog"
theme = "yinyang"
DefaultContentLanguage = "en"

[author]
  name = "Lalitha Visvanathan"
  homepage = "https://lalithavn.github.io/"

[params]
disqus = "" # disqus account name
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://"
