
#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: posts
#+HUGO_AUTO_SET_LASTMOD: f
#+AUTHOR:
#+hugo_custom_front_matter: :author "Lalitha Visvanathan"
#+HUGO_LASTMOD: f
#+seq_todo: TODO DRAFT CANCEL | DONE
#+STARTUP: logdone
#+STARTUP: content

* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:END:
** TODO Hugo and Tamil
:PROPERTIES:
:EXPORT_FILE_NAME: hugo-and-tamil
:END:
роЕроХро░ роорпБродро▓ роОро┤рпБродрпНродрпЖро▓рпНро▓ро╛роорпН роЖродро┐
рокроХро╡ройрпН роорпБродро▒рпНро▒рпЗ роЙро▓роХрпБ.

I always wanted to check how I can write in tamil for my blog. I tried reading up on i18 and other methods but I couldn't find anything simple. Finally I settled on Google docs.

Google docs lets me write in Tamil (родрооро┐ро┤рпН) and I can just copy paste it in my markdown file.
** DONE рокрпБро▓ро┐ропрпВро░рпНроХрпНроХрпБро▒ро┐роЪрпНроЪро┐ропро┐ро▓рпН роТроЯрпНроЯрпБроХрпНроХрпЗроЯрпНроЯро╡рпИ
CLOSED: [2020-08-19 Wed 16:23]
:PROPERTIES:
:EXPORT_FILE_NAME: puliyurkurichiyil-ottukettavai
:END:
"роПройрпНройро╛, "ро░ро╛роотАж." "роХро┐ро░рпБро╖рпНрогтАж" роЗроирпНрод ро░рпЖрогрпНроЯрпБ рокро╛роЯрпНроЯрпБро▓ роОродрпБ роиро▓рпНро▓ро╛ ро╡роирпНродро┐ро░рпБроХрпНроХрпБ?"

"ро░ро╛роотАж"

"роирпЗро▒рпНро▒рпБ роХрпЗроЯрпНроЯрокрпНрокрпЛ  'роХро┐ро░рпБро╖рпНрог..' рокро╛роЯрпНроЯрпБ роиро▓рпНро▓ро╛ роЗро░рпБроХрпНроХрпБройрпНройрпБ роЪрпКройрпНройрпЗро│рпЗ ЁЯШб?"

ЁЯШзЁЯШзЁЯШз

        ***********************

"роПроорпНрооро╛, роХро╛ро▓рпИро▓рпЗро░рпНроирпНродрпБ роЗроирпНрод рокро╛роЯрпНроЯрпИропрпЗ ро░рпЖроХрпНроХро╛ро░рпНроЯрпН рокрогрпНрогро┐рогрпНроЯро┐ро░рпБроХрпНроХрпЗ?

"роОройрпНройройрпНройрпБ роЪрпКро▓рпНро▓? рокро╛роЯрпНроЯ роорпБроЯро┐роХрпНроХро┐ро▒ роЪрооропродрпНродро┐ро▓ роЬройрпНройро▓ро╛рогрпНроЯ роТро░рпБ роХро╛роХрпНроХро╛ропрпН ро╡роирпНродрпБ роХродрпНродро┐ропро┐ро░рпБроХрпНроХрпБ"

"рокродрпНродрпБ роорогро┐роХрпНроХрпБ рокро╛роЯро┐ройро┐ропрпЗ"

"роХрпВро░ро┐ропро░рпНроХро╛ро░ройрпН ро╡роирпНродрпБ роХро╛ро▓ро┐роЩрпН рокрпЖро▓рпН роЕроЯро┐роЪрпНроЪродрпБ роЗродрпБро▓ ро░рпЖроХрпНроХро╛ро░рпНроЯрпН роЖропро┐ро░рпБроХрпНроХрпБ"

"роородро┐ропроорпН?"

"роЙроЩрпНроХрокрпНрокро╛ ро░рпЖроХрпНроХро╛ро░рпНроЯрпН рокрогрпНро▒рпЗройрпНройрпБ рокроХрпНроХродрпНродро┐ро▓рпН ро╡роирпНродрпБ  роЙроЯрпНроХро╛ро░рпНроирпНродрпБрогрпНроЯрпБ рокро╛родро┐ро▓  родрпБроорпНрооро┐роЯрпНроЯро╛ро░рпНроЯро╛"

"роЪро░ро┐, роИро╡рпНройро┐роЩрпН?"

"роХро╛рокро┐ роХрпБроЯро┐роЪрпНроЪрпБроЯрпНроЯрпБ рокро╛роЯро┐ройрпЗройро╛, роорпБроЯро┐роХрпНроХрпБроорпН рокрпЛродрпБ роПрокрпНрокроорпН ро╡роирпНродрпБроЯрпБродрпНродрпБ"

"..."

"роХрпКроЮрпНроЪ роорпБройрпНройро╛роЯро┐ роХрпБроЯрпНроЯро┐ ро░рпВроорпНро▓ роЙроЯрпНроХро╛ро░рпНроирпНродрпБ рокро╛роЯро┐ройрпЗройрпН. рокро╛роЯрпБроорпНрокрпЛродрпБ родрпЖро░ро┐ропро▓рпИ. роЖройро╛ роЕроирпНрод ро╣рпИродро░рпН роХро╛ро▓родрпНродрпБ роГрокрпЗройрпН роЪродрпНродроорпН роиро╛ро░ро╛роЪрооро╛ рокродро┐роЮрпНроЪро┐ро░рпБроХрпНроХрпБ. роЕродро╛ройрпН роЗрокрпНрок роЗроЩрпНроХ ро╡роирпНродрпБ, ро░рпВроорпН роХродро╡ родро╛ро│рпН рокрпЛроЯрпНроЯрпБ, роПроЪро┐ рокрпЛроЯрпНроЯрпБрогрпНроЯрпБ роХрогрпНрог роорпВроЯро┐рогрпНроЯрпБ роЪрпБроХрооро╛ рокро╛роЯро┐ропро┐ро░рпБроХрпНроХрпЗройрпН. роХрпЗроЯрпНроЯрпБрокрпН рокро╛ро░рпЗройрпН."

" роРропрпЛ роЕроорпНрооро╛, роорпКрокрпИро▓ роХро╡ройро┐роХрпНроХро▓ропро╛? роЪро╛ро░рпНроЬрпН роХрпБро▒роЮрпНроЪрпБ, роирпА рокро╛родро┐ рокро╛роЯрпБроорпНрокрпЛродрпЗ роЪрпЖро▓рпН роЖроГрокрпН роЖропро┐ро░рпБроХрпНроХрпБроорпНрооро╛"

 "ЁЯе╡ЁЯе╡ЁЯе╡"

    ***********************

"роЗроирпНрод ро░ро╛родрпНродро┐ро░ро┐ роирпЗро░родрпНро▓ роОродрпБроХрпНроХрпБроорпНрооро╛ рокрпБродрпБрокрпН рокроЯрпНроЯрпБрокрпНрокрпБроЯро╡рпИ роХроЯрпНроЯро┐рогрпНроЯро┐ро░рпБроХрпНроХро╛ропрпН? ро╡рпЗро░рпНроХрпНроХро▓рпИропро╛? роорпКрокрпИро▓рпНро▓ ро╡ро╛ропрпНро╕рпН  родро╛ройрпЗ ро░рпЖроХрпНроХро╛ро░рпНроЯрпН рокрогрпНрогрогрпБроорпН?"

"роЕрокрпНрокродрпНродро╛ройрпНроЯро╛ рокро╛роЯро▒  роорпВроЯрпН ро╡ро░рпБроорпН. роиро▓рпНро▓ роХроЪрпНроЪрпЗро░ро┐ роОроГрокрпЖроХрпНроЯрпН роХро┐роЯрпИроХрпНроХрпБроорпН"

ЁЯШЫЁЯШЫЁЯШЫ     ***********************

"роЗрокрпНрок роОродрпБроХрпНроХрпБроЯрпА рокро╛роЩрпНроХрпНро▓ рокрпБродрпБ роЕроХрпНроХро╡рпБрогрпНроЯрпН роУрокройрпН рокрогрпНрог роЪрпКро▓рпНро▒рпЗ. роЕродро╛ройрпН роЬро╛ропро┐рогрпНроЯрпН роЕроХрпНроХро╡рпБрогрпНроЯрпН роЗро░рпБроХрпНроХрпЗ"

"роЗроЩрпНроХ рокро╛ро░рпБроЩрпНроХ. роОройроХрпНроХрпБ рокро╛роЯрпНроЯрпБ рокрпЛроЯрпНроЯро┐роХро│рпНро▓ роЗродрпЗ рокрпЛро▓ роиро┐ро▒рпИроп роХрпЗро╖рпН рокрпНро░рпИро╕рпН роХро┐роЯрпИроХрпНроХрпБроорпН роЗро▓рпНро▓ро┐ропро╛? роЕрокрпНрок роЙроЩрпНроХро│рпБроХрпНроХрпБ роЯрпЗроХрпНро╕рпН рокрпНро░ро╛рокрпНро│роорпН ро╡ро░ роХрпВроЯро╛родрпБройрпНройрпБ родро╛ройрпН"

ЁЯдеЁЯдеЁЯде

      ***********************

"роЗроирпНрод рокро╛роЯрпНроЯрпБ роирпА рокро╛роЯро┐ройро╛ роиро▓рпНро▓ро╛ роЗро░рпБроХрпНроХрпБроорпЗроорпНрооро╛. роПройрпН ро╡рпЗрогрпНроЯро╛роЩрпНроХро▒рпЗ"

"роиро╛ройрпН ро░рпЖрогрпНроЯро╛роорпН роХрпНро│ро╛ро╕рпН рокроЯро┐роХрпНроХро▒роЪрпНроЪрпЗ роЪро╛роирпНродро╛ роЗроирпНрод рокро╛роЯрпНроЯрпБ рокро╛роЯро┐ роЪрпЖроХрогрпНроЯрпН рокрпНро░рпИро╕рпН ро╡ро╛роЩрпНроХро┐ройро╛. роЕро╡ро│рпБроорпН роЗроирпНрод роХрпНро░рпВрокрпНро▓ роЗро░рпБроХрпНроХро╛. роЕро╡ рокро╛роЯрпНроЯ роиро╛ройрпН роХро╛рокрпНрокро┐ропроЯро┐роЪрпНроЪрпБроЯрпНроЯрпЗройрпНройрпБ роЪрпКро▓рпНро╡ро╛роЯро╛"

ЁЯдФЁЯдФЁЯдФ

      ***********************

"роОройрпНрой? роЙроЯройрпЗ рокрпБродрпБ роорпКрокрпИро▓рпН ро╡ро╛роЩрпНроХрогрпБрооро╛? роЙройрпНроХро┐роЯрпНроЯ родро╛ройрпН роЗро░рпБроХрпНроХрпЗроЯрпА"

"роЗродрпБро▓ рокро╛роЯрпНроЯрпБ ро░рпЖроХрпНроХро╛ро░рпНроЯрпН рокрогрпНрогро┐ройро╛ роХрпБро░ро▓рпН роиро▓рпНро▓ро╛ро╡рпЗ ро╡ро░ро▓рпИ. рокро╛ро░рпБроЩрпНроХ, ро╡рпЗро▒ роОро▓рпНро▓ро╛ро░рпЛроЯродрпБроорпН роОро╡рпНро╡ро│ро╡рпБ роиро▓рпНро▓ро╛  роЗро░рпБроХрпНроХрпБ рокро╛ро░рпБроЩрпНроХ"

ЁЯШиЁЯШиЁЯШи

     ***********************

"роОройрпНройроорпНрооро╛, рокро╛роЯрпНроЯро┐ ро░рпЖрогрпНроЯрпБ роиро╛ро│ро╛ ро░рпЖро╕рпНроЯрпНро▓рпЖро╕рпНро╕ро╛ роПродрпЛ ропрпЛроЪройрпИропро╛ роЗро░рпБроХрпНроХро╛ро│рпЗ. роПродрпБроорпН рокро┐ро░роЪрпНройрпИропро╛?"

"роЕродрпБ роТройрпНройрпБроорпН роЗро▓рпНро▓рпИроЯро┐. роЕро╡ро╛ роКро░рпН роХрпБро░рпВрокрпН рокро╛роЯрпНроЯрпБрокрпН рокрпЛроЯрпНроЯро┐ро▓ роЬроЯрпНроЬро╛ роЗро░рпБроХрпНроХро╛ роЗро▓рпНро▓ро┐ропро╛? роОро▓рпНро▓ро╛ро░рпБроорпЗ роиро▓рпНро▓ро╛ рокро╛роЯро┐ропро┐ро░рпБроХрпНроХро╛ро│ро╛роорпН. роОрокрпНрокроЯро┐ ро╡ро░ро┐роЪрпИрокрпНрокроЯрпБродрпНродройрпНройрпБ ропрпЛроЪро┐роХрпНроХро▒ро╛"

ЁЯЩГЁЯЩГЁЯЩГ

     ***********************

"... роЗроирпНрод рокро╛роЯрпНроЯрпБ роирпА роиро▓рпНро▓ро╛ рокро╛роЯрпБро╡ро┐ропрпЗроорпНрооро╛, роЗрокрпНрок роПройрпН ро╡рпЗрогрпНроЯро╛роЩрпНроХро▒рпЗ"

"роЪро╛роирпНродро╛ роЗродрпИ ро░рпЖроХрпНроХро╛ро░рпНроЯрпН рокрогрпНрогро┐ роЕройрпБрокрпНрок ро░рпЖроЯро┐ рокрогрпНрогро┐роЯрпНроЯро╛."

"роЕроорпЖро░ро┐роХрпНроХро╛ро╡ро┐ро▓рпН роЗро░рпБроХрпНроХро┐ро▒ роЕроирпНрод роЖройрпНроЯрпНроЯро┐ роЪрпЖропрпНро▒родрпБ роЙройроХрпНроХрпБ роОрокрпНрокроЯро┐роорпНрооро╛ родрпЖро░ро┐ропрпБроорпН?"

"роЕро╡ро│рпЛроЯ роТройрпНро▒рпБро╡ро┐роЯрпНроЯ роиро╛родрпНродройро╛ро░рпЛроЯ ро░рпЖрогрпНроЯрпБ ро╡ро┐роЯрпНроЯ роУро░рпНрокрпНрокроЯро┐ропрпЛроЯ рокро┐ро░рогрпНроЯрпЛроЯ рооройрпНройро┐ роЗроЩрпНроХрпЗ роОройрпН рокроЬройрпН роХрпБро░рпВрокрпНро▓ роЗро░рпБроХрпНроХро╛. роЕро╡родро╛ройрпН роЪрпКройрпНройро╛."

ЁЯдФЁЯдФЁЯдФ

      ***********************

"роХрпЛроирпНродрпЗ"

"роОройрпНрой родро╛родрпНродро╛?"

"роОроЩрпНроХ роКро░рпН роХрпНро░рпВрокрпНро▓ рокро╛роЯрпНроЯрпБрокрпНрокрпЛроЯрпНроЯро┐ роЗро░рпБроХрпНроХрпБ. роирпАропрпБроорпН роТро░рпБ рокро╛роЯрпНроЯрпБ рокро╛роЯрпЗройрпН"

"роУроХрпЗ родро╛родрпНродро╛"

"роЗро░рпБ. роЪрпБро░рпБродро┐ роЪрпЗро░рпНродрпНродрпБроХрпНроХро▒рпЗройрпНтАж. роЪро░ро┐, рокро╛роЯро▒ро┐ропро╛?"

"ЁЯЧгя╕ПЁЯЧгя╕ПЁЯЧгя╕П"

"роХрпЛроирпНродрпЗ, роЕроирпНрод роЪро╛роХрпНро▓рпЗроЯрпНроЯ роорпБро┤рпБроЪро╛ роорпБро┤рпБроЩрпНроХро┐роЯрпНроЯрпБ рокро╛роЯрпБ"

"роОройрпНроХрпВроЯ uno ро╡ро┐ро│рпИропро╛роЯ ро╡ро╛роЩрпНроХ родро╛родрпНродро╛. роХрпЗроорпН роорпБроЯро┐роЮрпНроЪродрпБроорпН рокро╛роЯро▓ро╛роорпН"

"ро░рпКроорпНрок роирпЗро░рооро╛роХрпБроорпЗ"

"роиро╛ройрпН ро╡ро┐ройрпН рокрогрпНрогро┐ройродрпБроорпН рокро╛роЯро▒рпЗройрпН родро╛родрпНродро╛"

"роЪро░ро┐роЯро╛ роХрогрпНрогро╛"

"роХрпЛроирпНродрпЗ, рокро╛роЯро▓ро╛рооро╛?"

"роЯро┐роГрокройрпН роЪро╛рокрпНрокро┐роЯрпНроЯрпБроЯрпНроЯрпБ ро╡ро▒рпЗройрпН родро╛родрпНродро╛"

"роХрпЛроирпНродрпЗ, рокро╛роЯро▓ро╛рооро╛?"

"роЖройрпНро▓рпИройрпН роХро┐ро│ро╛ро╕рпН родрпКроЯроЩрпНроХро┐ро░рпБроХрпНроХрпБ родро╛родрпНродро╛. роЕроорпНрооро╛ роХрпВрокрпНрокро┐роЯро▒ро╛ "

"роХрпЛроирпНродрпЗ, рокро╛роЯро▓ро╛рооро╛?"

"ро░ро╡ро┐ ро╡ро┐ро│рпИропро╛роЯ ро╡роирпНродро┐ро░рпБроХрпНроХро╛ройрпН родро╛родрпНродро╛. роХрпКроЮрпНроЪ роирпЗро░роорпН ро╡ро┐ро│рпИропро╛роЯро┐роЯрпНроЯрпБ ро╡ро░рпЗройрпЗ"

"роХрпЛроирпНродрпЗ, рокро╛роЯро▓ро╛рооро╛?"

"роЖройрпНро▓рпИройрпНро▓ рооро┐ропрпВроЪро┐роХрпН роХро┐ро│ро╛ро╕рпНроХрпНроХрпБ роирпЗро░рооро╛роЪрпНроЪрпБ родро╛родрпНродро╛"

"роХрпЛроирпНродрпЗ, рокро╛роЯро▓ро╛рооро╛?"

"ро╣рпЛроорпН ро╡рпКро░рпНроХрпН роорпБроЯро┐роХрпНроХрогрпБроорпН родро╛родрпНродро╛"

"роХрпЛроирпНродрпЗ, роТро░рпБ роорогро┐роХрпНроХрпВро░рпНро▓ рокро╛роЯрпНроЯ роЕройрпБрокрпНрокрогрпБроорпН. роХрпКроЮрпНроЪроорпН рокро╛роЯрпЗройрпН"

"родрпВроХрпНроХроорпН ро╡ро▒родрпБ родро╛родрпНродро╛"

"роХрпЛроирпНродрпЗ, рокрпНро│рпАро╕рпНроЯро╛"

"ЁЯЧгя╕ПЁЯЧгя╕ПЁЯЧгя╕П"

"роХрпЛроирпНродрпЗ, роЗроЩроХрпНро▓рпАро╖рпН ро╡рпЗрогрпНроЯро╛роорпН роХрогрпНрогро╛. роТро░рпБ роЪро╛рооро┐ рокро╛роЯрпНроЯрпБ рокро╛роЯрпЗройрпН"

"ЁЯЧгя╕ПЁЯЧгя╕П ЁЯе▒...ЁЯЧгя╕ПЁЯе▒.."

'роХрпБро┤роирпНродрпИ родро╛ройрпЗ. роХрпКроЯрпНроЯро╛ро╡ро┐ ро╡ро┐роЯрпНроЯрпБрогрпНроЯрпЗ рокро╛роЯро┐роЯрпНроЯрпБ, рокро╛родро┐ро▓ родрпВроЩрпНроХро┐роЯрпНроЯро╛ройрпН.  рокро░ро╡ро╛ропро┐ро▓рпНро▓рпИ. роЕройрпБрокрпНрокро┐ ро╡рпИрокрпНрокрпЛроорпН.  роЕроЯрпБродрпНрод ро░ро╡рпБрогрпНроЯрпБроХрпНроХрпБ роорпВрогрпБ роиро╛ро│рпН роЗро░рпБроХрпНроХрпЗ'

ЁЯСитАНЁЯжпЁЯСитАНЁЯжпЁЯСитАНЁЯжп



***********************

"роОройрпНройрокрпНрокро╛? роЗроирпНрод рокродрпНродрпБ роиро╛ро│ро╛ роЪро╛рокрпНрокро╛роЯрпБ ро╡ро┐родрпНродро┐ропро╛роЪрооро╛ роЗро░рпБроХрпНроХрпЗ. роироЯрпНро╕рпН, роГрокрпНро░рпВроЯрпНро╕рпН, ро╡рпЖро░рпИроЯрпНроЯро┐ ро░рпИро╕рпН, роЪро┐рокрпНро╕рпН, take away foods... роОройрпНройро╛роЪрпНроЪрпБ?"

"Pky роХрпНро░рпВрокрпНро▓ рокро╛роЯрпНроЯрпБрокрпН рокрпЛроЯрпНроЯро┐ роироЯроХрпНроХро┐ро▒родрпБ роЗро▓рпНро▓ро┐ропро╛? роЕродро╛ройрпНтАж"

ЁЯШЛЁЯШЛЁЯШЛ                 ***********************

"роОройрпНройроЯро╛, роЙроЩрпНроХроорпНрооро╛ ро░рпКроорпНрок рокрпКро▓ро┐ро╡ро╛ родрпЖро░ро┐ропро▒ро╛ро│рпЗ. рокродрпНродрпБ ро╡ропродрпБ роХрпБро▒роЮрпНроЪ рооро╛родро┐ро░ро┐ роЗро▓рпНро▓рпИ?"

" роЕродро╛ройрпН роЕрокрпНрокро╛, роЕро╡роЩрпНроХ роКро░рпН роХрпНро░рпВрокрпН рокро╛роЯрпНроЯрпБрокрпНрокрпЛроЯрпНроЯро┐ро▓ роЪрпЗро░рпНроирпНродрпБ рокро╛роЯро┐ройродрпБро▓рпЗро░рпНроирпНродрпБ ро░рпКроорпНрок роЙро▒рпНроЪро╛роХрооро╛роХро┐роЯрпНроЯро╛роЩрпНроХ. роЕродрпЛроЯ, роЗрокрпНрокро▓рпНро▓ро╛роорпН роХрпЛрокроорпН роЪро┐роЯрпБроЪро┐роЯрпБрокрпНрокрпБ роОродрпБро╡рпБроорпЗ роЗро▓рпНро▓рпИрокрпНрокро╛."

"роЪро░ро┐родро╛ройрпН. роЕрокрпНрокроЯро┐ройрпНройро╛ роЕроирпНрод роЕроЯрпНрооро┐ройрпНроЯрпНроЯ роЪрпКро▓рпНро▓ро┐ роЕроЯро┐роХрпНроХроЯро┐ роЗроирпНрод рооро╛родро┐ро░ро┐ рокрпЛроЯрпНроЯро┐роХро│рпН ро╡рпИроХрпНроХ роЪрпКро▓рпНро▓рогрпБроорпН. роЪрпЖропрпНро╡ро╛ро░рпНроХро│ро╛?"

"ЁЯСМ super idea роЕрокрпНрокро╛"

  ***********************

** DONE роХрпЛрокроорпН роХрпЛрокрооро╛роХро╡ро░рпБроХро┐ро▒родрпБ
CLOSED: [2020-08-25 Tue 13:45]
:PROPERTIES:
:EXPORT_FILE_NAME: kobam-kobamaga-varugirathu
:END:
рокрпЖро▒рпНро▒ роороХро│рпИропрпКродрпНрод роЕрокрпНрокро╛ро╡ро┐ рооро╛рогро╡ро┐роХро│ро┐роЯроорпН роЪро┐ро▓рпНрооро┐ро╖роорпН роЪрпЖропрпНропрпБроорпН роЪро┐ро▓ ро╡ро╛родрпНродро┐ропро╛ро░рпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

роЪро╛ро▓рпИ ро╡ро┐родро┐роХро│рпИ, роЪро┐роХрпНройро▓рпНроХро│рпИ роЕро▓роЯрпНроЪро┐ропрооро╛роХ роорпАро▒ро┐роЪрпН роЪрпЖройрпНро▒рпБ, рокро┐ройрпН рооро╛ро░рпНродроЯрпНроЯро┐роЪрпН роЪро┐ро░ро┐роХрпНроХрпБроорпН ро╡ро╛роХрой роУроЯрпНроЯро┐роХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

роиро╛роЯрпНроЯрпБроХрпНроХрпБроорпН ро╡рпАроЯрпНроЯрпБроХрпНроХрпБроорпН роЪрпКроирпНрод роЙропро┐ро░рпБроХрпНроХрпБроорпН ро╡ро┐ро╖роорпН  роОройрпНро▒рпБ родрпЖро░ро┐роирпНродро┐ро░рпБроирпНродрпБроорпН, роородрпБроХрпНроХроЯрпИроХро│ро┐ро▓рпН роЕро▓рпИроорпЛродрпБроорпН роХрпВроЯрпНроЯродрпНродрпИроХрпН роХрогрпНроЯро╛ро▓рпН...

рокрпКродрпБ роЗроЯроЩрпНроХро│ро┐ро▓рпН роОроЪрпНроЪро┐ро▓рпН родрпБрокрпНрокрпБрокро╡ро░рпНроХро│рпН, рокрпБроХрпИ рокро┐роЯро┐рокрпНрокро╡ро░рпНроХро│рпН, ро▓роЬрпНроЬрпИропро┐ройрпНро▒ро┐ 'роТродрпБроЩрпНроХрпБ'рокро╡ро░рпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

ро╡рпАроЯрпНроЯрпБроХрпН роХрпБрокрпНрокрпИроХро│рпИ родрпЖро░рпБро╡рпЛро░роХрпН роХрпБрокрпНрокрпИродрпН родрпКроЯрпНроЯро┐роХро│ро┐ро▓рпН роТро┤рпБроЩрпНроХро╛роХрокрпН рокрпЛроЯро╛рооро▓рпН (роорпВроХрпНроХрпИрокрпН рокро┐роЯро┐родрпНродрпБроХрпНроХрпКрогрпНроЯрпБ) ро╡рпАроЪро┐ ро╡ро┐роЯрпНроЯрпЖро▒ро┐рокро╡ро░рпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

рооро┐роХ рооро┐роХ рооро┐роХ роЖроЯроорпНрокро░рооро╛роХ родро┐ро░рпБроорогроорпН роироЯродрпНродро┐, рокро┐ройрпН роЕроирпНрод роХроЯройрпИропрпБроорпН рокрпЖрогрпН родро▓рпИропро┐ро▓рпЗропрпЗ роХроЯрпНроЯро┐ро╡ро┐роЯрпБроорпН рокрпЖро▒рпНро▒рпЛро░рпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпНтАж(роПро▒рпНроХрпЖройро╡рпЗ роЗро╡ро░рпНроХро│рпН роЪрпБропроиро▓родрпНродро╛ро▓рпН ро▓рпЗроЯрпН роорпЗро░рпЗроЬрпН тАж)

рокроЯро┐рокрпНрокрпБ, роЕроирпНродро╕рпНродро┐ро▓рпН  роХрпБро▒рпИроирпНрод роирогрпНрокро░рпН, роЙро▒ро╡ро┐ройро░рпНроХро│рпИ (рокрпЖро▒рпНро▒рпЛро░рпИропрпБроорпН роЪрпЗро░рпНродрпНродрпБ)  родрпЖро░ро┐роирпНродро╡ро░рпНроХро│ро┐роЯроорпН роЕро▒ро┐роорпБроХроорпН роЪрпЖропрпНроп ро╡рпЖроЯрпНроХрокрпНрокроЯрпБроорпН 'рокрпЖро░рпАроп' рооройро┐родро░рпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпНтАж

роЙро░рпБрокрпНрокроЯро┐ропро╛роХ роОродрпБро╡рпБроорпЗ родрпЖро░ро┐ропро╛ ро╡ро┐роЯрпНроЯро╛ро▓рпБроорпН, "роР роЯрпЛрогрпН роирпЛ роЯро╛рооро┐ро▓рпН" роОройрпНро▒рпБ ро╡рпЖроЯрпНроХрооро┐ройрпНро▒ро┐ роЪро┐ро▓рпБрокрпНрокро┐роХрпН роХрпКрогрпНроЯрпБ родро┐ро░ро┐ропрпБроорпН роЪро┐ро▓ ро▓рпВроЪрпБроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

роЪро░ро┐ропро╛роХ роЖро░ро╛ропро╛рооро▓рпН, роОродрпИропро╛ро╡родрпБ роОрокрпНрокроЯро┐ропро╛ро╡родрпБ роЪрпЖропрпНродро┐ропро╛роХ ро╡рпЖро│ро┐ропро┐роЯрпНроЯрпБ рокро░рокро░рокрпНрокрпИ  родрпЗроЯро┐роХрпНроХрпКро│рпНро│рпБроорпН роЪро┐ро▓ роКроЯроХроЩрпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

роХрпКро░рпКройро╛ роЙро▓роХрпИропрпЗ роЕроЪрпНроЪрпБро▒рпБродрпНрод, рооро╛ро╕рпНроХрпН роЕрогро┐ропро╛рооро▓рпН, родрпЗро╡рпИропро┐ро▓рпНро▓ро╛род рокрпЛродрпБроорпН рокрпКродрпБ роЗроЯроЩрпНроХро│ро┐ро▓рпН  роЕро▓роЯрпНроЪро┐ропрооро╛роХ роЪрпБро▒рпНро▒ро┐родрпН  родро┐ро░ро┐рокро╡ро░рпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

роЗро╡рпИропрпЖро▓рпНро▓ро╛роорпН родрпЖро░ро┐роирпНродрпБроорпН рокрпБро░ро┐роирпНродрпБроорпН роЙрогро░рпНродрпНродрпБроорпН роХрогрпНроЯрпБроорпН роХро╛рогро╛рооро▓рпН рокрпЛроХрпБроорпН роОройрпН роХрпИропро╛ро▓ро╛роХро╛родрпНродройродрпНродрпИ роиро┐ройрпИродрпНродро╛ро▓рпЗ  роХрпЛрокроорпН роХрпЛрокроорпН роХрпЛрокрооро╛роХ ро╡ро░рпБроХро┐ро▒родрпБтАж.

** DONE роХро▓ро┐ роорпБродрпНродро┐рокрпН рокрпЛроЪрпНроЪрпБ :роЪро┐ро▒рпБроХродрпИ:
CLOSED: [2020-08-28 Fri 00:48]
:PROPERTIES:
:EXPORT_FILE_NAME: kali-muthi-pochu
:END:
*роЪрооро░рпНрокрпНрокрогроорпН* :  роОродро▒рпНроХрпЖроЯрпБродрпНродро╛ро▓рпБроорпН тАЬро╣рпНроорпНтАж роОроЩрпНроХ роХро╛ро▓роорпН рокрпЛро▓ ро╡ро░рпБрооро╛тАж.тАЭ роОройрпНро▒рпБ роЪродро╛ роЕроЩрпНроХро▓ро╛ропрпНрокрпНрокро╡ро░рпНроХро│рпБроХрпНроХрпБтАж!

*** роорпБроирпНродро╛роиро╛ро│рпН

тАЬроХро▓ро┐ роорпБродрпНродро┐рокрпН рокрпЛроЪрпНроЪрпБроЯрпА ро░рпБроХрпНроХрпБтАЭ

тАЬроОройрпНрой роЪрпКро▓рпНро▒рпЗро│рпНтАЭ

тАЬроироорпНрок рокро┐ро│рпНро│рпИропро╛рогрпНроЯройрпИропрпЗ рокро╛ро░рпЗройрпН. роХроЯрпНроЯрпБроХрпНроХрпБроЯрпБрооро┐ропрпБроорпН роХроЯрпБроХрпНроХройрпБрооро╛ роЬроорпНроорпБройрпНройрпБ роЗро░рпБроирпНродро╡ройрпН, роОрокрпНрокроЯро┐ роЕро▓роЩрпНроХрпЛро▓роорпН рокрогрпНрогро┐рогрпНроЯрпБ ро╡роирпНродрпБ роиро┐роХрпНроХро▒ро╛ройрпН рокро╛ро░рпБ.тАЭ

тАЬроРропрпИропрпЛ.. роЗродро╛ройрпН роХрпНро░ро╛рокрпНрокрпБ родро▓рпИропро╛... тАЬ

тАЬроЖрооро╛роорпНроЯрпА. ро╡рпЗро╖рпНроЯро┐ропроХрпНроХрпВроЯ роЗрокрпНрокро▓рпНро▓ро╛роорпН родро╛ро░рпН рокро╛ропрпНроЪрпНроЪро┐ роХроЯрпНроЯро┐роХрпНроХро┐ро▒родро┐ро▓рпНро▓рпИ. роЪрпБроорпНрооро╛ роТро░рпБ роЪрпБро▒рпНро▒рпБ. роЕро╡рпНро╡ро│ро╡рпБродро╛ройрпН.  роЗродрпБро▓ роТро░рпБ роЯрокрпНрокро╛роХрпНроХроЯрпНроЯрпБ ро╡рпЗро▒тАжтАЭ

тАЬроПродрпЛ рокрпБродрпБ родро┐ройрпБроЪро╛ рокро╛роЯрпНроЯрпБ рооро╛родро┐ро░ро┐ роорпБрогрпБроорпБрогрпБроХрпНроХро┐ро▒ро╛ройрпЗ.тАЭ

тАЬроЪро┐ройро┐рооро╛ рокро╛роЯрпНроЯрпБроЯрпА. рокрпБродрпБроЪро╛ ро╡ро╛роЩрпНроХро┐ роОрокрпНрокро╡рпБроорпН роХро╛родрпБ роХро┐роЯрпНроЯропрпЗ ро╡роЪрпНроЪрпБрогрпНроЯрпБ роироЯроХрпНроХро┐ро▒ро╛ройрпЗтАж. роЯрпНро░ро╛ройрпНро╕ро┐ро╕рпНроЯро░рпНройрпБ.  роЕродрпБро▓ роХрпЗроЯрпНроЯрпБроХрпНроХро▒родрпБ родро╛ройрпН роЗродрпЖро▓рпНро▓ро╛роорпН.тАЬ

тАЬроЕроЯ ро░ро╛рооро╛тАж роПройрпН родро╛ройрпН рокрпБродрпНродро┐ роЗрокрпНрокроЯро┐ рокрпЛро▒родрпЛтАЭ

тАЬродрпБро░рпИ роЖрокро┐ро╕рпН ро╡рпЗро▓рпИроХрпНроХрпБрокрпН рокрпЛро▒ро╛ройрпНро▓, роЕроирпНрод рокро╡ро┐ро╖рпБтАЭ

тАЬроЕродрпБ роЪро░ро┐, роЕро╡ройрпН рокрпКрогрпНроЯро╛роЯрпНроЯро┐ роороЯрпНроЯрпБроорпН роОройрпНройро╡ро╛роорпН? роорпБродро▓рпНро▓ роЗроирпНрод рокро╛роХрпАро░родро┐ропрпБроорпН роороЯро┐роЪро╛ро░рпБроорпН роХрпЛроЯро╛ро▓ро┐роХрпН роХрпКрогрпНроЯрпИропрпБрооро╛ рокродро╡ро┐роЪро╛родрпНродро╛ройрпЗ роЗро░рпБроирпНродро╛. рокрпЛрой рооро╛роЪроорпН роЕро╡ родроЩрпНроХрпИропрпИ рокро╛ро░рпНроХрпНроХ роородро░ро╛ро╕рпН рокрпЛропро┐роЯрпНроЯрпБ  ро╡роирпНродро╛ро▓рпБроорпН ро╡роирпНродро╛, родро╛роЩрпНроХро▓. ро╕ро╛ро░ро┐ройрпНройрпБ роТрогрпНрог роХроЯрпНроЯро┐роХрпНроХро┐ро▒ро╛ рокро╛ро░рпБроЩрпНроХ. роорпКродрпНрод роирпАро│роорпЗ роЖро▒рпБ роХроЬроорпНродро╛ройрпН. роЕродрпБро▓ роТро░рпБ роорпАроЯрпНроЯро░рпБроХрпНроХрпБ роорпЗро▓ропрпЗ родро▓рокрпНрокрпБройрпНройрпБ роЪрпКро▓рпНро▓ро┐ роХро╛ро▒рпНро▒рпБро▓ рокро▒роХрпНроХро▒родрпБ. роЕроирпНрод ро╕ро╛ро░ро┐ роХро▓ро░рпНро▓ропрпЗ роЪроЯрпНроЯрпИ. роорпЗроЯрпНроЪро┐роЩрпНроХро╛роорпН. роЕродрпБ роороЯрпНроЯрпБрооро╛, роЪро┐ройрпНройрокрпНрокрпЖрогрпН рооро╛родро┐ро░ро┐ роЬроЯрпИ рокро┐ройрпНройро┐ ро░ро┐рокрпНрокройрпН ро╡роЪрпНроЪрпБтАж рокрпЛродро╛роХрпНроХрпБро▒рпИроХрпНроХрпБ ро╕рпНройрпЛ, рокро╡рпБроЯро░рпНройрпБ роОройрпНройрпЖройрпНройро╡рпЛ роХрогрогро▒ро╛ро╡ро┐.тАЭ

тАЬроЖроЪро╛ро░роЩрпНроХро▒родрпБ ро╡ро┐роЯрпНроЯрпЗ рокрпЛроЪрпНроЪрпБ. роирпЗро▒рпНро▒рпБ ро╡ро┐роЪрпНроЪрпБро╡рокрпН рокро╛ро░рпНроХрпНроХ роЪро┐ройрпЗроХро┐родройрпН роироЯрпЗроЪройрпН ро╡роирпНродро┐ро░рпБроХрпНроХро╛ройрпН, роЙро│рпНродро┐рогрпНрогрпИ рокрпЖроЮрпНроЪрпНро▓ роЙроЯрпНроХро╛ро░ ро╡роЪрпНроЪрпБ роЗро╡ройрпН ро╡ро░рпНро▒ ро╡ро░рпИроХрпНроХрпБроорпН рокрпЗроЪро┐рогрпНроЯро┐ро░рпБроХрпНроХро╛тАЭ

тАЬроЗроЩрпНроХ ро░рпЗро┤ро┐ро▓ роЪро┐ро░ро┐роЪрпНроЪро╛ родро┐рогрпНрогрпИ ро╡ро░рпИроХрпНроХрпБроорпН роХрпЗроЯрпНроХрпБродрпБтАЭ

тАЬроЕроЯро┐роХрпНроХроЯро┐ ро░роХроЪро┐ропрооро╛ ро░рпЖрогрпНроЯрпБ рокрпЗро░рпБроорпН роЪро┐ройро┐рооро╛ роХрпВроЯрокрпН рокрпЛро▒ро╛ройрпНройро╛ рокро╛ро░рпНродрпНродрпБроХрпНроХрпЛ.тАЭ

тАЬроЪро┐ро╡роЪро┐ро╡ро╛, роОро▓рпНро▓ро╛роорпН роХрпИроорпАро▒ро┐рокрпН рокрпЛропро╛роЪрпНроЪрпБ. роОройрпНрой роЪрпЖропрпНроп?тАЭ

тАЬроХро▓ро┐роХро╛ро▓роорпН роХро▓ро┐роХро╛ро▓роорпНтАжтАЭ

*** роирпЗро▒рпНро▒рпБ

тАЬроХро▓ро┐ роорпБродрпНродро┐рокрпН рокрпЛроЪрпНроЪрпБроЯрпА рокро╛роХро┐тАЭ

тАЬроПройрпН? роОройрпНройро╛роЪрпНроЪрпБ?тАЭ

тАЬроироорпНрок роЪрпАройрпБро╡рпБроХрпНроХрпБ ро░рпЖрогрпНроЯрпБ ро╡рпЗро╖рпНроЯро┐ ро╡ро╛роЩрпНроХро┐роЯрпНроЯрпБ ро╡роирпНродрпЗройрпН. ро╡рпЗрогрпНроЯро╛роорпНройрпБ роЪрпКро▓рпНро▒ро╛ройрпН. роЖрокрпАроЪрпБроХрпНроХрпБ, ро╡рпЖро│ро┐ро▓ рокрпЛроХро╡ро░ рокрпЗрогрпНроЯрпН ро╖ро░рпНроЯрпН родро╛ройрпН роЪрпМроХро░рпНропрооро╛ роЗро░рпБроХрпНроХро╛роорпН. ро╡рпАроЯрпНро▓ роЗро░рпБроХрпНроХро▒роЪрпНроЪ роОрокрпНрокрокрпНрокро╛ро░рпБ роТро░рпБ роХрпИро▓ро┐ропрпБроорпН роТро░рпБ рокройро┐ропройрпБроорпН. родрпАро╡роЯрпНроЯро┐роХрпН  роХрпКро│рпНро│рпИроХрпНроХро╛ро░ройро╛роЯрпНроЯроорпН роЗро░рпБроХрпНроХрпБ.тАЭ

тАЬродро▓рпИропрпИрокрпН рокро╛ро░рпБ. роТро┤рпБроЩрпНроХро╛ роТро░рпБ роХрпНро░ро╛рокрпН ро╡рпЖроЯрпНроЯро┐роХрпНроХро╛роо, ро╕рпНроЯрпЖрокрпН роХроЯрпНроЯро┐роЩрпН, рокройрпН роХроЯрпНроЯро┐роЩрпНройрпБ рокрогрпНрогро┐рогрпНроЯрпБ ро╡роирпНродрпБ родро▓рпИроп роЪро┐ро▓рпБрокрпНрокро┐ роЪро┐ро▓рпБрокрпНрокро┐ роХро╛роЯрпНроЯро┐...тАЭ

тАЬроХро╛родрпБ роХро┐роЯрпНроЯ роХро┐ро░рпБродро╛, роорпВроХрпНроХрпБроХрпНроХроЯро┐ро▓ роорпАроЪрпИ роОро▓рпНро▓ро╛роорпН ро╡ро│ро░рпНроХрпНроХродрпН родрпКроЯроЩрпНроХро┐ропро┐ро░рпБроХрпНроХро╛ройрпЗ. рокропрооро╛родрпНродро╛ройро┐ро░рпБроХрпНроХрпБтАЭ

тАЬроОро▓рпНро▓ро╛роорпН роЗроирпНрод роЪро┐ройро┐рооро╛роХрпНроХро╛ро░ро╛ро│рпИроХрпН роХро╛рокрпНрокро┐ропроЯро┐роХрпНроХро┐ро▒родрпБроХро│рпН. роиро▓рпНро▓родрпБроХрпНроХро╛ роЗродрпЖро▓рпНро▓ро╛роорпН?тАЭ

тАЬроЕро╡ройрпН рокрпКрогрпНроЯро╛роЯрпНроЯро┐ ро░рооро╛ро╡рпБроорпН роЪро│рпИроЪрпНроЪро╡ро│ро┐ро▓рпНро▓рпИ. роЗроирпНрод рокроорпНрокро╛ропрпН роХро▓рпНропро╛рогродрпНродрпБроХрпНроХрпБрокрпН рокрпЛропро┐роЯрпНроЯрпБ ро╡роирпНродро╛ро▓рпБроорпН ро╡роирпНродро╛, роОро▓рпНро▓ро╛роорпЗ рооро╛ро▒ро┐рогрпНроЯро┐ро░рпБроХрпНроХрпБ. рокрпКроорпНрооройро╛роЯрпНроЯро┐роХрпНроХрпБ роЪрпЗро▓рпИ родро╛ройрпЗ роЕро┤роХрпБ. роЗроЩрпНроХ роОройрпНройроЯро╛ройрпНройро╛ роОрокрпНрокрокрпНрокро╛ро░рпБ ро╡роЯроХрпНроХродрпНродро┐рокрпН рокрпКроорпНрокро│рпИ рооро╛родро┐ро░ро┐ ро╕ро▓рпНро╡ро╛ро░рпН роХроорпАро╕рпН. ро╡рпАроЯрпНро▓ рокро╛родро┐ роирпЗро░роорпБроорпН роирпИроЯрпНроЯро┐ родро╛ройрпН. роЕродрпИ роирпИроЯрпНроЯро┐ роЗро▓рпНро▓, роЯрпЗроЯрпНроЯро┐ройрпНройрпБ родро╛ройрпН роЪрпКро▓рпНро▓рогрпБроорпНтАЭ

тАЬроироорпНрок роЪрпАройрпБро╡рпИ рокрпЗро░рпН роЪрпКро▓рпНро▓ро┐родрпНродро╛ройрпН роХрпВрокрпНрокро┐роЯро▒ро╛ рокрпЛро▓. ро╡рпЗро▓рпИроХрпНроХрпБ ро╡рпЗро▒ рокрпЛро▒ро╛ро│рпЛройрпНройрпЛтАЭ

тАЬроОродрпБроХрпНроХрпЖроЯрпБродрпНродро╛ро▓рпБроорпН роЗродрпБ роТро░рпБ роЪро╛роХрпНроХрпБ. родро▓рпИро╡ро╛ро░ро┐рокрпН рокро┐ройрпНройро┐роХрпНроХроЪрпН роЪрпКройрпНройро╛, роирпЗро░рооро┐ро▓рпНро▓рпИропро╛роорпН. рокрпЛройро┐ роЯрпЖропрпНро▓рпНройрпБ роТро░рпБ роХрпНро│ро┐рокрпН рооро╛роЯрпНроЯро┐роХрпНроХро┐ро▒родрпБ. ро╡ро┐родро╡ро┐родрооро╛ роЬро┐рооро┐роХрпНроХро┐, роЯрпНро░ро╛рокрпНро╕рпНройрпБ рооро╛роЯрпНроЯро┐роХрпНроХ роороЯрпНроЯрпБроорпН роирпЗро░рооро┐ро░рпБроХрпНроХрпБ.тАЭ

тАЬро╣рпБроорпНтАЭ

тАЬроЙроЩрпНроХро│рпБроХрпНроХрпБ родрпЖро░ро┐ропрпБрооро╛, роорпБроЯро┐ропрпИ роЕроЯро┐роХрпНроХроЯро┐ ро╡рпЖроЯрпНроЯро┐ ро╡ро┐роЯрпНроЯрпБроХрпНроХро▒ро╛. роиро░рпИроХрпНроХродрпН родрпКроЯроЩрпНроХро┐ропро╛роЪрпНроЪрпБ. ро╡рпЖро│ро┐ро▓ родрпЖро░ро┐ропро╛роо роЪро╛ропроорпН рокрпВроЪро┐роХрпНроХро┐ро▒ро╛.тАЭ

тАЬроЗроирпНрод роЯро┐ро╡ро┐ройрпНройрпБ роТройрпНро▒рпБ ро╡рпАроЯрпНроЯрпБроХрпНроХрпБро│рпНро│ ро╡роирпНродро╛ро▓рпБроорпН ро╡роирпНродродрпБ. роЪро░рпНро╡роиро╛роЪроорпНтАЭ

тАЬроОро▓рпНро▓ро╛роорпН роОроЩрпНроХрпЗ рокрпЛропрпН роорпБроЯро┐ропрокрпН рокрпЛроХро┐ро▒родрпЛ, роИро╕рпНро╡ро░ро╛...тАЭ

тАЬроХро▓ро┐роХро╛ро▓роорпН роХро▓ро┐роХро╛ро▓роорпНтАжтАЭ


*** роЗройрпНро▒рпБ

тАЬроХро▓ро┐ роорпБродрпНродро┐рокрпН рокрпЛроЪрпНроЪрпБ ро░рооро╛тАЭ

тАЬроОройрпНрой роЪрпАройрпБ?тАЭ

тАЬроироорпНрок ро╡рпАроЯрпНроЯрпИропрпЗ рокро╛ро░рпБ. роЗроирпНрод роЕрокро┐ роХрпКроЮрпНроЪрооро╛ро╡родрпБ роТро┤рпБроЩрпНроХро╛ роЗро░рпБроХрпНроХро╛ройро╛? ро╡ро╛ро░роХрпНроХрогроХрпНроХрпБро▓ родрпЛропрпНроХрпНроХро╛род роЬрпАройрпНро╕рпБроорпН, ро╡рпЖро│ро▒ро┐рой роТро░рпБ роЯрпАро╖ро░рпНроЯрпНроЯрпБроорпН, роЕро╡ройрпН родро╛роЯро┐ропрпБроорпНтАж  роиро▓рпНро▓ро╛ро╡ро╛ роЗро░рпБроХрпНроХрпБ?тАЭ

тАЬроТро┤рпБроЩрпНроХро╛ рокрпЗрогрпНроЯрпН роЪро░рпНроЯрпН роЕропро░рпНройрпН рокрогрпНрогро┐ рокрпЛроЯрпНроЯроХрпНроХроХрпНроХрпВроЯро╛родрпЛ?тАЭ

тАЬроЗройрпНройро┐роХрпНроХрпБ ро╣рпЗро░рпНроХроЯрпН рокрогрпНрогро┐роЯрпНроЯрпБ ро╡роирпНродро┐ро░рпБроХрпНроХро╛ройрпН рокро╛ро░рпНродрпНродро┐ропро╛? роОройрпНройро╡рпЛ роЕрогрпНроЯро░рпНроХроЯрпНроЯро╛роорпН. роОро▓ро┐ ро╡роирпНродрпБ роХро▒рпБро╡ро┐роЯрпНроЯрпБрокрпН рокрпЛрой рооро╛родро┐ро░ро┐ роЗро░рпБроХрпНроХрпБ.тАЭ

тАЬроЕройрпБро╡рпБроорпН роЗродрпЗродро╛ройрпЗ. роорпБроЯро┐ройрпНройро╛ роХро▒рпБрокрпНрокро╛родрпНродро╛ройрпЗ роЗро░рпБроХрпНроХрогрпБроорпН? роЪрпБро╡ро▒рпНро▒рпБроХрпНроХрпБ роЕроЯро┐роХрпНроХро┐ро▒ рокрпЖропро┐рогрпНроЯрпН рооро╛родро┐ро░ро┐ родро▓рпИропро┐ро▓ропрпБроорпН роЕроЯро┐роЪрпНроЪрпБ, ро▓рпВро╕рпН ро╣рпЗро░рпНройрпБ роорпБроЯро┐ропрпИ ро╡ро┐ро░ро┐роЪрпНроЪрпБрокрпН рокрпЛроЯрпНроЯрпБрогрпНроЯрпБ ро╡роирпНродрпБ роиро┐роХрпНроХро▒ро╛. роЪро╛рокрпНрокро┐роЯрпБроорпНрокрпЛродрпБ родро┐роХрпНроХрпБ родро┐роХрпНроХрпБройрпНройрпБ  роЗро░рпБроХрпНроХрпБ. роЬрпЖро▓рпН рокрпЛроЯрпНроЯро┐ро░рпБроХрпНроХрпЗройрпН, роорпБроЯро┐ропрпЖро▓рпНро▓ро╛роорпН роЙродро┐ро░ро╛родрпБройрпНройрпБ ро╡ро┐ро│роХрпНроХроорпН ро╡рпЗро▒.тАЭ

тАЬроЯрпНро░ро╕рпН роЕродрпБроХрпНроХрпБроорпН роорпЗро▓. роОрокрпНрок рокро╛ро░рпБ роЖроорпНрокро│ рооро╛родро┐ро░ро┐ роТро░рпБ ро╖ро╛ро░рпНроЯрпНро╕рпН, ро╖ро░рпНроЯрпН. роХро╛родрпБро▓ роХрпИро▓ роХро┤рпБродрпНродрпБро▓ройрпНройрпБ роОродрпБро╡рпБроорпН роХро┐роЯрпИропро╛родрпБ. ро▓рпЖройрпНро╕ ро╡роЪрпНроЪрпБ роЙро▒рпНро▒рпБрокрпН рокро╛ро░рпНродрпНродро╛роХрпНроХрпВроЯ родрпЖро░ро┐ропро╛род роТро░рпБ роЪро┐ройрпНройрпНрой рокрпКроЯрпНроЯрпБ.тАЭ

тАЬроХрпИро▓ роЯро╛роЯрпНроЯрпВройрпНройрпБ роТро░рпБ рокроЯроорпН рокроЪрпНроЪрпИроХрпН роХрпБродрпНродро┐рой рооро╛родро┐ро░ро┐тАЭ

тАЬрооро░ро┐ропро╛родрпИройрпНро▒родрпБ роХроЯрпБроХро│ро╡рпБроорпН роЗро▓рпНро▓ро┐ропрпЗ. роироорпНрок роЕрокро┐ропрпИ ро╡ро╛роЯро╛ рокрпЛроЯро╛ройрпНройрпБродро╛ройрпН рокрпЗроЪро▒ро╛. роОро▓рпНро▓ро╛роорпН роЙро░рпБрокрпНрокроЯрпНроЯро╛ рооро╛родро┐ро░ро┐ родро╛ройрпНтАЭ

тАЬроОро▓рпНро▓ро╛ ро╡рпЗро▓рпИроХрпНроХрпБроорпН роорпЖро╖ро┐ройрпН. роЙроЯроорпНрокрпБ роКродро╛роо роОройрпНрой роЖроХрпБроорпН? роЕрокрпНрокрпБро▒роорпН роЕродрпБроХрпНроХрпБройрпНройрпБ родройро┐ропро╛ ро╡ро╛роХрпНроХро┐роЩрпН, роЬро┐роорпНройрпБ..тАЭ

тАЬроОроЩрпНроХро░рпБроирпНродрпБ родро╛ройрпН роХродрпНродрпБроХрпНроХро▒ро╛роЩрпНроХро│рпЛ..тАЭ

тАЬроХрпИро▓ роЪрпЖро▓рпНроГрокрпЛройрпН, роороЯро┐ро▓ ро▓ро╛рокрпНроЯро╛рокрпН. роиро┐рооро┐ро░рпНроирпНродрпБ рокро╛ро░рпНродрпНродро╛родрпНродро╛ройрпЗ. роЗроирпНрод роЗройрпНроЯро░рпНроирпЖроЯрпН ро╡роирпНродро╛ро▓рпБроорпН ро╡роирпНродродрпБ. роЪроХро▓роорпБроорпН роЪро░рпНро╡роиро╛роЪроорпНтАЭ

тАЬроЖрооро╛, роЪрпБропрооро╛ ропрпЛроЪро┐роХрпНроХро╛роо, роОродрпБроХрпНроХрпЖроЯрпБродрпНродро╛ро▓рпБроорпН роЕроирпНрод роХрпВроХро┐ро│рпНро▓ родро╛рой родрпЗроЯро▒родрпБроХро│рпНтАЭ

тАЬро░ро╛рооро╛тАж роОроЩрпНроХ рокрпЛропрпН роиро┐ро▒рпНроХрокрпН рокрпЛро▒родрпБроХро│рпЛ..тАЭ

тАЬроХро▓ро┐роХро╛ро▓роорпН роХро▓ро┐роХро╛ро▓роорпНтАжтАЭ

*** роиро╛ро│рпИ

"роХро▓ро┐ роорпБродрпНродро┐рокрпН рокрпЛроЪрпНроЪрпБ роЕройрпБ  "

"роПройрпНроЯро╛ роЕрокрпА?"

"рокро┐ройрпНройрпЗ роОройрпНрой? роироорпНрок ро╢рпНро░рпА роЗройрпНройро┐роХрпНроХрпБ роЖроГрокрпАроЪрпБроХрпНроХрпБ ро╡рпЗро╖рпНроЯро┐ропрпЛроЯ ро╡роирпНродрпБ роиро┐роХрпНроХро▒ро╛ройрпН. рооро╛ройроорпН рокрпЛроЪрпНроЪрпБ роОройроХрпНроХрпБ.тАЭ

тАЬроРропрпИропрпЛтАЭ

тАЬроЗродрпБ роороЯрпНроЯрпБрооро╛, рокро╛роХро╡родро░рпН ро╕рпНроЯрпИро▓рпНройрпБ роЬроЯрпИ ро╡ро│ро░рпНродрпНродрпБтАж роЕрокрпНрокрокрпНрок роХрпБроЯрпБрооро┐роХрпНроХроЯрпНроЯрпБ ро╡рпЗро▒. роХро╛родрпБро▓ роТро░рпБ ро╕рпНроЯроЯрпН. роЪрпЖропро┐ройрпНро▓ роЯрпИроХро░рпН роирпЖропрпНро▓рпН рооро╛родро┐ро░ро┐ роЯро╛ро▓ро░рпН. роОройрпНройроЯро┐ роХрпЛро▓роорпН роЗродрпБ?тАЭ

тАЬроОро▓рпНро▓ро╛роорпН роЕро╡ройрпН ро╡рпКропрпНроГрокрпН ро╡рпЗро▓рпИроЯро╛. роЕро╡ро│рпБроХрпНроХрпБроорпН роЯрпАро╕рогрпНроЯро╛ роЬрпАройрпНро╕рпН, ро╖ро╛ро░рпНроЯрпНро╕рпН, ро╖ро░рпНроЯрпНро╕рпНройрпБ роОро╡рпНро╡ро│ро╡рпЛ роЗро░рпБроХрпНроХрпБ. родрпЗроЯро┐родрпНродрпЗроЯро┐ роороЯро┐роЪро╛ро░рпНройрпБ  роТро░рпБ роЯроЬройрпН ро╡ро╛роЩрпНроХро┐роЯрпНроЯрпБ ро╡роирпНродро┐ро░рпБроХрпНроХро╛. роирпАро│ роирпАро│рооро╛. роОрокрпНрокроЯро┐родрпНродро╛ройрпН роХроЯрпНроЯро┐рогрпНроЯро╛ро│рпЛ, рокро╛ро░рпНродрпНродро╛ро▓рпЗ родро▓рпИ роЪрпБродрпНродрпБродрпБ. роХрпЗроЯрпНроЯро╛ роЗродрпБро▓родро╛ройрпН тАШроГрокрпЖрооро┐ройрпИройрпН ро▓рпБроХрпНтАЩ роЗро░рпБроХрпНроХрпБройрпНройрпБ роЪрпКро▓рпНро▒ро╛.тАЭ

тАЬро╕ро┐роорпНрокрпНро▓ро┐ ро╡рпЗро╕рпНроЯро┐роЩрпН роЯрпИроорпН роЕрогрпНроЯрпН роОройро░рпНроЬро┐.тАЭ

тАЬроЕроирпНродродрпН родро▓рпИ роорпБроЯро┐роп роТро┤рпБроЩрпНроХро╛ роХрпНро░ро╛рокрпН рокрогрпНрогро┐ роЯрпНро░ро┐роорпНрооро╛ роЗро░рпБроХрпНроХ ро╡рпЗрогрпНроЯро╛рооро╛? роОройрпНройро╡рпЖро▓рпНро▓ро╛роорпЛ родроЯро╡ро┐, роорпБроЯро┐ропрпИрокрпН рокрпЛропрпН роорпБроЯрпНроЯро┐ ро╡ро░рпИроХрпНроХрпБроорпН ро╡ро│ро░рпНродрпНродрпБ ро╡роЪрпНроЪро┐ро░рпБроХрпНроХро╛. родро┐ройроорпН роЕрод ро╡ро╛ро░ро┐, ро╡ро┐родро╡ро┐родрооро╛ рокро┐ройрпНройро┐, роЕродрпБро▓ рокрпВ ро╡рпЗро▒ ро╡роЪрпНроЪрпБ тАж. роЕродро┐ро▓рпНро▓рпИройрпНройро╛ роЪрпЗро░рпНродрпНродрпБ рокро┐роЯро┐родрпНродрпБ роОройрпНройро╡рпЛ рокрогрпНрогро┐ роХрпКрогрпНроЯрпИ, роХрпЛроЯро╛ро▓ро┐ роорпБроЯро┐роЪрпНроЪрпБройрпНройрпБ... роорпБроХродрпНродрпБро▓ роЗро╡рпНро╡ро│ро╡рпБ роороЮрпНроЪро│рпИ роЕрокрпНрокро┐рогрпНроЯрпБ.. роЗродрпБроХрпНроХрпБройрпНройрпБ роПродрпЗродрпЛ роорпВро▓ро┐роХрпИропрпЖро▓рпНро▓ро╛роорпН родрпЛроЯрпНроЯродрпНродрпБро▓ ро╡ро│ро░рпНродрпНродрпБ ро╡роЪрпНроЪро┐ро░рпБроХрпНроХро╛. рокро╛ро░рпНродрпНродрпЗройрпНтАЭ

тАЬроЖро░рпНроХро╛ройро┐роХрпН ро╣рпЖро░рпНрокрпНро╕рпН..тАЭ

тАЬроиро╛ройрпН ропрпВро╕рпН рокрогрпНро▒родрпБ роОро▓рпНро▓ро╛роорпН роХрпЖрооро┐роХрпНроХро▓ро╛роорпН. роЗродрпБ роороЯрпНроЯрпБрооро╛, роХро╛родрпБро▓ роорпВроХрпНроХрпБро▓ роОро▓рпНро▓ро╛роорпН роУроЯрпНроЯрпИ рокрпЛроЯрпНроЯрпБтАж роЕродрпБроХрпНроХрпБ родройро┐ропро╛ родроЩрпНроХроорпН, ро╡рпИро░роорпНройрпБ роОроХрпНро╕рпНроЯрпНро░ро╛ роГрокро┐роЯрпНроЯро┐роЩрпН. ро╖ро┐роЯрпНтАЭ

тАЬроЗродрпЖро▓рпНро▓ро╛роорпН ро╡ро┐роЯрпБ. роХрпБро┤роирпНродрпИропрпИ роЕро┤роХро╛ ро╡ро┐ро╖рпНройрпБ роХрпВрокрпНрокро┐роЯроХрпН роХрпВроЯро╛родро╛роорпН. ро╡ро┐ро╕рпНро╡роиро╛родройрпНройрпБ роТро╡рпНро╡рпКро░рпБ родроЯро╡рпИропрпБроорпН роЗро┤рпБродрпНродро╛родрпНродро╛ройрпН рокрпЗро░рпЛроЯ роорпАройро┐роЩрпН рокрпБро░ро┐ропрпБрооро╛роорпН. роЯроЩрпН ро╕рпНро▓ро┐рокрпН роЖроХро┐роЯрпБродрпБ.тАЭ

тАЬро╣рпНроорпН. роЗройрпНройрпБроорпН роОройрпНройрпЖройрпНрой рокро╛роХрпНроХро┐ роЗро░рпБроХрпНроХрпЛ? роХро╛роЯрпН роТройрпНро▓ро┐ роирпЛро╕рпНтАЭ

тАЬроХро▓ро┐роХро╛ро▓роорпН роХро▓ро┐роХро╛ро▓роорпНтАжтАЭ
** DONE роЗрокрпНрокроЯро┐роХрпНроХрпБ ро░ро╛роорпБ :роЪро┐ро▒рпБроХродрпИ:
CLOSED: [2021-06-06 Sun 20:16]
:PROPERTIES:
:EXPORT_FILE_NAME: ippadikku-ramu
:END:
 6/1994

   роТро░рпБ рокрпКройрпНрооро╛ро▓рпИрокрпН рокрпКро┤рпБродро┐ро▓рпН ро░ро╛роорпБро╡ро╛роХро┐роп роиро╛ройрпН роЗроирпНрод роЙро▓роХродрпНродрпИ роОроЯрпНроЯро┐рокрпН рокро╛ро░рпНродрпНродродрпБроорпН роорпБродро▓ро┐ро▓рпН роХрпЗроЯрпНроЯродрпБ, тАЬроиро▓рпНро▓ ро╡рпЗро│рпИ роЖрогрпНрокро┐ро│рпНро│рпИ. ро░роЩрпНроХройрпБроХрпНроХрпБ роЗройро┐ роХро╡ро▓рпИропро┐ро▓рпНро▓рпИ. роороХройрпН роЪроорпНрокро╛ро░ро┐роЪрпНроЪрпБрокрпН рокрпЛроЯрпНроЯрпБроЯрпБро╡ро╛ройрпНтАЭ

   \\

 6/1999

   ро╕рпНроХрпВро▓рпБроХрпНроХрпБрокрпН рокрпЛроХродрпН родрпКроЯроЩрпНроХро┐ропро┐ро░рпБроХрпНроХрпЗройрпН. роорпБродро▓рпНро▓ рокропрооро╛роХ, роЪроЩрпНроХроЯрооро╛роХ роЗро░рпБроирпНродро╛ро▓рпБроорпН роЗрокрпНрокрпЛ роЬро╛ро▓ро┐ропро╛родрпНродро╛ройрпН роЗро░рпБроХрпНроХрпБ. роОрокрпНрокро╡рпБроорпН ро╡ро┐ро│рпИропро╛роЯрпНроЯрпБродрпНродро╛ройрпН. роТро░рпБ рооро╛ро╕рпНроЯро░рпБроорпН роТро░рпБ роЯрпАроЪрпНроЪро░рпБроорпН роЗро░рпБроХрпНроХро╛роЩрпНроХ. рооро╛ро╕рпНроЯро░рпН роТройрпНро▒ро╛роорпН родрпЗродро┐ роороЯрпНроЯрпБроорпН ро╡ро░рпБро╡ро╛ро░рпН. роЯрпАроЪрпНроЪро░рпН роЕрокрпНрокрокрпНрокрпЛ ро╡роирпНродрпБроЯрпНроЯрпБ роЙроЯройрпЗ роХро┐ро│роорпНрокро┐роЯрпБро╡ро╛роЩрпНроХ. ро░рпЖрогрпНроЯрпБ рокрпЗро░рпБроорпН роПродрпЛ ро╡роЯрпНроЯро┐ ро╡ро┐ропро╛рокро╛ро░роорпН рокрогрпНро▒родро╛ рокроЪроЩрпНроХ роЪрпКро▓рпНро▒ро╛роЩрпНроХ.

   \\

6/2004

   роЕрокрпНрокро╛ро╡рпБроХрпНроХрпБ роЯро┐ро░ро╛ройрпНро╕рпНрокро░рпН роЖроХро┐ропро┐ро░рпБроХрпНроХрпБ. роЗродрпБ роХрпКроЮрпНроЪроорпН рокрпЖро░ро┐роп роКро░рпН. роТро░рпБ роорпЖроЯрпНро░ро┐роХрпБро▓рпЗро╖ройрпН ро╕рпНроХрпВро▓рпНро▓ роЖро▒ро╛роорпН ро╡роХрпБрокрпНрокрпБ роЪрпЗро░рпНроирпНродро┐ро░рпБроХрпНроХрпЗройрпН. рокрпБродрпБ ро╕рпНроХрпВро▓рпН, рокрпБродрпБ ропрпВройро┐роГрокро╛ро░рпНроорпН, рокрпБродрпБ рокрпЗроХрпН роЪрпВрокрпНрокро░ро╛родрпНродро╛ройрпН роЗро░рпБроХрпНроХрпБ. ро░ро┐роХрпНтАМро╖ро╛ро▓ родро╛ройрпН роЗроЯроорпН рокродрпНродро▓. ро░рпКроорпНрок роирпЖро░рпБроХрпНроХроЯро┐. рокро▓ роЪрооропроЩрпНроХро│ро┐ро▓рпН рокропрооро╛ роЗро░рпБроХрпНроХрпБроорпН.

   роЖройро╛ роЕроорпНрооро╛ роПройрпН роЗрокрпНрокроЯро┐ роХро╡ро▓рпИропрпЛроЯ роЗро░рпБроХрпНроХро╛роЩрпНроХройрпНройрпБ рокрпБро░ро┐ропро▓. "роПроЩрпНроХ, ро░ро╛роорпБро╡ роЗрокрпНрок роЗрокрпНрокроЯро┐ рокро┐ро░рпИро╡рпЗроЯрпН ро╕рпНроХрпВро▓рпНро▓ роХрпКрогрпНроЯрпБ роЪрпЗро░рпНродрпНродро┐ро░рпБроХрпНроХрпАроЩрпНроХро│рпЗ. роироороХрпНроХрпБ роХроЯрпНроЯрпБрокрпНрокроЯро┐ропро╛роХрпБрооро╛"ройрпНройрпБ рокрпБро▓роорпНрокро▒ро╛роЩрпНроХ.

   "роПрогрпНроЯро┐, роиро╛ройрпН родро╛ройрпН роиро▓рпНро▓ро╛ рокроЯро┐роХрпНроХро╛роо рокро┐ропрпВройро╛ро╡рпЗ роЗро░рпБроХрпНроХрпЗройрпН. роЗро╡ройрпИропро╛ро╡родрпБ роиро▓рпНро▓ро╛ рокроЯро┐роХрпНроХ ро╡роЪрпНроЪрпБ роЯро╛роХрпНроЯро░рпЛ, роЗройрпНроЬро┐ройро┐ропро░рпЛ роЖроХрпНроХ ро╡рпЗрогрпНроЯро╛рооро╛? роХрпКроЮрпНроЪроорпН роЪро┐ро░роорокрпН рокроЯрпНроЯро╛ро╡родрпБ роГрокрпАро╕рпН роХроЯрпНроЯро┐роЯро▓ро╛роорпН. роХро╡ро▓рпИрокрпНрокроЯро╛родрпЗ. рокрпЖро░ро┐ропро╡ройро╛ройродрпБроорпН роЕро╡ройрпН роироорпНрооро│ родроЩрпНроХродрпН родро╛роорпНрокро╛ро│родрпНродрпБро▓ ро╡роЪрпНроЪрпБ родро╛роЩрпНроХрокрпН рокрпЛро▒ро╛ройрпН рокро╛ро░рпБ"

   роЖройро╛ роХрпКроЮрпНроЪ роиро╛ро│ро╛ роОройроХрпНроХрпБ роЗроирпНрод ро╕рпНроХрпВро▓рпН рокро┐роЯро┐роХрпНроХро▓. роПрокро┐роЪро┐роЯро┐, роЖройро╛ роЖро╡ройрпНройро╛ роХрпВроЯ роТро┤рпБроЩрпНроХро╛ роОро┤рпБродродрпН родрпЖро░ро┐ропро▓рпИройрпНройрпБ рокроЪроЩрпНроХро│рпБроорпН рооро┐ро╕рпНро╕рпБроорпН ро░рпКроорпНрок роХрпЗро▓ро┐ рокрогрпНро▒ро╛роЩрпНроХ. роГрокрпЖропро┐ро▓ро╛ропро┐роЯрпБро╡рпЗройрпНройрпБ   рокропроорпБро▒рпБродрпНродро▒ро╛роЩрпНроХ.  рокро┤рпИроп ро╕рпНроХрпВро▓рпНро▓ рокро┐ро░роЪрпНроЪройрпИропрпЗ роХро┐роЯрпИропро╛родрпБ. роЪрпБроорпНрооро╛ ро╕рпНроХрпВро▓рпБроХрпНроХрпБ рокрпЛройро╛ро▓рпЗ 'роЖро▓рпНрокро╛ро╕рпН' родро╛ройрпН.

   \\

6/2006

   роЗроирпНрод ро╡ро░рпБро╖родрпНродро┐ро▓ро┐ро░рпБроирпНродрпБ ропрпВройро┐роГрокро╛ро░рпНроорпН роГрокрпБро▓рпН рокрпЗрогрпНроЯрпН, роГрокрпБро▓рпН ро╖ро░рпНроЯрпН. роОроЯрпНроЯро╛ро╡родрпБ ро╡роирпНродро╛роЪрпНроЪрпБ роЗро▓рпНро▓ро┐ропро╛?

   роХро┐ро│ро╛ро╕рпНро▓ роХрпЗро░рпНро│рпНро╕рпН роОро▓рпНро▓ро╛роорпН роХро┐роЯрпБроХро┐роЯрпБройрпНройрпБ ро╡ро│ро░рпНроирпНродрпБроЯрпНроЯро┐ро░рпБроХрпНроХро╛роЩрпНроХ. рокроЪроЩрпНроХро│рпБроХрпНроХрпБроорпН роиро┐ро▒рпИроп рокрпЗро░рпБроХрпНроХрпБ роорпАроЪрпИ ро╡роирпНродрпБроЯрпНроЯро┐ро░рпБроХрпНроХрпБ. роОройроХрпНроХрпБ роороЯрпНроЯрпБроорпН ро╡ро░ро▓ро┐ропрпЗ. роорпАроЪрпИ ро╡ро│ро░ роОройрпНрой роЪрпЖропрпНропрогрпБроорпН? ропро╛ро░рпНроХро┐роЯрпНроЯ роХрпЗроЯрпНрокродрпБ? роХрпВроЪрпНроЪрооро╛ роЗро░рпБроХрпНроХрпБ. роХро┐рогрпНроЯро▓роЯро┐рокрпНрокро╛роЩрпНроХро│рпЛ? родроЩрпНроХроЪрпНроЪро┐ропрпЛроЯ роХрогрпНроорпИропро╛ро▓ ро▓рпЗроЪро╛ ро╡ро░рпИроЮрпНроЪрпБрокрпН рокро╛ро░рпНродрпНродрпЗройрпН. роЪрпЛро│роХрпН роХрпКро▓рпНро▓рпИ рокрпКроорпНроорпИ рооро╛родро┐ро░ро┐ роЗро░рпБроирпНродродрпБ. родрогрпНрогрпАро░рпН ро╡ро┐роЯрпНроЯрпБ роЕро┤ро┐роЪрпНроЪродрпБро▓ роЗройрпНройрпБроорпН роЕроЪро┐роЩрпНроХрооро╛ рокро░ро╡ро┐роЯрпБроЪрпНроЪрпБ. роорпБроХродрпНродрпИ роорпВроЯро┐роХрпНроХро┐роЯрпНроЯрпБ рокроЯрпБродрпНродрпБроЯрпНроЯрпЗройрпН.

   \\



6/2007

   роТройрпНрокродро╛роорпН ро╡роХрпБрокрпНрокрпБ рокрпБроХрпНро╕рпН ро╡ро╛роЩрпНроХродрпН родрпЗро╡рпИропро┐ро▓рпНро▓рпИ. роЯрпЖройрпНродрпН рокрпЛро░рпНро╖ройрпИ роЗрокрпНрокро╡рпЗ родрпКроЯроЩрпНроХро┐ропро╛роЪрпНроЪрпБ. рокрпБро░ро┐ропро╡рпЗ рооро╛роЯрпНроЯрпЗроЩрпНроХрпБродрпБ. роХрпЗроЯрпНроЯро╛ роЕроЯро┐роХрпНроХро┐ро▒ро╛роЩрпНроХ. роЯро┐ропрпВро╖ройрпН ро╡роЪрпНроЪро╛ роиро▓рпНро▓родрпБройрпНройрпБ ро╕рпНроХрпВро▓рпНро▓ роЪрпКро▓рпНро▓, рооро┐ро╕рпНроХро┐роЯрпНроЯропрпЗ роЯро┐ропрпВро╖ройрпБроХрпНроХрпБ роЪрпЗро░рпНроирпНродро┐ро░рпБроХрпНроХрпЗройрпН.

   ро╕рпНроХрпВро▓рпН рооро╛родро┐ро░ро┐ропрпЗ родро╛ройрпН роЗроЩрпНроХрпЗропрпБроорпН рооро┐ро╕рпН роЪрпКро▓рпНро▓ро┐родрпН родро░рпНро▒ро╛роЩрпНроХ. ро╕рпНроХрпВро▓рпНро▓ропро╛ро╡родрпБ роиро╛ро▒рпНрокродрпБ рокрпЗро░рпН родро╛ройрпН. роЗроЩрпНроХрпЗ роРроорпНрокродрпНродрпИроирпНродрпБ рокрпЗро░рпН. роЪрпБродрпНрод рокрпЛро░рпН.

   ро░ро╛родрпНродро┐ро░ро┐ роЖропро┐роЯрпНроЯро╛ роЬро╛ро▓ро┐родро╛ройрпН. роОройрпНройрпИропрпБроорпН родроЩрпНроХроЪрпНроЪро┐ропрпИропрпБроорпН рокроЯро┐роХрпНроХроЪрпН роЪрпКро▓рпНро▓ро┐роЯрпНроЯрпБ роЕроорпНрооро╛, роЕрокрпНрокро╛ роЯрпАро╡ро┐ роЪрпАро░ро┐ропро▓рпНро▓ роорпВро┤рпНроХро┐роЯрпБро╡ро╛роЩрпНроХ. ро╣рпЛроорпНро╡ро░рпНроХрпН рокрогрпНро▒ рооро╛родро┐ро░ро┐ роУро░рооро╛ роЙроЯрпНроХро╛ро░рпНроирпНродрпБ роиро╛ройрпБроорпН рокро╛ро░рпНродрпНродрпБроЯрпНроЯро┐ро░рпБрокрпНрокрпЗройрпН. ро╡ро┐ро│роорпНрокро░роорпН ро╡ро░рпНро▒рокрпНрок роороЯрпНроЯрпБроорпН родро▓рпИроп рокрпБроХрпНро╕рпНро▓ рокрпБродрпИроЪрпНроЪрпБроЯрпБро╡рпЗройрпН. родроЩрпНроХроЪрпНроЪро┐ропрпБроорпН роЕрокрпНрокроЯро┐родрпНродро╛ройрпН. роЖройро╛ роТро░рпБродрпНродро░рпИропрпКро░рпБродрпНродро░рпН роХро╛роЯрпНроЯро┐роХрпН роХрпКроЯрпБроХрпНроХ рооро╛роЯрпНроЯрпЛроорпН. роЯрпАро╡ро┐ро▓ роЪро┐ройро┐рооро╛, роЪрпАро░ро┐ропро▓рпН роОро▓рпНро▓ро╛роорпЗ роиро▓рпНро▓ро╛ роЗро░рпБроХрпНроХрпБроорпН. роиро╛ро│рпИ роОройрпНрой ро╡ро░рпБроорпЛройрпНройрпБ ро╡ро┐ро▒рпБро╡ро┐ро▒рпБрокрпНрокро╛роХ роЗро░рпБроХрпНроХрпБроорпН.

   \\



6 / 2008

   рокродрпНродро╛роорпН ро╡роХрпБрокрпНрокрпБ роЗро▓рпНро▓рпИропро╛? рокрпКродрпБродрпНродрпЗро░рпНро╡рпБ роОро┤рпБродрогрпБроорпН. рокроЯро┐рокрпНрокрпБ рокроЯро┐рокрпНрокрпБ рокроЯро┐рокрпНрокрпБродро╛ройрпН. роЪро░ро┐ропро╛ роХрпБро│ро┐роХрпНроХ, роЪро╛рокрпНрокро┐роЯ, роПройрпН рокро╛родрпНро░рпВроорпН рокрпЛроХроХрпНроХрпВроЯ роирпЗро░рооро┐ро▓рпНро▓рпИ. родро┐ройроорпН роХро╛ро▓рпИропро┐ро▓ роЯро┐ропрпВро╖ройрпН, ро╕рпНроХрпВро▓рпН, роОроХрпНро╕рпНроЯрпНро░ро╛ роХро┐ро│ро╛ро╕рпН, рооро▒рпБрокроЯро┐ роЯро┐ропрпВро╖ройрпН, ро╣рпЛроорпН ро╡рпКро░рпНроХрпН... роХрогрпНрогрпИ роорпВроЯро┐ройро╛ рокрпВроЪрпНроЪро┐ рокро▒роХрпНроХро┐ро▒ рооро╛родро┐ро░ро┐ роЗро░рпБроХрпНроХрпБ. ро░рпКроорпНрок  роЕроЪродро┐ропро╛ роЗро░рпБроХрпНроХрпБ. рокро╛роЯроЩрпНроХро│рпИ рокрпБро░ро┐роЮрпНроЪро┐роХрпНроХро╡рпЗ роирпЗро░рооро┐ро▓рпНро▓рпИ. роирпЖроЯрпНроЯрпБро░рпБ рокрпЛроЯрпНроЯро╛ро▓рпБроорпН рооро▒рпБроиро╛ро│рпН рооро▒роирпНродрпБроЯрпБродрпБ. родрпВроХрпНроХроорпЗ ро╡ро░рооро╛роЯрпНроЯрпЗроЩрпНроХрпБродрпБ..

   рооро╛роЯро▓рпН роЯрпЖро╕рпНроЯрпНро▓ ро╡ро░рпБрогрпН роиро▓рпНро▓ рооро╛ро░рпНроХрпН ро╡ро╛роЩрпНроХро┐ропро┐ро░рпБроХрпНроХро╛ройрпН. роиро╛ройрпН ро╡ро┤роХрпНроХроорпН рокрпЛро▓ роЪро░ро╛роЪро░ро┐ родро╛ройрпН. роЕрокрпНрокро╛ родро┐роЯрпНроЯро▒ро╛ро░рпН. "роЕродрпЗ ро╕рпНроХрпВро▓рпНро▓ рокроЯро┐роЪрпНроЪ роЕро╡ройрпН роороЯрпНроЯрпБроорпН роиро▓рпНро▓ рооро╛ро░рпНроХрпН ро╡ро╛роЩрпНроХро▒ро╛ройрпЗ. роЙройроХрпНроХрпБ роОройрпНрой роХрпЗроЯрпБ?".. родрпЖро░ро┐ропро▓рпИропрпЗ

   \\

5 / 2009

  рокрпКродрпБродрпН родрпЗро░рпНро╡рпБродрпН 58% родро╛ройрпН. роЕроорпНрооро╛ро╡рпБроорпН роЕрокрпНрокро╛ро╡рпБроорпН роТро░рпБ ро╡ро╛ро░рооро╛ рокрпЗроЪро╡рпЗропро┐ро▓рпНро▓рпИ. роОройрпНройро╛ро▓рпН роЗро╡рпНро╡ро│ро╡рпБродро╛ройрпЗ роорпБроЯро┐роЮрпНроЪродрпБ??

  \\

6 / 2009

   рокро┤рпИроп ро╕рпНроХрпВро▓рпНро▓ роГрокро░рпНро╕рпНроЯрпН роХрпНро░рпВрокрпН роЗроЯроорпН роХро┐роЯрпИроХрпНроХро▓рпИ. роХрпКроЮрпНроЪроорпН родрпВро░родрпНродро┐ро▓ ро╡рпЗро▒ ро╕рпНроХрпВро▓рпНро▓ роЪрпЗро░рпНроирпНродро┐ро░рпБроХрпНроХрпЗройрпН. роЗродрпБ роХрпВроЯ роЕрокрпНрокро╛ рокро╛ро░рпНроЯрпН роГрокрпИройро▓рпН ро▓рпЛройрпН роПродрпЛ роОроЯрпБродрпНродрпБ роЯрпКройрпЗро╖ройрпН роХрпКроЯрпБродрпНродрпБродрпНродро╛ройрпН роХро┐роЯрпИродрпНродродрпБ. ро░рпЖрогрпНроЯрпБ рокрпЗро░рпН ро╕рпНроХрпВро▓рпН рокрпАро╕рпН,  ро╡ро╛роЯроХрпИ, роЗройрпНройрпБроорпН роиро┐ро▒рпИроп роЪрпЖро▓ро╡рпБроХро│рпНтАж роЕрокрпНрокро╛ родро┐рогро▒рпБро╡родрпИрокрпН рокро╛ро░рпНроХрпНроХ роХро╖рпНроЯрооро╛роХ роЗро░рпБроХрпНроХрпБ.

   ро╕рпНроХрпВро▓рпН родро┐ро▒роирпНродродрпБроорпЗ рокройрпНройро┐ро░рогрпНроЯро╛роорпН ро╡роХрпБрокрпНрокрпБ рокро╛роЯроорпН роЖро░роорпНрокро┐роЪрпНроЪро╛роЪрпНроЪрпБ. рокродро┐ройрпКройрпНро▒ро╛роорпН ро╡роХрпБрокрпНрокрпБ рокро╛роЯроЩрпНроХро│рпИ ро╡ро┐роЯрпНроЯрпБ ро╡ро┐роЯрпНроЯрпБ роЕроЯрпБродрпНрод ро╡ро░рпБроЯ рокро╛роЯроЩрпНроХро│рпИ роОроЯрпБроХрпНроХрпБроорпНрокрпЛродрпБ роТройрпНро▒рпБроорпЗ рокрпБро░ро┐ро╡родро┐ро▓рпНро▓рпИ роОройрпНрокродрпИ ропро╛ро░рпН родро╛ройрпН роОроЯрпБродрпНродрпБ роЪрпКро▓рпНро╡родрпБ? роорпАрогрпНроЯрпБроорпН роЯро┐ропрпВро╖ройрпН, ро╕рпНроХрпВро▓рпН, роЯро┐ропрпВро╖ройрпН, ро╕рпНроХрпВро▓рпНтАж.

   \\

3 / 2011

   роиро╛ро│рпИ рооро▒рпБроиро╛ро│рпН рокро┐ро│ро╕рпН роЯрпВ родрпЗро░рпНро╡рпБ. роирпЗро▒рпНро▒рпБ ро╣рпЖроЯрпН рооро╛ро╕рпНроЯро░рпН роЕрокрпНрокро╛ро╡рпИ роЕро┤рпИродрпНродрпБ рокрпЗроЪро┐ропро┐ро░рпБроХрпНроХро┐ро▒ро╛ро░рпН.

   "роЗроЩрпНроХрпЗ рокро╛ро░рпБроЩрпНроХ роЙроЩрпНроХ роороХройрпН роорпЗродрпНро╕рпН, роХрпЖрооро┐ро╕рпНроЯрпНро░ро┐ ро░рпЖрогрпНроЯрпБро▓ропрпБроорпН ро░рпКроорпНрок ро╡рпАроХрпНроХро╛ роЗро░рпБроХрпНроХро╛ройрпН. роЗро╡ройрпН роЗрокрпНрок роОроХрпНро╕ро╛роорпН роОро┤рпБродро┐ роОройрпНрой рокро┐ро░ропрпЛроЬройроорпН? рокро╛ро╕ро╛роХро┐ро▒родрпЗ рокрпЖро░ро┐роп ро╡ро┐ро╖ропроорпН. роЗродрпБро▓ роорпЗро▒рпНрокроЯро┐рокрпНрокрпБроХрпНроХрпБ роОроЩрпНроХ роЗроЯроорпН роХро┐роЯрпИроХрпНроХрокрпН рокрпЛроХрпБродрпБ?"

   роЕрокрпНрокро╛ роЕро┤родрпН родрпКроЯроЩрпНроХро┐ ро╡ро┐роЯрпНроЯро╛ро░рпН рокрпЛро▓рпБроорпН.

   "роЕро┤ро╛родрпАроЩрпНроХ роЙроЩрпНроХро│рпИрокрпН рокро╛ро░рпНродрпНродро╛ро▓рпБроорпН рокро╛ро╡рооро╛родрпНродро╛ройрпН роЗро░рпБроХрпНроХрпБ. ро╡рпЗрогрпНроЯрпБрооро╛ройро╛ро▓рпН роТро░рпЗ роТро░рпБ ро╡ро┤ро┐ роЗро░рпБроХрпНроХрпБ."

   "роОройрпНрой роЪро╛ро░рпН? роЪрпКро▓рпНро▓рпБроЩрпНроХ роЪро╛ро░рпН."

   "роОроХрпНро╕ро╛роорпН родрпКроЯроЩрпНроХро┐ рокродрпНродрпБ роиро┐рооро┐роЯродрпНродрпБроХрпНроХрпБро│рпНро│ роОро▓рпНро▓ро╛ роХрпЗро│рпНро╡ро┐роХро│рпБроХрпНроХрпБроорпН ро╡ро┐роЯрпИроХро│рпИ роТро░рпБ рокрпЗрокрпНрокро░ро┐ро▓рпН рокро┐ро░ро┐рогрпНроЯрпН роОроЯрпБродрпНродрпБ роЕро╡ройрпН роХрпИропро┐ро▓ роХро┐роЯрпИроХрпНроХ роПро▒рпНрокро╛роЯрпБ роЪрпЖропрпНроХро┐ро▒рпЗройрпН. роЖройро╛ро▓рпН роЕродрпБроХрпНроХрпБ роХрпКроЮрпНроЪроорпН роЪрпЖро▓ро╡ро╛роХрпБроорпН. рокро░ро╡ро╛ропро┐ро▓рпНро▓рпИропро╛?"

   "роОро╡рпНро╡ро│ро╡рпБ роЪро╛ро░рпН?"

   роЕро╡ро░рпН роЪрпКройрпНрой родрпКроХрпИропрпИ роХрпЗроЯрпНроЯрпБ роЕрокрпНрокро╛ рооро┐ро░ро│, "роЙроЩрпНроХро│ро╛ро▓рпН роорпБроЯро┐ропро╛родрпБройрпНройро╛ ро╡ро┐роЯрпНроЯрпБроЯрпБроЩрпНроХ" роОройрпНро▒ро╛ро░рпН.

   рооро▒рпБрокрпЗроЪрпНроЪро┐ройрпНро▒ро┐ роЕро╡ро░рпН роХрпЗроЯрпНроЯродрпИ роЕрокрпНрокро╛ роЗройрпНро▒рпБ роХрпКроЯрпБродрпНродро╛ропро┐ро▒рпНро▒рпБ. роОроЩрпНроХрпЗ роХроЯройрпН ро╡ро╛роЩрпНроХро┐ройро╛ро░рпЛ родрпЖро░ро┐ропро▓рпИ.

   \\

8 / 2011

   рокрпНро│ро╕рпН роЯрпВ роОроХрпНро╕ро╛роорпН 'роиройрпНро▒ро╛роХ' роОро┤рпБродро┐ропродро╛ро▓рпН ро░рпКроорпНрок роиро▓рпНро▓ роородро┐рокрпНрокрпЖрогрпН. роиро▓рпНро▓ ро░рпЗроЩрпНроХрпН. роХрпЗроЯрпНроЯ роХро╛ро▓рпЗроЬро┐ро▓ роХрпЗроЯрпНроЯ роХрпБро░рпВрокрпН роХро┐роЯрпИродрпНродрпБро╡ро┐роЯрпНроЯродрпБ. роХро╛ро▓рпЗроЬрпН роГрокрпАро╕рпН роХроЯрпНроЯ роЕрокрпНрокро╛ роХроирпНродрпБро╡роЯрпНроЯро┐роХрпНроХро╛ро░ройро┐роЯроорпН роХроЯройрпН ро╡ро╛роЩрпНроХро┐ропро┐ро░рпБроХрпНроХро┐ро▒ро╛ро░рпН рокрпЛро▓ро┐ро░рпБроХрпНроХрпБ. родрпЖро│ро┐ро╡ро╛ роЪрпКро▓рпНро▓ рооро╛роЯрпНроЯрпЗройрпНроХро┐ро▒ро╛ро░рпН.

   \\

10 / 2011

   рокро╛роЯроЩрпНроХро│рпН роОродрпБро╡рпБроорпН роЪрпБродрпНродрооро╛ рокро┐роЯро┐рокроЯ рооро╛роЯрпНроЯрпЗроЩрпНроХрпБродрпБ. родро┐ройроорпН роЯрпЖро╕рпНроЯрпН, роЕро╕рпИройрпНроорпЖройрпНроЯрпН, рокрпНро░ро╛роХрпНроЯро┐роХро▓рпНро╕рпНтАж ропро╛ро░ро┐роЯроорпБроорпН роЪроирпНродрпЗроХроорпН роХрпЗроЯрпНроХ ро╡рпЖроЯрпНроХрооро╛ роЗро░рпБроХрпНроХрпБ. 'роЗроирпНрод роЕроЯро┐рокрпНрокроЯрпИ роХрпВроЯро╡ро╛ родрпЖро░ро┐ропро╛родрпБ'ройрпНройрпБ роХро┐рогрпНроЯро▓рпН рокрогрпНро▒ро╛роЩрпНроХ.

   \\

1 / 2012

   роГрокро░рпНро╕рпНроЯрпН роЪрпЖрооро╕рпНроЯро░рпН ро░ро┐ро╕ро▓рпНроЯрпН ро╡роирпНродрпБ ро╡ро┐роЯрпНроЯродрпБ. роиро╛ройрпНроХро┐ро▓рпН роорпВройрпНро▒рпБ рокро╛роЯроЩрпНроХро│ро┐ро▓рпН роГрокрпЖропро┐ро▓рпН. роЕрокрпНрокро╛ро╡ро┐роЯроорпН роЪрпКро▓рпНро▓ родрпИро░ро┐ропрооро┐ро▓рпНро▓рпИ. роОрокрпНрокро╛роЯрпБ рокроЯрпНроЯро╛ро╡родрпБ роЕроЯрпБродрпНрод роорпБро▒рпИ роОро▓рпНро▓ро╛ рокрпЗрокрпНрокро░рпБроорпН рокро╛ро╕ро╛ропро┐роЯрогрпБроорпН.

   \\

4 / 3 / 2012

   роХрпБрооро╛ро░рпН роКро░рпБроХрпНроХрпБ рокрпЛропрпН ро╡ро┐роЯрпНроЯрпБ роЗройрпНро▒рпБ роХро╛ро▓рпИ ро╡роирпНродро╛ройрпН. роОроЩрпНроХроорпНрооро╛ро╡рпБроХрпНроХрпБ роЙроЯроорпНрокрпБ роЪро░ро┐ропро┐ро▓рпНро▓рпИропро╛роорпН. роПродрпЛ роЖрокрпНро░рпЗро╖ройрпН рокрогрпНрогрогрпБрооро╛роорпН. рокрогроорпН роЗро▓рпНро▓ро╛родродро╛ро▓рпН рокрогрпНрогро╡ро┐ро▓рпНро▓рпИ рокрпЛро▓ро┐ро░рпБроХрпНроХрпБ роОройрпНро▒рпБ роЕро╡ройрпН роЕроорпНрооро╛ роЪрпКройрпНройро╛ро░рпНроХро│ро╛роорпН.          роЕроорпНрооро╛ро╡рпИ роЙроЯройрпЗ рокро╛ро░рпНроХрпНроХ ро╡рпЗрогрпНроЯрпБроорпН рокрпЛро▓ро┐ро░рпБроХрпНроХрпБ.

   роЕрокрпНрокро╛ро╡рпБроХрпНроХрпБ роГрокрпЛройрпН рокрогрпНрогро┐ройрпЗройрпН. роОроЯрпБродрпНродродрпБроорпЗ, "роиро▓рпНро▓ро╛ рокроЯро┐роХрпНроХро┐ро▒ро┐ропро╛рокрпНрокро╛? рокрпЛрой родроЯро╡рпИ рокрпЛро▓ро╡рпЗ роОро▓рпНро▓ро╛ рокро╛роЯродрпНродрпБро▓ропрпБроорпН роиро▓рпНро▓ рооро╛ро░рпНроХрпН ро╡ро╛роЩрпНроХрогрпБроорпНроЯро╛ ро░ро╛роЬро╛" роОройрпНроХро┐ро▒ро╛ро░рпН. роОродрпНродройрпИ роОродро┐ро░рпНрокро╛ро░рпНрокрпНрокрпБ, роироорпНрокро┐роХрпНроХрпИтАж

      ро╡рпАроЯрпНроЯрпИрокрпН рокро▒рпНро▒ро┐ роХрпЗроЯрпНроЯро╛ро▓рпН, "роирпА роПрогрпНроЯро╛ роЗродрпЖро▓рпНро▓ро╛роорпН ропрпЛроЪро┐роЪрпНроЪрпБроХрпНроХро┐роЯрпНроЯрпБ? роЖроЪрпНроЪрпБ, роЗройрпНройрпБроорпН роорпВрогрпБ ро╡ро░рпБро╖роорпН родро╛ройрпЗ? роиро▓рпНро▓ ро╡рпЗро▓рпИро▓ роЪрпЗро░рпНроирпНродрпБроЯрпНроЯро╛ роОро▓рпНро▓ро╛роорпН роЪро░ро┐ропро╛ропро┐роЯрпБроорпН."

   "роЕ.. роЖрооро╛роорпНрокро╛.."

   "роЖрооро╛, роиро▓рпНро▓ рокроЯро┐роХрпНроХро┐ро▒рпЗропро┐ро▓рпНро▓рпЗ?"

   роиро╛ройрпН роОройрпНройро╡рпЖройрпНро▒рпБ роЪрпКро▓рпНро╡рпЗройрпН? рокрпЛрой роЪрпЖрооро╕рпНроЯро░ро┐ройрпН роорпВройрпНро▒рпБ роЕро░ро┐ропро░рпНроЪрпИропро╛? роЗроирпНрод роЪрпЖрооро╕рпНроЯро░рпН роЕродрпИро╡ро┐роЯ роХроЯро┐ройрооро╛роХ роЗро░рпБрокрпНрокродрпИропро╛?

   \\

4 / 4 / 2012

   роОроХрпНро╕ро╛роорпБроХрпНроХрпБ роЗройрпНройрпБроорпН роорпВройрпНро▒рпБ роиро╛ро│рпН роЗро░рпБроХрпНроХрпБ.   роЕро▒рпИропро┐ро▓рпН роиро╛ройрпНроХрпБ рокроХрпНроХроорпБроорпН рокрпБродрпНродроХроЩрпНроХро│рпН. роХрпБро┤рокрпНрокрооро╛роХ роЗро░рпБроХрпНроХрпБ. роЕроЯро┐ро╡ропро┐ро▒рпНро▒рпИ  рокро┐роЪрпИроХро┐ро▒родрпБ. роЕро┤рпБроХрпИ роЕро┤рпБроХрпИропро╛роХ ро╡ро░рпБроХро┐ро▒родрпБ. роиро╛ройрпН роОройрпНрой родрокрпНрокрпБ роЪрпЖропрпНродрпЗройрпН?

   рокрпНро░рпИрооро░ро┐ ро╕рпНроХрпВро▓ро┐ро▓рпН роЯрпАроЪрпНроЪро░рпНро╕рпН роТро┤рпБроЩрпНроХро╛роХ роЕроЯро┐рокрпНрокроЯрпИ рокро╛роЯроЩрпНроХро│рпИ роЪрпКро▓рпНро▓ро┐ родроирпНродро┐ро░рпБроХрпНроХроХрпН роХрпВроЯро╛родро╛?

   ро╣рпИро╕рпНроХрпВро▓ро┐ро▓ро╛ро╡родрпБ роЙро░рпБрокрпНрокрпЛроЯ ро╡рпИроХрпНроХро╛рооро▓рпН рокро╛роЯроЩрпНроХро│рпИ рокрпБро░ро┐роп ро╡рпИродрпНродро┐ро░рпБроХрпНроХроХрпН роХрпВроЯро╛родро╛?

   ро╣рпЖроЯрпН рооро╛ро╕рпНроЯро░рпН роЪроорпНрокро╛родро┐роХрпНроХ роОройрпН роЗропро▓ро╛роорпИ родро╛ройрпН роХро┐роЯрпИродрпНродродро╛? роЕродро▒рпНроХрпБ роЕрокрпНрокро╛, роирпАроЩрпНроХ роПройрпН роЪроорпНроородро┐роЪрпНроЪрпАроЩрпНроХ?

   роОройрпНройро╛ро▓рпН роорпБроЯро┐ропрпБрооро╛ роОройрпНро▒рпБ ропрпЛроЪро┐роХрпНроХро╛рооро▓рпН роороХройрпИ рокрпЖро░ро┐роп роОройрпНроЬро┐ройрпАропро░рпН роЖроХрогрпБроорпНройрпБ роирпАроЩрпНроХро│ро╛ро╡рпЗ роПройрпНрокро╛ роорпБроЯро┐ро╡рпБ роЪрпЖроЮрпНроЪрпАроЩрпНроХ?

   роЕрокрпНрокро╛.. роЕроорпНрооро╛тАж роЗрокрпНрок роОройрпНройро╛ро▓рпН роорпБроЯро┐ропро▓ро┐ропрпЗ.

   родроЩрпНроХроЪрпНроЪро┐ рокроЯро┐рокрпНрокрпБ, роХро▓рпНропро╛рогроорпН, роЕроорпНрооро╛ ро╡рпИродрпНродро┐ропроорпН.. роПро▒рпНроХройро╡рпЗ роОройроХрпНроХро╛роХ роОройрпНройрпИ роироорпНрокро┐ роПроХрокрпНрокроЯрпНроЯ роХроЯройрпНроХро│рпНтАж роРропрпЛ, роиро╛ройрпН роОройрпНрой роЪрпЖропрпНро╡рпЗройрпН?

   роиро╛ройрпН роОройрпНрой роЪрпЖропрпНро╡рпЗройрпНтАж?

...

   ро▓рпКроЯро▓рпКроЯро╡рпЖройрпНро▒рпБ рооро┐ройрпНро╡ро┐роЪро┐ро▒ро┐ роЪрпБро┤ро▓, роХроЯрпНроЯро┐ро▓ро┐ро▓рпН роЕро╡ро┐ро┤рпНродрпНродрпБрокрпН рокрпЛроЯрпНроЯро┐ро░рпБроирпНрод роХрпИро▓ро┐ропрпИрокрпН рокро╛ро░рпНродрпНродродрпБроорпН роОройрпНрой роЪрпЖропрпНропро▓ро╛роорпН роОройрпНрокродрпБ рокрпБро░ро┐роирпНродрпБ ро╡ро┐роЯрпНроЯродрпБ.

   роТро░рпБ рокрпЗрокрпНрокро░рпИ роХро┐ро┤ро┐родрпНродрпБ роОро┤рпБродродрпН родрпКроЯроЩрпНроХро┐ройрпЗройрпН, 'роХро╛ро╡ро▓рпН родрпБро▒рпИропро┐ройро░рпБроХрпНроХрпБ роОройрпН родро▒рпНроХрпКро▓рпИроХрпНроХрпБ ропро╛ро░рпБроорпН рокрпКро▒рпБрокрпНрокро┐ро▓рпНро▓рпИ - роЗрокрпНрокроЯро┐роХрпНроХрпБ ро░ро╛роорпБ'

   " роЯрпЗропрпН ро░ро╛роорпБ.  роорпБро░рпБроХройрпН родрпВроХрпНроХ рооро╛родрпНродро┐ро░рпИ роЪро╛рокрпНрокро┐роЯрпНроЯрпБроЯрпНроЯро╛ройро╛роорпН. роУроЯро┐ ро╡ро╛" роХродро╡рпИродрпН родроЯрпНроЯро┐ропро╡ро╛ро▒рпБ роХродрпНродро┐роХрпНроХрпКрогрпНроЯрпЗ роУроЯро┐ройро╛ройрпН роХрпБрооро╛ро░рпН.

   роОройрпНрой? роироорпНроо роорпБро░рпБроХройро╛? роПройрпН? роУ.. роЕро╡ройрпБроХрпНроХрпБ роОро▓рпНро▓ро╛ рокрпЗрокрпНрокро░рпБроорпН роЕро░ро┐ропро░рпНро╕рпН. рокрпБродрпБроЪро╛ ро╡роирпНрод роХро╛родро▓рпБроорпН роКродрпНродро┐роХрпНроХро┐роЪрпНроЪрпБ. роЖройро╛ро▓рпН роЕродрпБроХрпНроХро╛роХ роЗрокрпНрокроЯро┐ропро╛? роорпБроЯрпНроЯро╛ро│рпН.. роХрпЛро┤рпИ..

   роЙроЯрпНроХро╛ро░рпНроирпНродрпБ ропрпЛроЪро┐роЪрпНроЪро╛ роорпБроЯро┐ро╡рпБ роХро┐роЯрпИроХрпНроХро╛род рокро┐ро░роЪрпНройрпИройрпНройрпБ роПродрпБроорпН роЗро░рпБроХрпНроХро╛ роОройрпНрой?

   роХрпИропро┐ро▓ро┐ро░рпБроирпНрод рокрпЗрокрпНрокро░рпИ роХроЪроХрпНроХро┐ роОро▒ро┐роирпНродрпБ ро╡ро┐роЯрпНроЯрпБ роорпБро░рпБроХройрпН ро░рпВроорпБроХрпНроХрпБ роУроЯро┐ройрпЗройрпН.

   роиро┐роЪрпНроЪропроорпН роЕро╡ройрпИроХрпН роХро╛рокрпНрокро╛ро▒рпНро▒ро┐ ро╡ро┐роЯрпБро╡рпЛроорпН.

   (роПрокрпНро░ро▓рпН 1-15, 2014,  роороЩрпНроХрпИропро░рпН рооро▓ро░рпН роЗродро┤ро┐ро▓рпН рокро┐ро░роЪрпБро░рооро╛ройродрпБ.)




** DONE роХро░рпЖрогрпНроЯрпН рокрпЛройро╛родрпНродро╛ройрпЗ... :роЪро┐ро▒рпБроХродрпИ:
CLOSED: [2021-06-07 Mon 23:15]
:PROPERTIES:
:EXPORT_FILE_NAME: current-ponathane
:END:
роорогро┐ роОроЯрпНроЯроЯро┐родрпНродрпБ рокродрпНродрпБ роиро┐рооро┐роЯроЩрпНроХро│рпБроорпН роЖроХро┐ ро╡ро┐роЯрпНроЯродрпБ. роЗройрпНро▒рпБ роЗройрпНройрпБроорпН роПройрпН роХро░рпЖрогрпНроЯрпН рокрпЛроХро╡ро┐ро▓рпНро▓рпИ?

   роиро╛ройрпНроХрпБ ро╡ропродрпБ роородрпБрооро┐родро╛ роХро╡ро▓рпИропрпБроЯройрпН роЪрпБро▒рпНро▒ро┐роЪрпН роЪрпБро▒рпНро▒ро┐ ро╡роирпНродро╛ро│рпН.

   "роЕрокрпНрокро╛тАж"



   роороХро│рпН роЕро┤рпИродрпНродродрпБ роЪроЩрпНроХро░ро┐ройрпН роХро╛родрпБроХро│ро┐ро▓рпН ро╡ро┐ро┤рпБроирпНродродро╛роХродрпН родрпЖро░ро┐ропро╡ро┐ро▓рпНро▓рпИ. родрпКро▓рпИроХрпНроХро╛роЯрпНроЪро┐ропро┐ро▓рпН рокроЩрпНроХрпБроЪрпНроЪроирпНродрпИ роиро┐ро▓ро╡ро░родрпНродрпИ роЙройрпНройро┐рокрпНрокро╛роХ роХро╡ройро┐родрпНродрпБроХрпН роХрпКрогрпНроЯро┐ро░рпБроирпНродро╛ройрпН.

   роЖропро╛роЪродрпНродрпБроЯройрпН роородрпБ роЕроорпНрооро╛ро╡рпИродрпН родрпЗроЯро┐роЪрпН роЪрпЖройрпНро▒ро╛ро│рпН. ро╡ро┐родрпНропро╛ родройрпН ро▓рпЗрокрпНроЯро╛рокрпНрокро┐ро▓рпН роорпВро┤рпНроХро┐ропро┐ро░рпБроирпНродро╛ро│рпН. роЗрокрпНрокрпЛродрпБ роЕро┤рпИродрпНродро╛ро▓рпН роиро┐роЪрпНроЪропроорпН роХрпЛрокрокрпНрокроЯрпБро╡ро╛ро│рпН. роородрпБ родро┐ро░рпБроорпНрокро┐ роЪрпЖройрпНро▒рпБ родроирпНродрпИропро┐ройрпН роЕро░рпБроХро┐ро▓рпН роЕрооро░рпНроирпНродрпБ роХрпКрогрпНроЯро╛ро│рпН. роиро▓рпНро▓ ро╡рпЗро│рпИ, роЪрпАроХрпНроХро┐ро░роорпЗ ро╡ро┐ро│роорпНрокро░ роЗроЯрпИро╡рпЗро│рпИ ро╡роирпНродродрпБ.

   ро░ро┐роорпЛроЯрпНроЯрпИ роОроЯрпБродрпНродрпБ роЪрпЗройро▓рпИ рооро╛ро▒рпНро▒ роорпБро▒рпНрокроЯрпНроЯ роЪроЩрпНроХро░рпИ роЕро╡роЪро░рооро╛роХ роЕро┤рпИродрпНродро╛ро│рпН роородрпБ.

   "роЕрокрпНрокро╛"

   роЕрокрпНрокрпЛродрпБродро╛ройрпН роороХро│рпИ роХро╡ройро┐родрпНродро╛ройрпН роЪроЩрпНроХро░рпН.

   "роОройрпНройроЯро╛, роЪрпБроорпНрооро╛ роЗроЩрпНроХрпЗ ро╡роирпНродрпБ  роЙроЯрпНроХро╛ро░рпНроирпНродро┐ро░рпБроХрпНроХрпЗ?  ро╣рпЛроорпН роТро░рпНроХрпН роОро▓рпНро▓ро╛роорпН роорпБроЯро┐роЪрпНроЪро╛роЪрпНроЪро╛?"

   "роЕродрпЖро▓рпНро▓ро╛роорпН роИро╡ро┐ройро┐роЩрпНроХрпЗ  роорпБроЯро┐роЪрпНроЪро╛роЪрпНроЪрпБрокрпНрокро╛" роОройрпНро▒рпБ рокрпЖро░рпБроорпИропрпБроЯройрпН роЕро▒ро┐ро╡ро┐родрпНрод роородрпБ родрпКроЯро░рпНроирпНродро╛ро│рпН, "роЯро╛роЯро┐, роЕрокрпНрокро╡рпЗ роОропрпНроЯрпН роТ роХрпНро│ро╛роХрпН роЖропро┐роЯрпБроЪрпНроЪрпЗ? роХро░рпЖрогрпНроЯрпН роЗройрпНройрпБроорпН рокрпЛроХро▓ро┐ропрпЗ? роПроорпНрокро╛?"

    "роЙройроХрпНроХрпБродрпН родрпЖро░ро┐ропро╛родро╛ роородрпБ, роЗройро┐роорпЗро▓рпН ро░ро╛родрпНродро┐ро░ро┐ роХро░рпЖрогрпНроЯрпН рокрпЛроХро╛родрпБ. рокроХро▓рпНро▓ роороЯрпНроЯрпБроорпНродро╛ройрпН роХро░рогрпНроЯрпН роХроЯрпН."

   "роОройрпНройродрпБ??" роЕродро┐ро░рпНроирпНродрпБ ро╡ро┐ро┤ро┐родрпНродро╛ро│рпН роородрпБ.

...

   роХроЯроирпНрод рокродрпНродрпБ роиро╛роЯрпНроХро│ро╛роХ роЕроирпНрод ро╡роЯрпНроЯро╛ро░родрпНродро┐ро▓рпН родро┐ройроорпН роХро╛ро▓рпИ роОроЯрпНроЯро┐ро▓ро┐ро░рпБроирпНродрпБ рокродрпНродрпБ роорогро┐ ро╡ро░рпИропрпБроорпН, роЗро░ро╡рпБ роОроЯрпНроЯро┐ро▓ро┐ро░рпБроирпНродрпБ рокродрпНродрпБ роорогро┐ ро╡ро░рпИропрпБроорпН рооро┐ройрпНро╡рпЖроЯрпНроЯрпБ роЕрооро▓ро┐ро▓рпН роЗро░рпБроирпНродродрпБ.

   роЕроЩрпНроХрпБро│рпНро│ роЯро┐ро░ро╛ройрпНро╕рпНрокро╛ро░рпНрооро░рпН роТройрпНро▒ро┐ро▓рпН роПродрпЛ рокрпЖро░ро┐роп роХрпЛро│ро╛ро▒рпБ роПро▒рпНрокроЯрпНроЯрпБро│рпНро│родро╛ро▓рпН рооро┐ройрпНроЪро╛ро░рокрпН роЪрпЖро▓ро╡рпИроХрпН роХрпБро▒рпИрокрпНрокродро▒рпНроХро╛роХ роЗроирпНрод роироЯро╡роЯро┐роХрпНроХрпИ роОройрпНро▒ро╛ро░рпНроХро│рпН.

    роорпБродро▓рпН роиро╛ро│рпН рооро┐ройрпНроЪро╛ро░роорпН рокрпЛройродрпБроорпН роОро▓рпНро▓рпЛро░рпБроорпН родроЯрпБрооро╛ро▒ро┐родрпНродро╛ройрпН рокрпЛройро╛ро░рпНроХро│рпН.

   роОро▓рпНро▓ро╛ ро╡рпЗро▓рпИроХро│рпБроорпН рокро╛родро┐ропро┐ро▓рпН роиро┐ро▒рпНроХ, роОрокрпНрокроЯро┐ропрпЛ роорпЖро┤рпБроХрпБро╡ро░рпНродрпНродро┐ропрпИродрпН родрпЗроЯро┐ роОроЯрпБродрпНродро╛ро▓рпН роЕродро┐ро▓рпН родро┐ро░ро┐ роЗро▓рпНро▓рпИ. роЯро╛ро░рпНроЪрпНроЪро┐ро▓рпН  рокрпЗроЯрпНроЯро░ро┐ ро╡рпАроХрпН. роорпБрогрпБроХрпН  роорпБрогрпБроХрпНроХрпЖройрпНро▒родрпБ.  роХроЯрпИроЪро┐ропро┐ро▓рпН роЪрпЖро▓рпНроГрокрпЛройрпН рооро▒рпНро▒рпБроорпН роХрпБродрпНродрпБро╡ро┐ро│роХрпНроХрпИ ро╡рпИродрпНродрпБ роЪрооро╛ро│ро┐родрпНродро╛ро░рпНроХро│рпН.

  рооро▒рпБроиро╛ро│рпН роЪрпБродро╛ро░ро┐родрпНродрпБ ро╡ро┐роЯрпНроЯро╛ро░рпНроХро│рпН. роОрооро░рпНроЬрпЖройрпНроЪро┐ ро▓рпЗроорпНрокрпИ роЪро░ро┐ роЪрпЖропрпНродрпБ . ро╡рпИродрпНродро╛ро░рпНроХро│рпН. роОро▓рпНро▓ро╛ ро╡рпЗро▓рпИроХро│рпИропрпБроорпН роЪро▒рпНро▒рпБ роорпБройрпНройродро╛роХро╡рпЗ роорпБроЯро┐родрпНродрпБроХрпН роХрпКрогрпНроЯрпБ роЙроЯрпНроХро╛ро░рпНроирпНродро╛ро░рпНроХро│рпН. роородрпБ родройрпН ро╡рпАроЯрпНроЯрпБрокрпН рокро╛роЯроЩрпНроХро│рпИ роЪрпЖропрпНродрпБ роорпБроЯро┐родрпНродродрпЛроЯрпБ роЕро▓рпНро▓ро╛рооро▓рпН, роЗро░ро╡рпБ роЙрогро╡рпИропрпБроорпН роЪро╛рокрпНрокро┐роЯрпНроЯрпБ роорпБроЯро┐родрпНродрпБро╡ро┐роЯрпНроЯро╛ро│рпН.

   роОродрпБро╡рпБроорпН роЪрпЖропрпНропро╛рооро▓рпН роЗро░рогрпНроЯрпБ роорогро┐ роирпЗро░родрпНродрпИ роОрокрпНрокроЯро┐ роХроЯродрпНродрпБро╡родрпБ? роЪроЩрпНроХро░рпБроорпН ро╡ро┐родрпНропро╛ро╡рпБроорпН родроЩрпНроХро│рпН роЖроГрокрпАро╕ро┐ро▓рпН роироЯроирпНродро╡ро▒рпНро▒рпИ роЪрпКро▓рпНро▓,  роородрпБро╡рпБроорпН родройрпН ро╕рпНроХрпВро▓рпН роХродрпИроХро│рпИ роОроЯрпБродрпНродрпБ ро╡ро┐роЯрпНроЯро╛ро│рпН.

   роЕроЯрпБродрпНродрпБ ро╡роирпНрод роиро╛роЯрпНроХро│ро┐ро▓рпН ро╡рпЖро▒рпБроорпН рокрпЗроЪрпНроЪрпЛроЯрпБ роиро┐ро▓рпНро▓ро╛рооро▓рпН, ро╡рпЗро░рпНроЯрпНро╕рпН рокро┐ро▓рпНроЯро┐роЩрпН, рокро╛роЯрпНроЯрпБроХрпНроХрпБрокрпН рокро╛роЯрпНроЯрпБ роОройрпНро▒рпБ ро╡ро┐ро│рпИропро╛роЯро┐ роороХро┐ро┤рпНроЪрпНроЪро┐ропро╛роХ роирпЗро░родрпНродрпИроХрпН роХроЯродрпНродро┐ройро╛ро░рпНроХро│рпН.

   роЗройрпНро▒рпБ рокрпЖро▒рпНро▒рпЛро░ро┐роЯроорпН роХрпЗроЯрпНрокродро▒рпНроХро╛роХ роРроирпНродрпБ ро╡ро┐роЯрпБроХродрпИроХро│рпИ роирогрпНрокро░рпНроХро│ро┐роЯрооро┐ро░рпБроирпНродрпБ роЪрпЗроХро░ро┐родрпНродрпБ ро╡роирпНродрпБ, роЙро▒рпНроЪро╛роХрооро╛роХроХрпН роХро╛родрпНродро┐ро░рпБроирпНродро╛ро│рпН роородрпБрооро┐родро╛.

   роЖройро╛ро▓рпН роЗроирпНрод роХро░рпЖрогрпНроЯрпНтАж

тАж

   роЪроЩрпНроХро░рпН роЪрпКро▓рпНро▓ро┐роХрпН роХрпКрогрпНроЯро┐ро░рпБроирпНродро╛ройрпН, "роородрпБроХрпБроЯрпНроЯро┐, роЙройроХрпНроХрпБ роороХро┐ро┤рпНроЪрпНроЪро┐ родро╛ройрпЗ! роЗройро┐ роЕро░рпИропро┐ро░рпБроЯрпНроЯро┐ро▓рпН роЕро▓рпИроп  ро╡рпЗрогрпНроЯро╛роорпН. роЕро╡роЪро░ роЕро╡роЪро░рооро╛роХ роЪро╛рокрпНрокро┐роЯ ро╡рпЗрогрпНроЯро╛роорпН. роХрпКроЪрпБ рокрпВроЪрпНроЪро┐ роОродрпБро╡рпБроорпН ро╡ро░рпБроорпЗ, ро╡ро┐ропро░рпНроХрпНроХрпБроорпЗ роОройрпНро▒рпЖро▓рпНро▓ро╛роорпН роХро╡ро▓рпИрокрпНрокроЯ ро╡рпЗрогрпНроЯро╛роорпН. роирпА роЬро╛ро▓ро┐ропро╛роХ рокрпЖропро┐рогрпНроЯро┐роЩрпН рокрогрпНрогро▓ро╛роорпН. рокро┐ро│ро╛роХрпНро╕рпН, рокроЪро┐ро▓рпНро╕рпН, ро╡рпАроЯро┐ропрпЛ роХрпЗроорпНро╕рпН роОродрпБро╡рпЗрогро╛ ро╡ро┐ро│рпИропро╛роЯро▓ро╛роорпН. роЙройрпН рокрпБродрпБ роХрпБроЯрпНроЯро┐ роЯрпАро╡ро┐ропро┐ро▓рпН роЙройроХрпНроХрпБ рокро┐роЯро┐родрпНрод роХро╛ро░рпНроЯрпНроЯрпВройрпН рокро╛ро░рпНроХрпНроХтАж"

   роЙро▒рпНроЪро╛роХрооро╛роХ роЕроЯрпБроХрпНроХро┐роХрпН роХрпКрогрпНроЯрпЗ рокрпЛройро╡ройрпН, роХрпБро┤роирпНродрпИ ро╡ро┐роХрпНроХро┐ ро╡ро┐роХрпНроХро┐ роЕро┤рпБродро╡ро╛ро▒рпБ, родро▓рпИропрпИ ро╡рпЗроХрооро╛роХ роЗроЯро╡ро▓рооро╛роХ роЕроЪрпИрокрпНрокродрпИрокрпН рокро╛ро░рпНродрпНродрпБ родро┐роЯрпБроХрпНроХро┐роЯрпНроЯро╛ройрпН.

   "роОройрпНройроЯро╛?"

   роХроЯрпНроЯрпБрокрпН рокроЯрпБродрпНрод роорпБроЯро┐ропро╛род роЕро┤рпБроХрпИропро┐ройрпВроЯрпЗ роородрпБ роХрпВро▒ро┐ройро╛ро│рпН, "роЖройро╛ роХро░рпЖрогрпНроЯрпН рокрпЛройро╛ роороЯрпНроЯрпБроорпН родро╛ройрпЗ роЕроорпНрооро╛ро╡рпБроорпН роЕрокрпНрокро╛ро╡рпБроорпН роОройрпНроХрпВроЯ рокрпЗроЪрпБро╡рпАроЩрпНроХ."

  ...

рокро┐рокрпНро░ро╡ро░ро┐ 12-18, 2010  рокро╛роХрпНропро╛ роЗродро┤ро┐ро▓рпН рокро┐ро░роЪрпБро░рооро╛ройродрпБ.
** DONE роПройрпН рооро╛ро▒ро┐ройро╛ропрпН роЕрогрпНрогро┐? :роЪро┐ро▒рпБроХродрпИ:
CLOSED: [2020-09-20 Sun 23:48]
:PROPERTIES:
:EXPORT_FILE_NAME: yen-maarinai-anni
:END:
I

   'роОрокрпНрокроЯро┐ роЗро░рпБроирпНрод ро░рооро╛ роЕрогрпНрогро┐,' роЕройрпНро▒рпБ роирпВро▒ро╛ро╡родрпБ родроЯро╡рпИропро╛роХ роиро┐ройрпИродрпНродрпБрокрпН рокрпЖро░рпБроорпВроЪрпНроЪрпБ ро╡ро┐роЯрпНроЯро╛ро│рпН рооро╛ро▓родро┐.

   роиро╛ройрпНроХрпБ рооро╛родроЩрпНроХро│рпБроХрпНроХрпБ роорпБройрпН, роТро░рпБроиро╛ро│рпН ро░рооро╛ роЖроГрокрпАро╕ро┐ро▓ро┐ро░рпБроирпНродрпБ родройрпН ро╕рпНроХрпВроЯрпНроЯро┐ропро┐ро▓рпН ро╡рпАроЯрпНроЯрпБроХрпНроХрпБ ро╡роирпНродрпБ роХрпКрогрпНроЯро┐ро░рпБроХрпНроХрпБроорпНрокрпЛродрпБ, роТро░рпБ роЪро┐ро▒рпБ ро╡ро┐рокродрпНродрпБ. роХрпАро┤рпЗ ро╡ро┐ро┤рпБроирпНродродро┐ро▓рпН ро░рооро╛ро╡рпБроХрпНроХрпБ роЗроЯродрпБ роХро╛ро▓рпН роорпБроЯрпНроЯро┐ропро┐ро▓рпН роОро▓рпБроорпНрокрпБ роорпБро▒ро┐ро╡рпБ роПро▒рпНрокроЯрпНроЯрпБ ро╡ро┐роЯрпНроЯродрпБ. роЙроЯройроЯро┐ропро╛роХ роХро╡ройро┐родрпНродрпБ роЖрокрпНро░рпЗро╖ройрпБроорпН роЪрпЖропрпНродрпБ ро╡ро┐роЯрпНроЯро╛ро░рпНроХро│рпН.

    ро╡рпАроЯрпНроЯрпБроХрпНроХрпБ ро╡ро░ро▓ро╛роорпН роОройрпНро▒ро┐ро░рпБроХрпНроХрпБроорпН рокрпЛродрпБ,  роОрокрпНрокроЯро┐ропрпЛ роЗройрпНроГрокрпЖроХрпНтАМро╖ройрпН роПро▒рпНрокроЯрпНроЯрпБ  роЪрпАро░ро┐ропро╕рпН роЖроХро┐ ро╡ро┐роЯро╡рпБроорпН, роЕродро▒рпНроХрпБ роХрпКроЮрпНроЪроорпН роиро┐ро▒рпИропро╡рпЗ роиро╛роЯрпНроХро│рпН роЪро┐роХро┐роЪрпНроЪрпИ родрпЗро╡рпИрокрпНрокроЯрпНроЯродрпБ.

   роОро▓рпНро▓ро╛роорпН роиройрпНро▒ро╛роХ роХрпБрогрооро╛роХро┐, роЗрокрпНрокрпЛродрпБ ро╡рпАроЯрпНроЯрпБроХрпНроХрпБ ро╡роирпНродрпБ роЗро░рпБрокродрпБ роиро╛роЯрпНроХро│ро╛роХро┐ройрпНро▒рой.

тАж

   рооро╛ро▓родро┐ ропрпВ.роОро╕рпН.ро╕ро┐ро▓рпН роЪроорпАрокродрпНродро┐ро▓рпНродро╛ройрпН роОроорпН.роОро╕рпН. роХрпЛро░рпНро╕рпН роЪрпЗро░рпНроирпНродро┐ро░рпБроирпНродро╛ро│рпН. роЕродройро╛ро▓рпН роЙроЯройрпЗ ро▓рпАро╡рпБ роОроЯрпБроХрпНроХ роорпБроЯро┐ропро╡ро┐ро▓рпНро▓рпИ.

   роПро▒рпНроХройро╡рпЗ 'ро╣рпЛроорпН ро╕ро┐роХрпН'роХро╛роХ роЗро░рпБроирпНродро╡ро│рпН, роЕрогрпНрогро┐ропрпИрокрпН рокро╛ро░рпНроХрпНроХрпБроорпН родро╡ро┐рокрпНрокрпБроорпН роЪрпЗро░рпНроирпНродрпБ роХрпКро│рпНро│, роХро┐роЯрпИродрпНрод роорпБродро▓рпН роЪроирпНродро░рпНрокрпНрокродрпНродро┐ро▓рпН роХро┐ро│роорпНрокро┐ ро╡роирпНродрпБ ро╡ро┐роЯрпНроЯро╛ро│рпН. роТро░рпБ ро╡ро╛ро░ ро▓рпАро╡рпБродро╛ройрпН роОройрпНро▒ро╛ро▓рпБроорпН рокро░ро╡ро╛ропро┐ро▓рпНро▓рпИ.

  родройрпНройрпИ роЕро┤рпИродрпНродрпБроЪрпН роЪрпЖро▓рпНро▓ ро╡ро┐рооро╛рой роиро┐ро▓рпИропроорпН ро╡роирпНродро┐ро░рпБроирпНрод рооро╛родро╡ройрпИрокрпН рокро╛ро░рпНродрпНродродрпБроорпЗ роХрпЗроЯрпНроЯро╛ро│рпН, "роЕрогрпНрогро┐ роОрокрпНрокроЯро┐ роЗро░рпБроХрпНроХро╛роЩрпНроХ роЕрогрпНрогро╛?"

   "роОройрпНройройрпНройрпБ роЪрпКро▓рпНро▓ рооро╛ро▓рпБ. роЗрокрпНрокрпЛродрпЖро▓рпНро▓ро╛роорпН ро░рооро╛ роЪро░ро┐ропро╛роХ роЪро╛рокрпНрокро┐роЯро▒родрпБроХрпВроЯ роЗро▓рпНро▓рпИ. роХрпВроЯро╡рпЗ роЙроЯрпНроХро╛ро░рпНроирпНродрпБ роХроЯрпНроЯро╛ропрокрпНрокроЯрпБродрпНродро┐родрпНродро╛ройрпН роТро╡рпНро╡рпКро░рпБ ро╡рпЗро│рпИропрпБроорпН рооро╛родрпНродро┐ро░рпИ роХрпКроЯрпБроХрпНроХ ро╡рпЗрогрпНроЯро┐ропро┐ро░рпБроХрпНроХрпБ. роГрокро┐ро╕ро┐ропрпЛродрпЖро░рокро┐ро╕рпНроЯрпН ро╡роирпНродро╛ роХрпКроЮрпНроЪроорпН роХрпВроЯ роТродрпНродрпБро┤рпИроХрпНроХ рооро╛роЯрпНроЯрпЗройрпНроХро┐ро▒ро╛. роОройрпНрой роЪрпКройрпНройро╛ро▓рпБроорпН роорпБро▒рпИроЪрпНроЪрпБроХрпНроХро┐роЯрпНроЯрпБ роЙроЯрпНроХро╛ро░рпНроирпНродро┐ро░рпБроХрпНроХро╛."

   тАЬроОройрпНройрогрпНрогро╛ роЪрпКро▓рпНро▒рпЗ?тАЭ

   тАЬроЖрооро╛роорпН. роОрокрпНрокрокрпН рокро╛ро░рпБ, роЪро┐роЯрпБроЪро┐роЯрпБрокрпНрокрпБроорпН роТро░рпБро╡ро┐род роЪрпЛроХрокрпН рокро╛ро░рпНро╡рпИропрпБроорпНтАжтАЭ

  "роЕрогрпНрогро┐ропро╛..? роЪрпАроЪрпНроЪрпА, роЕрокрпНрокроЯро┐ропрпЖро▓рпНро▓ро╛роорпН роЗро░рпБроХрпНроХро╛родрпБ" роОройрпНро▒ро╛ро│рпН рооро╛ро▓родро┐.

   "роирпЗро▒рпНро▒рпБродрпН родро╛ройрпН роЯро╛роХрпНроЯро░рпИрокрпН рокрпЛропрпНрокрпН рокро╛ро░рпНродрпНродрпБроЯрпНроЯрпБ ро╡роирпНродрпЗройрпН. родро▓рпИроХрпНроХрпБ ро╡рпЗрогро╛ роЗройрпНройрпКро░рпБ ро╕рпНроХрпЗройрпН роОроЯрпБродрпНродрпБрокрпН рокро╛ро░рпНроХрпНроХро▓ро╛роорпН роОройрпНроХро┐ро▒ро╛ро░рпН."

   "роПройрпН? роорпБродро▓рпНро▓ропрпЗ роОроЯрпБроХрпНроХро▓рпИропро╛?"

   "роОроЯрпБродрпНродрпЛроорпН. роОро▓рпНро▓ро╛роорпН роиро╛ро░рпНрооро▓ро╛роХродрпНродро╛ройрпН роЗро░рпБроирпНродродрпБ. роЗрокрпНрокрпЛ роОродро▒рпНроХрпБроорпН роорпАрогрпНроЯрпБроорпН роОроЯрпБроХрпНроХро▓ро╛роорпН роОройрпНроХро┐ро▒ро╛ро░рпН." рооро╛родро╡ройро┐ройрпН роХрпБро░ро▓ро┐ро▓рпН ро▓рпЗроЪро╛рой роироЯрпБроХрпНроХроорпН.

   "роЗрокрпНрокро╡рпБроорпН роОро▓рпНро▓ро╛роорпН роиро╛ро░рпНрооро▓ро╛роХродрпНродро╛ройрпН роЗро░рпБроХрпНроХрпБроорпН роЕрогрпНрогро╛.. рокрпЗроЪро╛рооро▓рпН роЕрогрпНрогро┐ роХрпКроЮрпНроЪ роиро╛ро│рпН роиро▓рпНро▓ ро░рпЖро╕рпНроЯрпН роОроЯрпБродрпНродро╛ро▓рпЗ рокрпЛродрпБроорпН."

   "роиро╛ройрпБроорпН роЕрокрпНрокроЯро┐родрпНродро╛ройрпН роиро┐ройрпИроХрпНроХро┐ро▒рпЗройрпН. роиро▓рпНро▓ ро░рпЖро╕рпНроЯрпН роХро┐роЯрпИроХрпНроХроЯрпНроЯрпБроорпНройрпБродро╛ройрпН роЕро╡ ро░рпВроорпН роХродро╡рпИроХрпНроХрпВроЯ роОрокрпНрокро╡рпБроорпН роЪро╛ро░рпНродрпНродро┐ропрпЗ ро╡роЪрпНроЪро┐ро░рпБроХрпНроХрпЗройрпН. роЕроорпНрооро╛ро╡рпИ ро╡ро┐роЯрпБ, роЪрпБрокро╛роХрпНроХрпБроЯрпНроЯро┐ роХрпВроЯ роЕро╡ро│рпИ родрпКроирпНродро░ро╡рпБ роЪрпЖропрпНро╡родрпЗ роЗро▓рпНро▓рпИ. роЖроГрокрпАро╕ро┐ро▓ро┐ро░рпБроирпНродрпБроорпН ропро╛ро░рпБроорпН родрпКроирпНродро░ро╡рпБ рокрогрпНрог ро╡рпЗрогрпНроЯро╛роорпНройрпБ роЪрпКро▓рпНро▓ро┐ропро┐ро░рпБроХрпНроХрпЗройрпНтАж рокро╛ро░рпНроХрпНроХро▓ро╛роорпН."

   роЕрогрпНрогройрпН родрпИро░ро┐ропрооро╛роХроХрпН роХро╛роЯрпНроЯро┐роХрпНроХрпКрогрпНроЯро╛ро▓рпБроорпН роЙро│рпНро│рпБроХрпНроХрпБро│рпН роХро▓роЩрпНроХро┐ропро┐ро░рпБрокрпНрокродрпБ рокрпБро░ро┐роирпНродродрпБ рооро╛ро▓родро┐роХрпНроХрпБ.

тАж

   рооро╛родро╡ройрпБроХрпНроХрпБроорпН ро░рооро╛ро╡рпБроХрпНроХрпБроорпН родро┐ро░рпБроорогроорпН роироЯроирпНродрпБ роОроЯрпНроЯрпБ ро╡ро░рпБроЯроЩрпНроХро│рпН роЖроХро┐ройрпНро▒рой. роЕрокрпНрокрпЛродрпБ рооро╛ро▓родро┐роХрпНроХрпБ ро╡ропродрпБ рокродро┐ройро╛ро▒рпБ.

   родро┐ро░рпБроорогродрпНродрпБроХрпНроХрпБ ро╡роирпНрод рокро▓ро░рпБроорпН, ро░рооро╛ ро╡рпЗро▓рпИроХрпНроХрпБ рокрпЛроХро┐ро▒ рокрпЖрогрпН роОройрпНро▒рпБ родрпЖро░ро┐роирпНродродрпБроорпН роЕроорпНрооро╛ро╡ро┐роЯроорпН, "роЗройро┐ роирпА роЪроорпНрокро│роорпН роЗро▓рпНро▓ро╛род ро╡рпЗро▓рпИроХрпНроХро╛ро░ро┐родро╛ройрпН, рокрпЛ" роОройрпНро▒рпБ роОроЪрпНроЪро░ро┐родрпНродройро░рпН.

   рооро╛ро▓родро┐ропро┐роЯроорпБроорпН, "роЗройро┐ роирпА рокро┤рпИроп 'рокро╛роЪрооро▓ро░рпН' роЕрогрпНрогройрпИ роОродро┐ро░рпНрокро╛ро░рпНроХрпНроХроХрпН роХрпВроЯро╛родрпБ" роОройрпНро▒ройро░рпН.

   роЕродройро╛ро▓рпЗропрпЗ роЕроорпНрооро╛ро╡рпБроорпН роЪро░ро┐, рооро╛ро▓родро┐ропрпБроорпН роЪро░ро┐, рокрпБродрпБрокрпН рокрпЖрогрпНрогро┐роЯроорпН роЪро▒рпНро▒рпБ роХро╡ройродрпНродрпБроЯройрпН роироЯроирпНродрпБ роХрпКрогрпНроЯройро░рпН.

   роЖройро╛ро▓рпН роОро▓рпНро▓ро╛роорпН роЪро┐ро▓ роиро╛роЯрпНроХро│рпБроХрпНроХрпБродрпНродро╛ройрпН. ро░рооро╛ро╡ро┐ройрпН рооро▓ро░рпНроирпНрод роорпБроХроорпБроорпН роХро▓роХро▓рокрпНрокро╛рой роЪрпБрокро╛ро╡роорпБроорпН роЕроирпНрод ро╡рпАроЯрпНроЯрпИропрпЗ рооро╛ро▒рпНро▒ро┐ ро╡ро┐роЯрпНроЯродрпБ.

   рокрпЗроЪрпНроЪрпИрокрпН рокрпЛро▓ро╡рпЗ роОро▓рпНро▓ро╛ ро╡рпЗро▓рпИроХро│ро┐ро▓рпБроорпН ро░рооро╛ро╡рпБроХрпНроХрпБ роЪрпБро▒рпБроЪрпБро▒рпБрокрпНрокрпБ роЕродро┐роХроорпН родро╛ройрпН.

   рокрпЛрой ро╡ро░рпБроЯроорпН рооро╛ро▓родро┐ родро┐ро░рпБроорогрооро╛роХро┐ ропрпВ.роОро╕рпН. роХро┐ро│роорпНрокрпБроорпНрокрпЛродрпБ роЕроорпНрооро╛ роЪрпКройрпНройро╛ро│рпН, "ро░рооро╛ рооро╛родро┐ро░ро┐ропрпЗ роиро▓рпНро▓ рокрпЖрогрпНрогро╛роХ роироЯроирпНродрпБроХрпНроХроорпНрооро╛." роЗро╡ро│рпБроХрпНроХрпБроорпН рооройродро┐ро▓рпН роЕродрпЗ роОрогрпНрогроорпН родро╛ройрпН.

   роЕрокрпНрокроЯро┐рокрпНрокроЯрпНроЯ ро░рооро╛ роЗрокрпНрокрпЛродрпБ роЗрокрпНрокроЯро┐ роУропрпНроирпНродро┐ро░рпБрокрпНрокродрпБродро╛ройрпН ропро╛ро░рпБроХрпНроХрпБроорпН родро╛роЩрпНроХро╡ро┐ро▓рпНро▓рпИ.

тАж

   ро╡рпАроЯрпНроЯрпИ роЕроЯрпИроирпНродродрпБроорпН, роЕроорпНрооро╛ро╡ро┐роЯроорпН роТро░рпБ роиро┐рооро┐роЯроорпН рокрпЗроЪро┐ро╡ро┐роЯрпНроЯрпБ рооро╛ро▓родро┐ роирпЗро░ро╛роХ роЕрогрпНрогро┐ропрпИрокрпН рокро╛ро░рпНроХрпНроХ роУроЯро┐ройро╛ро│рпН.

   "роЕрогрпНрогрпА, роОрокрпНрокроЯро┐ роЗро░рпБроХрпНроХрпЗ?"

   "...."

   "роЙроЯроорпНрокрпБ родрпЗро╡ро▓рпИропро╛?"

   тАЬ...тАЭ

   "роХро╛ро▓рпНро▓ ро╡ро▓ро┐ роЗро░рпБроХрпНроХро╛?"

   роОро▓рпНро▓ро╛ро╡ро▒рпНро▒рпБроХрпНроХрпБроорпН роТро░рпБ роЪро┐ро▒рпБ родро▓рпИропро╛роЯрпНроЯро▓рпН родро╛ройрпН рокродро┐ро▓рпН.

   роЕро░рпБроХро┐ро▓рпН ро╕рпНроЯрпВро▓ро┐ро▓рпН роЗро░рогрпНроЯрпБ рооро╛родрпНродро┐ро░рпИроХро│рпН роЗро░рпБроирпНродрой.

   "рооро╛родрпНродро┐ро░рпИ рокрпЛроЯрпНроЯрпБроХрпНроХро▓рпИропро╛ роЕрогрпНрогро┐? родрогрпНрогрпАро░рпН роХрпКрогрпНроЯрпБ ро╡ро░ро╡ро╛?"

   'ро╡рпЗрогрпНроЯро╛роорпН' роОройрпНро▒ роЪро┐ро▒рпБ родро▓рпИропроЪрпИро╡рпБроЯройрпН роХроЯрпНроЯро┐ро▓ро┐ро▓рпН родро┐ро░рпБроорпНрокро┐рокрпН рокроЯрпБродрпНродрпБроХрпН роХрогрпНроХро│рпИ роорпВроЯро┐роХрпНроХрпКрогрпНроЯро╛ро│рпН ро░рооро╛.

   роорпЗро▒рпНроХрпКрогрпНроЯрпБ роЪрпЖропрпНро╡родро▒ро┐ропро╛рооро▓рпН 'роЕрогрпНрогро┐роХрпНроХрпБ роОройрпНрой родро╛ройрпН роЖроЪрпНроЪрпБ' роОройрпНро▒рпБ роХро╡ро▓рпИропрпЛроЯрпБ ро╡рпЖро│ро┐ропрпЗ ро╡роирпНродро╛ро│рпН рооро╛ро▓родро┐.

тАж.


                                          II

    роЪрпБрокро╛ рокро│рпНро│ро┐роХрпНроХрпБроЪрпН роЪрпЖро▓рпНро▓родрпН  родропро╛ро░ро╛роХро┐роХрпН роХрпКрогрпНроЯро┐ро░рпБроирпНродро╛ро│рпН. ро╣ро╛ро▓рпЗ роЗро░рогрпНроЯрпБ рокроЯрпНроЯрпБроХрпН роХрпКрогрпНроЯро┐ро░рпБроирпНродродрпБ.

   рокро╛роЯрпНроЯро┐ роЪрпЖропрпНродро┐ро░рпБроирпНрод роирпВроЯрпБро▓рпНро╕рпН, родрогрпНрогрпАро░рпН ро╡ро▒рпНро▒ро┐ роХрпЖроЯрпНроЯро┐ропро╛роХ роЗро░рпБроирпНродродро╛ро▓рпН, роЪро╛рокрпНрокро┐роЯ роорпБроЯро┐ропро╛рооро▓рпН родро┐рогро▒ро┐ роЕрокрпНрокроЯро┐ропрпЗ ро╡рпИродрпНродрпБ ро╡ро┐роЯрпНроЯро╛ро│рпН.

   "рокрпЛродрпБроорпН рокро╛роЯрпНроЯро┐."

   "роХрпНро░рпЗропро╛ройрпН рокро╛роХрпНро╕рпН роОроЩрпНроХрпЗрокрпНрокро╛?"

   рооро╛родро╡ройрпН ропро╛ро░ро┐роЯроорпЛ роГрокрпЛройро┐ро▓рпН рокро┐ро╕ро┐ропро╛роХ роЗро░рпБроирпНродро╛ройрпН.

   "ро╕ро╛роХрпНро╕рпН ро░рпЖрогрпНроЯрпБроорпН ро╡рпЗро▒ ро╡рпЗро▒ропро╛ роЗро░рпБроХрпНроХрпЗ. рооро┐ро╕рпН родро┐роЯрпНроЯрпБро╡ро╛роЩрпНроХ"

   "рокрпЖро▓рпНроЯрпН рокрпЛроЯ ро╡ро░ро▓рпИ. роЯрпИроЯрпНроЯро╛ропро┐ро░рпБроХрпНроХрпБ."

   роЪрпБрокро╛ родро╛ройрпБроорпН родро╡ро┐родрпНродрпБ, рооро▒рпНро▒ро╡ро░рпНроХро│рпИропрпБроорпН роЕро▓рпИроХрпНроХро┤ро┐родрпНродрпБроХрпН роХрпКрогрпНроЯро┐ро░рпБроирпНродро╛ро│рпН.

   рооро╛ро▓родро┐ропрпИроХрпН роХрогрпНроЯродрпБроорпН роЪрпАрокрпНрокрпБроЯройрпН роУроЯро┐ ро╡роирпНродро╛ро│рпН.

   "роЗройрпНройро┐роХрпНроХрпБ роирпАроЩрпНроХ рокро┐ройрпНройро┐ ро╡ро┐роЯрпБроЩрпНроХ роЕродрпНродрпИ. рокро╛роЯрпНроЯро┐ роиро┐ро▒рпИроп роОрогрпНрогрпЖропрпН ро╡роЪрпНроЪрпБроЯрпБро╡ро╛. роЕрокрпНрокро╛ ро╡ро╛ро░ро┐ройро╛ роЪро┐роХрпНроХро┐ роЪро┐роХрпНроХро┐ ро╡ро▓ро┐роХрпНроХрпБроорпН. "

   роТро░рпБро╡ро╛ро▒рпБ ро░рпЖроЯро┐ропро╛ройродрпБроорпН роирпЗро░ро╛роХ ро░рооро╛ро╡ро┐роЯроорпН роЪрпЖройрпНро▒рпБ, "роЕроорпНрооро╛, роиро╛ройрпН ро╕рпНроХрпВро▓рпБроХрпНроХрпБроХрпН роХро┐ро│роорпНрокро┐ропро╛роЪрпНроЪрпБтАж рокрпИ" роОройрпНро▒ро╛ро│рпН.

   родро╛ропро┐роЯрооро┐ро░рпБроирпНродрпБ рокродро┐ро▓рпН ро╡ро░ро╛родродрпБроорпН, "роЕроорпНроорпНрооро╛" роОройрпНро▒рпБ роЕро┤рпИродрпНродро╛ро│рпН роЕродроЯрпНроЯро▓ро╛роХ.

   "ро╖рпН.. роЪрпБрокро╛" роОройрпНро▒рпБ рооро╛родро╡ройрпН роЕро╡роЪро░рооро╛роХ роОроЪрпНроЪро░ро┐роХрпНроХро╡рпБроорпН, роТройрпНро▒рпБроорпН роЪрпКро▓рпНро▓ро╛рооро▓рпН роХро┐ро│роорпНрокро┐ ро╡ро┐роЯрпНроЯро╛ро│рпН.

тАж

   рооро╛родро╡ройрпБроорпН роЪрпБрокро╛ро╡рпБроорпН роХро┐ро│роорпНрокро┐рокрпН рокрпЛройродрпБроорпН роЕродро▒рпНроХрпБ роорпЗро▓рпН роЕроорпНрооро╛ро╡ро╛ро▓рпБроорпН роорпБроЯро┐ропро╡ро┐ро▓рпНро▓рпИ. роХрпКроЮрпНроЪ роирпЗро░роорпН рооро╛ро▓родро┐ропрпИропрпБроорпН ро░рооро╛ро╡рпИропрпБроорпН рокро▒рпНро▒ро┐ рокрпЗроЪро┐роХрпНроХрпКрогрпНроЯро┐ро░рпБроирпНродро╡ро│рпН роЕрокрпНрокроЯро┐ропрпЗ роХрогрпНрогропро░рпНроирпНродрпБ ро╡ро┐роЯрпНроЯро╛ро│рпН.

   рооро╛ро▓родро┐ роорпАрогрпНроЯрпБроорпН роЗро░рогрпНроЯрпБ роорпВройрпНро▒рпБ роорпБро▒рпИ ро░рооро╛ро╡ро┐роЯроорпН роЪрпЖройрпНро▒рпБ рокрпЗроЪро┐рокрпН рокро╛ро░рпНродрпНродро╛ро│рпН. роЕро╡ро│ро╛ро▓рпН рокрпЖро░рпБроорпВроЪрпНроЪрпБ родро╛ройрпН ро╡ро┐роЯ роорпБроЯро┐роирпНродродрпБ.

   ропрпВ.роОро╕рпН.ро╕ро┐ро▓рпН родройро┐ропро╛роХ роЗро░рпБроХрпНроХрпБроорпН роХрогро╡ройро┐ройрпН роиро┐ройрпИро╡рпБ роЕроЯро┐роХрпНроХроЯро┐ ро╡роирпНродродрпБ.

   'рокро╛ро╡роорпН, роиро╛ройро┐ро▓рпНро▓ро╛рооро▓рпН родройро┐ропро╛роХ роОройрпНрой рокро╛роЯрпБ рокроЯрпБроХро┐ро▒ро╛ро░рпЛ' роОройрпНро▒рпБ роЪроЩрпНроХроЯрооро╛роХ роЗро░рпБроирпНродродрпБ.

   'роЕроЯрпБродрпНрод ро╡ро╛ро░роорпН роЗроирпНроирпЗро░роорпН рокрпЛропрпН ро╡ро┐роЯро▓ро╛роорпН' роОройрпНро▒рпБ родройрпНройрпИродрпНродро╛ройрпЗ родрпЗро▒рпНро▒ро┐роХрпН роХрпКрогрпНроЯро╛ро│рпН.

тАж

   роЕройрпНро▒ро┐ро░ро╡рпБ роЪрпБроирпНродро░ро┐роЯрооро┐ро░рпБроирпНродрпБ роГрокрпЛройрпН ро╡роирпНродродрпБроорпН роорпБродро▓ро┐ро▓рпН роЕродрпИродрпНродро╛ройрпН ро╡ро┐роЪро╛ро░ро┐родрпНродро╛ро│рпН.

   "родройро┐ропро╛роХ ро░рпКроорпНрокроХрпН роХро╖рпНроЯрооро╛роХ роЗро░рпБроХрпНроХро╛?"

   роТро░рпБ роирпАрогрпНроЯ рокрпБро▓роорпНрокро▓рпИродрпНродро╛ройрпН рокродро┐ро▓ро╛роХ роОродро┐ро░рпНрокро╛ро░рпНродрпНродро╛ро│рпН. роЖройро╛ро▓рпН,

   "роЕрокрпНрокроЯро┐ропрпКройрпНро▒рпБроорпН роЗро▓рпНро▓рпИ рооро╛ро▓рпБ. роР роорпЗройрпЗроЬрпНроЯрпН ро╡рпЖро▓рпН роЯрпБроЯрпЗ" роОройрпНро▒ро╛ройрпН роЪрпБроирпНродро░рпН.

   рооро╛ро▓родро┐роХрпНроХрпБ роЙро│рпНро│рпБроХрпНроХрпБро│рпН роПродрпЛ роТро░рпБ рокро▓рпНрокрпБ роГрокро┐ропрпВроЪро╛ройродрпБ рокрпЛро▓рпН родрпЛройрпНро▒ро┐ропродрпБ. роЗро╡рпНро╡ро│ро╡рпБ родро╛ройро╛?

   "роЖройро╛ рооро╛ро▓рпБ, роЕродро▒рпНроХро╛роХ роТро░рпЗропроЯро┐ропро╛роХ роирпА роЕроЩрпНроХрпЗропрпЗ роЯрпЗро░ро╛ рокрпЛроЯрпНроЯрпБроЯро╛родрпЗ. роР рооро┐ро╕рпН ропрпВ ро╡рпЖро░ро┐ роороЪрпН. роОрокрпНрокроЯро┐ропрпЛ роЗройрпНро▒рпБ роЪрооро╛ро│ро┐родрпНродрпБ ро╡ро┐роЯрпНроЯрпЗройрпН. родроЯрпНро╕рпН роЖро▓рпН. роирпА ро╡роирпНродро╛ро▓рпН родро╛ройрпН роЪро░ро┐ропро╛роХрпБроорпН."

   рооро╛ро▓родро┐роХрпНроХрпБро│рпН роГрокро┐ропрпВроЪро╛рой рокро▓рпНрокрпБ роЗрокрпНрокрпЛродрпБ рокро┐ро░роХро╛роЪрооро╛роХ роОро░ро┐роирпНродродрпБ. роЪро┐ро▒ро┐родрпБ роирпЗро░роорпН роХрогро╡ройрпБроЯройрпН рокрпЗроЪро┐ро╡ро┐роЯрпНроЯрпБ, ропрпЛроЪройрпИропрпБроЯройрпН роЕрогрпНрогройрпИ роиро╛роЯро┐роЪрпН роЪрпЖройрпНро▒ро╛ро│рпН.

   "роЕрогрпНрогро╛, роЗроирпНрод роТро░рпБ ро╡ро╛ро░роорпН роЙройрпН роЖрокрпАро╕рпБроХрпНроХрпБ ро▓рпАро╡рпБ рокрпЛроЯрпНроЯрпБ ро╡ро┐роЯрпЗройрпН."

   "ро╡рпЗрогрпНроЯро╛роорпНрооро╛. ро░рооро╛ роЖроХрпНро╕ро┐роЯрпЖройрпНроЯрпН роЪрооропродрпНродро┐ро▓ роЗро░рпБрокродрпБ роиро╛ро│рпН ро▓рпАро╡рпБ рокрпЛроЯрпНроЯро┐ро░рпБроирпНродрпЗройрпН. родро┐ро░рпБроорпНрок роЬро╛ропро┐ройрпН рокрогрпНрогрпБроорпНрокрпЛродрпБ рокрпЛродрпБроорпН рокрпЛродрпБроорпНройрпБ роЖроХро┐роЯрпБроЪрпНроЪрпБ. роЬро┐.роОроорпН. роХрпВроЯроЪрпН роЪрпКро▓рпНро╡ро╛ро░рпН, 'рооро╛родро╡ройрпН роЗро▓рпНро▓ро╛роЯрпНроЯро╛ роЯро┐рокро╛ро░рпНроЯрпНроорпЖрогрпНроЯрпЗ роЖроЯро┐рокрпН рокрпКропро┐роЯрпБродрпБ'ройрпНройрпБ."

   "роРропрпЛ, рокро╛ро╡роорпН роЕрогрпНрогро╛ роирпА"

   "роЗродрпБро▓ рокро░ро┐родро╛рокрокрпН рокроЯ роОройрпНройроорпНрооро╛ роЗро░рпБроХрпНроХрпБ? роЪрпКро▓рпНро▓рокрпНрокрпЛройро╛ро▓рпН роОройроХрпНроХрпБроорпН роТро░рпБро╡ро┐род родро┐ро░рпБрокрпНродро┐ родро╛ройрпН. роироороХрпНроХрпБройрпНройрпБ роТро░рпБ роорпБроХрпНроХро┐ропродрпНродрпБро╡роорпН ро╡рпЗрогрпБрооро┐ро▓рпНро▓ро┐ропро╛?" роОройрпНро▒ро╡ройрпН родрпКроЯро░рпНроирпНродро╛ройрпН, "роЪрпБроирпНродро░рпН роГрокрпЛройрпН рокрогрпНрогро┐ройро╛ро░ро╛ рооро╛ро▓родро┐? роирпА роЗро▓рпНро▓ро╛роо рокро╛ро╡роорпН родро┐рогрпНроЯро╛роЯро┐роХрпН роХрпКрогрпНроЯро┐ро░рпБрокрпНрокро╛ро░рпН."

   "роорпН.. роорпН" роОройрпНро▒ рооро╛ро▓родро┐ родро┐роЯрпАро░рпЖрой ро╡рпЖроЯро┐родрпНродро╛ро│рпН.

   "роПрогрпНроЯро╛, роироороХрпНроХрпКро░рпБ роиро┐ропро╛ропроорпН, роЕрогрпНрогро┐роХрпНроХрпКро░рпБ роиро┐ропро╛ропрооро╛?"

   "роОройрпНрой роЪрпКро▓рпНро▒рпЗ?"

   "роЙройрпНройрпИ роЙроЩрпНроХ роЬро┐.роОроорпН.роорпБроорпН, роОройрпНройрпИ роЪрпБроирпНродро░рпБроорпН рооро┐ро╕рпН рокрогрпНрогрпБродрпБ рокрпЛро▓,  роЕрогрпНрогро┐ропрпИ ропро╛ро░рпБроорпН рооро┐ро╕рпН рокрогрпНрогро╡рпЗропро┐ро▓рпНро▓ро┐ропро╛?"

   "роОройрпНрой роЙро│ро▒рпБроХро┐ро▒ро╛ропрпН? роиро╛ройрпН, роЕроорпНрооро╛, роЪрпБрокро╛ рокроЯрпБроХро┐ро▒ рокро╛роЯрпНроЯрпИ роирпАродро╛ройрпН рокро╛ро░рпНроХрпНроХро┐ро▒ро╛ропрпЗ. роЕро╡ро│рпН роЖроГрокрпАро╕ро┐ро▓ро┐ро░рпБроирпНродрпБроорпН родро┐ройроорпН роЗро░рогрпНроЯрпБ родроЯро╡рпИропро╛ро╡родрпБ роГрокрпЛройрпН рокрогрпНро▒ро╛роЩрпНроХ, роорпЗроЯроорпН роОрокрпНрокрпЛ ро╡ро░рпБро╡ро╛роЩрпНроХройрпНройрпБ."

   "роЗродрпЖро▓рпНро▓ро╛роорпН роЕрогрпНрогро┐роХрпНроХрпБродрпН родрпЖро░ро┐ропрпБрооро╛?"

   "роЗро▓рпНро▓рпИропро┐ро▓рпНро▓рпИ. родрпЖро░ро┐ропро╛родрпБ. рокро╛ро╡роорпН. ро╡ро░рпБродрпНродрокрпНрокроЯрпБро╡ро╛ро│рпН. роОроирпНрод рокро┐ро░роЪрпНроЪройрпИропрпБроорпН роЕро╡ро│рпИ роОроЯрпНроЯро╛рооро▓рпН ро░рпКроорпНрок роХро╡ройрооро╛родрпНродро╛ройрпН роЗро░рпБроХрпНроХрпЗройрпН. роОро▓рпНро▓ро╛роорпН роиройрпНро▒ро╛роХ роироЯрокрпНрокродро╛роХроЪрпН роЪрпКро▓рпНро▓ро┐ропро┐ро░рпБроХрпНроХрпЗройрпН. роЕро╡ро│рпН роЪрпЖро▓рпНроГрокрпЛройрпИроХрпН роХрпВроЯ роЖроГрокрпН рокрогрпНрогро┐родрпНродро╛ройрпН ро╡рпИродрпНродро┐ро░рпБроХрпНроХрпЗройрпН. роЕрокрпНрокроЯро┐ роЗро░рпБроирпНродрпБроорпНтАж"

   рооро╛ро▓родро┐ роЕро▓рпБродрпНродрпБроХрпН роХрпКрогрпНроЯро╛ро│рпН.

   "роЗроЩрпНроХрпБ родро╛ройрпН роЕрогрпНрогро╛ роирпА родрокрпНрокрпБ роЪрпЖропрпНродрпБроЯрпНроЯрпЗ. роЕрогрпНрогро┐ роОройрпНройро┐роХрпНроХрпБроорпЗ роЪрпЖро▓рпНроГрокро┐ро╖рпН роХро┐роЯрпИропро╛родрпБ. роирпАроЩрпНроХро│рпНро▓ро╛роорпН рокрогрпНро▒родрпБро▓, 'роиро╛ройрпН роЗройро┐ ропро╛ро░рпБроХрпНроХрпБроорпН роОродро▒рпНроХрпБроорпН родрпЗро╡рпИропро┐ро▓рпНро▓рпИ' роОройрпНроХро┐ро▒ роОрогрпНрогроорпН роЕрогрпНрогро┐роХрпНроХрпБ роПро▒рпНрокроЯрпНроЯро┐ро░рпБроХрпНроХрпБ. роиро▓рпНро▓родрпБ роЪрпЖропрпНро╡родро╛роХ роиро┐ройрпИродрпНродрпБ роЕро╡роЩрпНроХро│рпИ родройро┐роорпИро▓ роЪро┐ро▒рпИрокрпНрокроЯрпБродрпНродро┐роЯрпНроЯрпАроЩрпНроХ.."

   "роОройрпНройродрпБ?"

   "роЕро╡ро│рпБроХрпНроХрпБроорпН 'роиро╛ройрпН роЗро▓рпНро▓ро╛роЯрпНроЯро╛ роОро▓рпНро▓ро╛ро░рпБроорпН роХро╖рпНроЯрокрпНрокроЯрогрпБроорпН'ройрпНро▒ роОрогрпНрогроорпН роЗро▓рпНро▓рпИ. роЖройро╛ро▓рпН, 'роиро╛ройрпН роЗро▓рпНро▓ро╛роЯрпНроЯро╛ роОро▓рпНро▓ро╛роорпЗ роЗройрпНройрпБроорпН ро░рпКроорпНрок роиройрпНро▒ро╛роХ роироЯроХрпНроХро┐ро▒родрпБ' роОройрпНроХро┐ро▒ родрпЛро▒рпНро▒роорпН рооройродрпИ рокро╛родро┐роЪрпНроЪро┐ро░рпБроХрпНроХрпБ."

   рооро╛родро╡ройрпН роЕро░рогрпНроЯрпБ рокрпЛройро╛ройрпН, "роЗрокрпНрокрпЛ роОройрпНройроЯро╛ роЪрпЖропрпНропро▓ро╛роорпН?"

   "роорпБродро▓рпНро▓ роЕроирпНрод роЕро▒рпИроХрпНроХродро╡рпИ родро┐ро▒роирпНродрпБ ро╡ро┐роЯрпБро╡рпЛроорпН. 'роЪрпЖро▓рпН'ро▓рпИропрпБроорпН роЖройрпН роЪрпЖропрпНродрпБ ро╡ро┐роЯрпБроЩрпНроХро│рпН. " роОройрпНро▒ро╡ро│рпН родрпКроЯро░рпНроирпНродро╛ро│рпН,

   "роЯро╛ройро┐роХрпНроХрпБроорпН рокропро┐ро▒рпНроЪро┐роХро│рпБроорпН роЙроЯроорпНрокрпБроХрпНроХрпБ роороЯрпНроЯрпБрооро▓рпНро▓; рооройродрпБроХрпНроХрпБроорпН родрпЗро╡рпИ роЕрогрпНрогро╛."

тАж

   рооро▒рпБроиро╛ро│рпН роХро╛ро▓рпИ.

   ро░рооро╛ро╡ро┐ройрпН рооро╛родрпНродро┐ро░рпИроХро│рпИ роОроЯрпБродрпНродрпБ ро╡рпИродрпНродрпБроХрпН роХрпКрогрпНроЯро┐ро░рпБроирпНродро╛ройрпН рооро╛родро╡ройрпН.

   роЖро│рпБроХрпНроХрпКро░рпБ роХрокрпН роХро╛рокрпНрокро┐ропрпБроЯройрпН роЙро│рпНро│рпЗ ро╡роирпНродро╛ро│рпН рооро╛ро▓родро┐.

   "роиро╛ройрпЗ рокрпЛроЯрпНроЯ роХро╛рокрпНрокро┐, роиро▓рпНро▓ро╛ роЗро░рпБроХрпНроХро╛?"

   "роиро▓рпНро▓ро╛родрпНродро╛ройрпН роЗро░рпБроХрпНроХрпБ. роЖройро╛ро▓рпБроорпН роЙроЩрпНроХрогрпНрогро┐ роХрпИ роХро╛рокрпНрокро┐роХрпНроХрпБ роПроХрпНроХрооро╛ роЗро░рпБроХрпНроХрпБ."

   ро░рооро╛ родро┐ро░рпБроорпНрокро┐рокрпН рокро╛ро░рпНродрпНродро╛ро│рпЛ?

   "роХро╛ро░рпНройрпН роГрокрпНро│рпЗроХрпНро╕рпН рокрпВро░ро╛ро╡рпБроорпН рокро╛ро▓рпНро▓ роХро░рпИроЮрпНроЪрпБ рокрпЛроЪрпНроЪрпЗ рокро╛роЯрпНроЯро┐" ро╣ро╛ро▓ро┐ро▓рпН роЪрпБрокро╛ роЕро┤рпБро╡родрпБ роХрпЗроЯрпНроЯродрпБ.

   "роирпЗро▒рпНро▒рпБ роирпА роХрпЗроЯрпНроЯро┐ропрпЗройрпНройрпБ роЮро╛рокроХрооро╛ роХро╛ро▓рпИро▓ропрпЗ роЕрод рокро╛ро▓рпНро▓ роКро▒ ро╡рпЖроЪрпНроЪрпБроЯрпНроЯрпЗройрпЗроорпНрооро╛."

   "роЕроорпНрооро╛ро╡рпБроХрпНроХрпБ роОрокрпНрокрпЛ рокро╛роЯрпНроЯро┐ роЪро░ро┐ропро╛роХрпБроорпН?" роПроХрпНроХродрпНродрпБроЯройрпН роХрпЗроЯрпНроЯро╛ро│рпН роХрпБро┤роирпНродрпИ.



   роЪрпЖро▓рпНроГрокрпЛройрпН роЪро┐рогрпБроЩрпНроХро┐ропродрпБ. родро┐ро░рпБроорпНрокро┐рокрпН рокро╛ро░рпНродрпНродро╛ро▓рпБроорпН ро░рооро╛ роОроЯрпБроХрпНроХро╛родродро╛ро▓рпН, рооро╛родро╡ройрпН роОроЯрпБродрпНродрпБ, ро╕рпНрокрпАроХрпНроХро░рпИрокрпН рокрпЛроЯрпНроЯрпБ ро╡ро┐роЯрпНроЯро╛ройрпН.

   ро░рооро╛ роЖроГрокрпАро╕рпН роЕроХрпНроХро╡рпБрогрпНроЯрпЖройрпНроЯрпН родро╛ройрпН. роЙроЯро▓рпНроиро▓роорпН ро╡ро┐роЪро╛ро░ро┐родрпНродро╡ро░рпН родрпКроЯро░рпНроирпНродро╛ро░рпН,

   "роорпЗроЯроорпН роЗро▓рпНро▓ро╛рооро▓рпН роЗроЩрпНроХ рокро▓ роЪрооропроЩрпНроХро│рпН роХро╖рпНроЯрооро╛ роЗро░рпБроХрпНроХрпБ роЪро╛ро░рпН. ро╡рпАроЯрпНро▓ ро╡роЪрпНроЪрпЗ роЪро┐ро▓ роорпБроХрпНроХро┐ропрооро╛рой роГрокрпИро▓рпНроХро│рпИ роороЯрпНроЯрпБрооро╛ро╡родрпБ рокро╛ро░рпНроХрпНроХ роорпБроЯро┐ропрпБрооро╛ройрпНройрпБ роорпЗройрпЗроЬро░рпН роХрпЗроЯрпНроХро┐ро▒ро╛ро░рпН роЪро╛ро░рпН."

   "роЪро░ро┐, роиро╛ройрпН роХрпЗроЯрпНроЯрпБроЪрпН роЪрпКро▓рпНро▒рпЗройрпН" роОройрпНро▒рпБ роХрпВро▒ро┐ 'роЪрпЖро▓рпНтАЩро▓рпИ роЕрогрпИродрпНродрпБ ро╡ро┐роЯрпНроЯрпБ родро┐ро░рпБроорпНрокро┐роп рооро╛родро╡ройрпН родро┐роХрпИродрпНродро╛ройрпН.

   ро╕рпНроЯрпВро▓ро┐ро▓рпН ро╡рпИродрпНродро┐ро░рпБроирпНрод рооро╛родрпНродро┐ро░рпИроХро│рпИроХрпН роХро╛рогро╡ро┐ро▓рпНро▓рпИ.

   ро╡ро┐ропрокрпНрокрпБроЯройрпН родройрпНройрпИ роирпЖро░рпБроЩрпНроХро┐роп рооро╛родро╡ройрпИрокрпН рокро╛ро░рпНродрпНродрпБ ро░рооро╛ роХрпЗроЯрпНроЯро╛ро│рпН,

   "роГрокро┐ро╕ро┐ропрпЛродрпЖро░рокро┐ро╕рпНроЯрпН роОрокрпНрокрпЛ ро╡ро░рпБро╡ро╛ро░рпН рооро╛родрпБ?"

...

роиро╡роорпНрокро░рпН рооро▒рпНро▒рпБроорпН роЯро┐роЪроорпНрокро░рпН 2008 роороЩрпНроХрпИропро░рпН рооро▓ро░рпН роЗродро┤рпНроХро│ро┐ро▓рпН рооро┐ройро┐ родрпКроЯро░ро╛роХ рокро┐ро░роЪрпБро░рооро╛ройродрпБ.

** TODO something
