
#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: posts
#+HUGO_AUTO_SET_LASTMOD: f
#+AUTHOR:
#+hugo_custom_front_matter: :author "Lalitha Visvanathan"
#+HUGO_LASTMOD: f
#+seq_todo: TODO DRAFT CANCEL | DONE
#+STARTUP: logdone
#+STARTUP: content

* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:END:
** TODO Hugo and Tamil
:PROPERTIES:
:EXPORT_FILE_NAME: hugo-and-tamil
:END:
роЕроХро░ роорпБродро▓ роОро┤рпБродрпНродрпЖро▓рпНро▓ро╛роорпН роЖродро┐
рокроХро╡ройрпН роорпБродро▒рпНро▒рпЗ роЙро▓роХрпБ.

I always wanted to check how I can write in tamil for my blog. I tried reading up on i18 and other methods but I couldn't find anything simple. Finally I settled on Google docs.

Google docs lets me write in Tamil (родрооро┐ро┤рпН) and I can just copy paste it in my markdown file.
** DONE рокрпБро▓ро┐ропрпВро░рпНроХрпНроХрпБро▒ро┐роЪрпНроЪро┐ропро┐ро▓рпН роТроЯрпНроЯрпБроХрпНроХрпЗроЯрпНроЯро╡рпИ
CLOSED: [2020-08-19 Wed 16:23]
:PROPERTIES:
:EXPORT_FILE_NAME: puliyurkurichiyil-ottukettavai
:END:
"роПройрпНройро╛, "ро░ро╛роотАж." "роХро┐ро░рпБро╖рпНрогтАж" роЗроирпНрод ро░рпЖрогрпНроЯрпБ рокро╛роЯрпНроЯрпБро▓ роОродрпБ роиро▓рпНро▓ро╛ ро╡роирпНродро┐ро░рпБроХрпНроХрпБ?"

"ро░ро╛роотАж"

"роирпЗро▒рпНро▒рпБ роХрпЗроЯрпНроЯрокрпНрокрпЛ  'роХро┐ро░рпБро╖рпНрог..' рокро╛роЯрпНроЯрпБ роиро▓рпНро▓ро╛ роЗро░рпБроХрпНроХрпБройрпНройрпБ роЪрпКройрпНройрпЗро│рпЗ ЁЯШб?"

ЁЯШзЁЯШзЁЯШз

        ***********************

"роПроорпНрооро╛, роХро╛ро▓рпИро▓рпЗро░рпНроирпНродрпБ роЗроирпНрод рокро╛роЯрпНроЯрпИропрпЗ ро░рпЖроХрпНроХро╛ро░рпНроЯрпН рокрогрпНрогро┐рогрпНроЯро┐ро░рпБроХрпНроХрпЗ?

"роОройрпНройройрпНройрпБ роЪрпКро▓рпНро▓? рокро╛роЯрпНроЯ роорпБроЯро┐роХрпНроХро┐ро▒ роЪрооропродрпНродро┐ро▓ роЬройрпНройро▓ро╛рогрпНроЯ роТро░рпБ роХро╛роХрпНроХро╛ропрпН ро╡роирпНродрпБ роХродрпНродро┐ропро┐ро░рпБроХрпНроХрпБ"

"рокродрпНродрпБ роорогро┐роХрпНроХрпБ рокро╛роЯро┐ройро┐ропрпЗ"

"роХрпВро░ро┐ропро░рпНроХро╛ро░ройрпН ро╡роирпНродрпБ роХро╛ро▓ро┐роЩрпН рокрпЖро▓рпН роЕроЯро┐роЪрпНроЪродрпБ роЗродрпБро▓ ро░рпЖроХрпНроХро╛ро░рпНроЯрпН роЖропро┐ро░рпБроХрпНроХрпБ"

"роородро┐ропроорпН?"

"роЙроЩрпНроХрокрпНрокро╛ ро░рпЖроХрпНроХро╛ро░рпНроЯрпН рокрогрпНро▒рпЗройрпНройрпБ рокроХрпНроХродрпНродро┐ро▓рпН ро╡роирпНродрпБ  роЙроЯрпНроХро╛ро░рпНроирпНродрпБрогрпНроЯрпБ рокро╛родро┐ро▓  родрпБроорпНрооро┐роЯрпНроЯро╛ро░рпНроЯро╛"

"роЪро░ро┐, роИро╡рпНройро┐роЩрпН?"

"роХро╛рокро┐ роХрпБроЯро┐роЪрпНроЪрпБроЯрпНроЯрпБ рокро╛роЯро┐ройрпЗройро╛, роорпБроЯро┐роХрпНроХрпБроорпН рокрпЛродрпБ роПрокрпНрокроорпН ро╡роирпНродрпБроЯрпБродрпНродрпБ"

"..."

"роХрпКроЮрпНроЪ роорпБройрпНройро╛роЯро┐ роХрпБроЯрпНроЯро┐ ро░рпВроорпНро▓ роЙроЯрпНроХро╛ро░рпНроирпНродрпБ рокро╛роЯро┐ройрпЗройрпН. рокро╛роЯрпБроорпНрокрпЛродрпБ родрпЖро░ро┐ропро▓рпИ. роЖройро╛ роЕроирпНрод ро╣рпИродро░рпН роХро╛ро▓родрпНродрпБ роГрокрпЗройрпН роЪродрпНродроорпН роиро╛ро░ро╛роЪрооро╛ рокродро┐роЮрпНроЪро┐ро░рпБроХрпНроХрпБ. роЕродро╛ройрпН роЗрокрпНрок роЗроЩрпНроХ ро╡роирпНродрпБ, ро░рпВроорпН роХродро╡ родро╛ро│рпН рокрпЛроЯрпНроЯрпБ, роПроЪро┐ рокрпЛроЯрпНроЯрпБрогрпНроЯрпБ роХрогрпНрог роорпВроЯро┐рогрпНроЯрпБ роЪрпБроХрооро╛ рокро╛роЯро┐ропро┐ро░рпБроХрпНроХрпЗройрпН. роХрпЗроЯрпНроЯрпБрокрпН рокро╛ро░рпЗройрпН."

" роРропрпЛ роЕроорпНрооро╛, роорпКрокрпИро▓ роХро╡ройро┐роХрпНроХро▓ропро╛? роЪро╛ро░рпНроЬрпН роХрпБро▒роЮрпНроЪрпБ, роирпА рокро╛родро┐ рокро╛роЯрпБроорпНрокрпЛродрпЗ роЪрпЖро▓рпН роЖроГрокрпН роЖропро┐ро░рпБроХрпНроХрпБроорпНрооро╛"

 "ЁЯе╡ЁЯе╡ЁЯе╡"

    ***********************

"роЗроирпНрод ро░ро╛родрпНродро┐ро░ро┐ роирпЗро░родрпНро▓ роОродрпБроХрпНроХрпБроорпНрооро╛ рокрпБродрпБрокрпН рокроЯрпНроЯрпБрокрпНрокрпБроЯро╡рпИ роХроЯрпНроЯро┐рогрпНроЯро┐ро░рпБроХрпНроХро╛ропрпН? ро╡рпЗро░рпНроХрпНроХро▓рпИропро╛? роорпКрокрпИро▓рпНро▓ ро╡ро╛ропрпНро╕рпН  родро╛ройрпЗ ро░рпЖроХрпНроХро╛ро░рпНроЯрпН рокрогрпНрогрогрпБроорпН?"

"роЕрокрпНрокродрпНродро╛ройрпНроЯро╛ рокро╛роЯро▒  роорпВроЯрпН ро╡ро░рпБроорпН. роиро▓рпНро▓ роХроЪрпНроЪрпЗро░ро┐ роОроГрокрпЖроХрпНроЯрпН роХро┐роЯрпИроХрпНроХрпБроорпН"

ЁЯШЫЁЯШЫЁЯШЫ     ***********************

"роЗрокрпНрок роОродрпБроХрпНроХрпБроЯрпА рокро╛роЩрпНроХрпНро▓ рокрпБродрпБ роЕроХрпНроХро╡рпБрогрпНроЯрпН роУрокройрпН рокрогрпНрог роЪрпКро▓рпНро▒рпЗ. роЕродро╛ройрпН роЬро╛ропро┐рогрпНроЯрпН роЕроХрпНроХро╡рпБрогрпНроЯрпН роЗро░рпБроХрпНроХрпЗ"

"роЗроЩрпНроХ рокро╛ро░рпБроЩрпНроХ. роОройроХрпНроХрпБ рокро╛роЯрпНроЯрпБ рокрпЛроЯрпНроЯро┐роХро│рпНро▓ роЗродрпЗ рокрпЛро▓ роиро┐ро▒рпИроп роХрпЗро╖рпН рокрпНро░рпИро╕рпН роХро┐роЯрпИроХрпНроХрпБроорпН роЗро▓рпНро▓ро┐ропро╛? роЕрокрпНрок роЙроЩрпНроХро│рпБроХрпНроХрпБ роЯрпЗроХрпНро╕рпН рокрпНро░ро╛рокрпНро│роорпН ро╡ро░ роХрпВроЯро╛родрпБройрпНройрпБ родро╛ройрпН"

ЁЯдеЁЯдеЁЯде

      ***********************

"роЗроирпНрод рокро╛роЯрпНроЯрпБ роирпА рокро╛роЯро┐ройро╛ роиро▓рпНро▓ро╛ роЗро░рпБроХрпНроХрпБроорпЗроорпНрооро╛. роПройрпН ро╡рпЗрогрпНроЯро╛роЩрпНроХро▒рпЗ"

"роиро╛ройрпН ро░рпЖрогрпНроЯро╛роорпН роХрпНро│ро╛ро╕рпН рокроЯро┐роХрпНроХро▒роЪрпНроЪрпЗ роЪро╛роирпНродро╛ роЗроирпНрод рокро╛роЯрпНроЯрпБ рокро╛роЯро┐ роЪрпЖроХрогрпНроЯрпН рокрпНро░рпИро╕рпН ро╡ро╛роЩрпНроХро┐ройро╛. роЕро╡ро│рпБроорпН роЗроирпНрод роХрпНро░рпВрокрпНро▓ роЗро░рпБроХрпНроХро╛. роЕро╡ рокро╛роЯрпНроЯ роиро╛ройрпН роХро╛рокрпНрокро┐ропроЯро┐роЪрпНроЪрпБроЯрпНроЯрпЗройрпНройрпБ роЪрпКро▓рпНро╡ро╛роЯро╛"

ЁЯдФЁЯдФЁЯдФ

      ***********************

"роОройрпНрой? роЙроЯройрпЗ рокрпБродрпБ роорпКрокрпИро▓рпН ро╡ро╛роЩрпНроХрогрпБрооро╛? роЙройрпНроХро┐роЯрпНроЯ родро╛ройрпН роЗро░рпБроХрпНроХрпЗроЯрпА"

"роЗродрпБро▓ рокро╛роЯрпНроЯрпБ ро░рпЖроХрпНроХро╛ро░рпНроЯрпН рокрогрпНрогро┐ройро╛ роХрпБро░ро▓рпН роиро▓рпНро▓ро╛ро╡рпЗ ро╡ро░ро▓рпИ. рокро╛ро░рпБроЩрпНроХ, ро╡рпЗро▒ роОро▓рпНро▓ро╛ро░рпЛроЯродрпБроорпН роОро╡рпНро╡ро│ро╡рпБ роиро▓рпНро▓ро╛  роЗро░рпБроХрпНроХрпБ рокро╛ро░рпБроЩрпНроХ"

ЁЯШиЁЯШиЁЯШи

     ***********************

"роОройрпНройроорпНрооро╛, рокро╛роЯрпНроЯро┐ ро░рпЖрогрпНроЯрпБ роиро╛ро│ро╛ ро░рпЖро╕рпНроЯрпНро▓рпЖро╕рпНро╕ро╛ роПродрпЛ ропрпЛроЪройрпИропро╛ роЗро░рпБроХрпНроХро╛ро│рпЗ. роПродрпБроорпН рокро┐ро░роЪрпНройрпИропро╛?"

"роЕродрпБ роТройрпНройрпБроорпН роЗро▓рпНро▓рпИроЯро┐. роЕро╡ро╛ роКро░рпН роХрпБро░рпВрокрпН рокро╛роЯрпНроЯрпБрокрпН рокрпЛроЯрпНроЯро┐ро▓ роЬроЯрпНроЬро╛ роЗро░рпБроХрпНроХро╛ роЗро▓рпНро▓ро┐ропро╛? роОро▓рпНро▓ро╛ро░рпБроорпЗ роиро▓рпНро▓ро╛ рокро╛роЯро┐ропро┐ро░рпБроХрпНроХро╛ро│ро╛роорпН. роОрокрпНрокроЯро┐ ро╡ро░ро┐роЪрпИрокрпНрокроЯрпБродрпНродройрпНройрпБ ропрпЛроЪро┐роХрпНроХро▒ро╛"

ЁЯЩГЁЯЩГЁЯЩГ

     ***********************

"... роЗроирпНрод рокро╛роЯрпНроЯрпБ роирпА роиро▓рпНро▓ро╛ рокро╛роЯрпБро╡ро┐ропрпЗроорпНрооро╛, роЗрокрпНрок роПройрпН ро╡рпЗрогрпНроЯро╛роЩрпНроХро▒рпЗ"

"роЪро╛роирпНродро╛ роЗродрпИ ро░рпЖроХрпНроХро╛ро░рпНроЯрпН рокрогрпНрогро┐ роЕройрпБрокрпНрок ро░рпЖроЯро┐ рокрогрпНрогро┐роЯрпНроЯро╛."

"роЕроорпЖро░ро┐роХрпНроХро╛ро╡ро┐ро▓рпН роЗро░рпБроХрпНроХро┐ро▒ роЕроирпНрод роЖройрпНроЯрпНроЯро┐ роЪрпЖропрпНро▒родрпБ роЙройроХрпНроХрпБ роОрокрпНрокроЯро┐роорпНрооро╛ родрпЖро░ро┐ропрпБроорпН?"

"роЕро╡ро│рпЛроЯ роТройрпНро▒рпБро╡ро┐роЯрпНроЯ роиро╛родрпНродройро╛ро░рпЛроЯ ро░рпЖрогрпНроЯрпБ ро╡ро┐роЯрпНроЯ роУро░рпНрокрпНрокроЯро┐ропрпЛроЯ рокро┐ро░рогрпНроЯрпЛроЯ рооройрпНройро┐ роЗроЩрпНроХрпЗ роОройрпН рокроЬройрпН роХрпБро░рпВрокрпНро▓ роЗро░рпБроХрпНроХро╛. роЕро╡родро╛ройрпН роЪрпКройрпНройро╛."

ЁЯдФЁЯдФЁЯдФ

      ***********************

"роХрпЛроирпНродрпЗ"

"роОройрпНрой родро╛родрпНродро╛?"

"роОроЩрпНроХ роКро░рпН роХрпНро░рпВрокрпНро▓ рокро╛роЯрпНроЯрпБрокрпНрокрпЛроЯрпНроЯро┐ роЗро░рпБроХрпНроХрпБ. роирпАропрпБроорпН роТро░рпБ рокро╛роЯрпНроЯрпБ рокро╛роЯрпЗройрпН"

"роУроХрпЗ родро╛родрпНродро╛"

"роЗро░рпБ. роЪрпБро░рпБродро┐ роЪрпЗро░рпНродрпНродрпБроХрпНроХро▒рпЗройрпНтАж. роЪро░ро┐, рокро╛роЯро▒ро┐ропро╛?"

"ЁЯЧгя╕ПЁЯЧгя╕ПЁЯЧгя╕П"

"роХрпЛроирпНродрпЗ, роЕроирпНрод роЪро╛роХрпНро▓рпЗроЯрпНроЯ роорпБро┤рпБроЪро╛ роорпБро┤рпБроЩрпНроХро┐роЯрпНроЯрпБ рокро╛роЯрпБ"

"роОройрпНроХрпВроЯ uno ро╡ро┐ро│рпИропро╛роЯ ро╡ро╛роЩрпНроХ родро╛родрпНродро╛. роХрпЗроорпН роорпБроЯро┐роЮрпНроЪродрпБроорпН рокро╛роЯро▓ро╛роорпН"

"ро░рпКроорпНрок роирпЗро░рооро╛роХрпБроорпЗ"

"роиро╛ройрпН ро╡ро┐ройрпН рокрогрпНрогро┐ройродрпБроорпН рокро╛роЯро▒рпЗройрпН родро╛родрпНродро╛"

"роЪро░ро┐роЯро╛ роХрогрпНрогро╛"

"роХрпЛроирпНродрпЗ, рокро╛роЯро▓ро╛рооро╛?"

"роЯро┐роГрокройрпН роЪро╛рокрпНрокро┐роЯрпНроЯрпБроЯрпНроЯрпБ ро╡ро▒рпЗройрпН родро╛родрпНродро╛"

"роХрпЛроирпНродрпЗ, рокро╛роЯро▓ро╛рооро╛?"

"роЖройрпНро▓рпИройрпН роХро┐ро│ро╛ро╕рпН родрпКроЯроЩрпНроХро┐ро░рпБроХрпНроХрпБ родро╛родрпНродро╛. роЕроорпНрооро╛ роХрпВрокрпНрокро┐роЯро▒ро╛ "

"роХрпЛроирпНродрпЗ, рокро╛роЯро▓ро╛рооро╛?"

"ро░ро╡ро┐ ро╡ро┐ро│рпИропро╛роЯ ро╡роирпНродро┐ро░рпБроХрпНроХро╛ройрпН родро╛родрпНродро╛. роХрпКроЮрпНроЪ роирпЗро░роорпН ро╡ро┐ро│рпИропро╛роЯро┐роЯрпНроЯрпБ ро╡ро░рпЗройрпЗ"

"роХрпЛроирпНродрпЗ, рокро╛роЯро▓ро╛рооро╛?"

"роЖройрпНро▓рпИройрпНро▓ рооро┐ропрпВроЪро┐роХрпН роХро┐ро│ро╛ро╕рпНроХрпНроХрпБ роирпЗро░рооро╛роЪрпНроЪрпБ родро╛родрпНродро╛"

"роХрпЛроирпНродрпЗ, рокро╛роЯро▓ро╛рооро╛?"

"ро╣рпЛроорпН ро╡рпКро░рпНроХрпН роорпБроЯро┐роХрпНроХрогрпБроорпН родро╛родрпНродро╛"

"роХрпЛроирпНродрпЗ, роТро░рпБ роорогро┐роХрпНроХрпВро░рпНро▓ рокро╛роЯрпНроЯ роЕройрпБрокрпНрокрогрпБроорпН. роХрпКроЮрпНроЪроорпН рокро╛роЯрпЗройрпН"

"родрпВроХрпНроХроорпН ро╡ро▒родрпБ родро╛родрпНродро╛"

"роХрпЛроирпНродрпЗ, рокрпНро│рпАро╕рпНроЯро╛"

"ЁЯЧгя╕ПЁЯЧгя╕ПЁЯЧгя╕П"

"роХрпЛроирпНродрпЗ, роЗроЩроХрпНро▓рпАро╖рпН ро╡рпЗрогрпНроЯро╛роорпН роХрогрпНрогро╛. роТро░рпБ роЪро╛рооро┐ рокро╛роЯрпНроЯрпБ рокро╛роЯрпЗройрпН"

"ЁЯЧгя╕ПЁЯЧгя╕П ЁЯе▒...ЁЯЧгя╕ПЁЯе▒.."

'роХрпБро┤роирпНродрпИ родро╛ройрпЗ. роХрпКроЯрпНроЯро╛ро╡ро┐ ро╡ро┐роЯрпНроЯрпБрогрпНроЯрпЗ рокро╛роЯро┐роЯрпНроЯрпБ, рокро╛родро┐ро▓ родрпВроЩрпНроХро┐роЯрпНроЯро╛ройрпН.  рокро░ро╡ро╛ропро┐ро▓рпНро▓рпИ. роЕройрпБрокрпНрокро┐ ро╡рпИрокрпНрокрпЛроорпН.  роЕроЯрпБродрпНрод ро░ро╡рпБрогрпНроЯрпБроХрпНроХрпБ роорпВрогрпБ роиро╛ро│рпН роЗро░рпБроХрпНроХрпЗ'

ЁЯСитАНЁЯжпЁЯСитАНЁЯжпЁЯСитАНЁЯжп



***********************

"роОройрпНройрокрпНрокро╛? роЗроирпНрод рокродрпНродрпБ роиро╛ро│ро╛ роЪро╛рокрпНрокро╛роЯрпБ ро╡ро┐родрпНродро┐ропро╛роЪрооро╛ роЗро░рпБроХрпНроХрпЗ. роироЯрпНро╕рпН, роГрокрпНро░рпВроЯрпНро╕рпН, ро╡рпЖро░рпИроЯрпНроЯро┐ ро░рпИро╕рпН, роЪро┐рокрпНро╕рпН, take away foods... роОройрпНройро╛роЪрпНроЪрпБ?"

"Pky роХрпНро░рпВрокрпНро▓ рокро╛роЯрпНроЯрпБрокрпН рокрпЛроЯрпНроЯро┐ роироЯроХрпНроХро┐ро▒родрпБ роЗро▓рпНро▓ро┐ропро╛? роЕродро╛ройрпНтАж"

ЁЯШЛЁЯШЛЁЯШЛ                 ***********************

"роОройрпНройроЯро╛, роЙроЩрпНроХроорпНрооро╛ ро░рпКроорпНрок рокрпКро▓ро┐ро╡ро╛ родрпЖро░ро┐ропро▒ро╛ро│рпЗ. рокродрпНродрпБ ро╡ропродрпБ роХрпБро▒роЮрпНроЪ рооро╛родро┐ро░ро┐ роЗро▓рпНро▓рпИ?"

" роЕродро╛ройрпН роЕрокрпНрокро╛, роЕро╡роЩрпНроХ роКро░рпН роХрпНро░рпВрокрпН рокро╛роЯрпНроЯрпБрокрпНрокрпЛроЯрпНроЯро┐ро▓ роЪрпЗро░рпНроирпНродрпБ рокро╛роЯро┐ройродрпБро▓рпЗро░рпНроирпНродрпБ ро░рпКроорпНрок роЙро▒рпНроЪро╛роХрооро╛роХро┐роЯрпНроЯро╛роЩрпНроХ. роЕродрпЛроЯ, роЗрокрпНрокро▓рпНро▓ро╛роорпН роХрпЛрокроорпН роЪро┐роЯрпБроЪро┐роЯрпБрокрпНрокрпБ роОродрпБро╡рпБроорпЗ роЗро▓рпНро▓рпИрокрпНрокро╛."

"роЪро░ро┐родро╛ройрпН. роЕрокрпНрокроЯро┐ройрпНройро╛ роЕроирпНрод роЕроЯрпНрооро┐ройрпНроЯрпНроЯ роЪрпКро▓рпНро▓ро┐ роЕроЯро┐роХрпНроХроЯро┐ роЗроирпНрод рооро╛родро┐ро░ро┐ рокрпЛроЯрпНроЯро┐роХро│рпН ро╡рпИроХрпНроХ роЪрпКро▓рпНро▓рогрпБроорпН. роЪрпЖропрпНро╡ро╛ро░рпНроХро│ро╛?"

"ЁЯСМ super idea роЕрокрпНрокро╛"

  ***********************

** DONE роХрпЛрокроорпН роХрпЛрокрооро╛роХро╡ро░рпБроХро┐ро▒родрпБ
CLOSED: [2020-08-25 Tue 13:45]
:PROPERTIES:
:EXPORT_FILE_NAME: kobam-kobamaga-varugirathu
:END:
рокрпЖро▒рпНро▒ роороХро│рпИропрпКродрпНрод роЕрокрпНрокро╛ро╡ро┐ рооро╛рогро╡ро┐роХро│ро┐роЯроорпН роЪро┐ро▓рпНрооро┐ро╖роорпН роЪрпЖропрпНропрпБроорпН роЪро┐ро▓ ро╡ро╛родрпНродро┐ропро╛ро░рпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

роЪро╛ро▓рпИ ро╡ро┐родро┐роХро│рпИ, роЪро┐роХрпНройро▓рпНроХро│рпИ роЕро▓роЯрпНроЪро┐ропрооро╛роХ роорпАро▒ро┐роЪрпН роЪрпЖройрпНро▒рпБ, рокро┐ройрпН рооро╛ро░рпНродроЯрпНроЯро┐роЪрпН роЪро┐ро░ро┐роХрпНроХрпБроорпН ро╡ро╛роХрой роУроЯрпНроЯро┐роХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

роиро╛роЯрпНроЯрпБроХрпНроХрпБроорпН ро╡рпАроЯрпНроЯрпБроХрпНроХрпБроорпН роЪрпКроирпНрод роЙропро┐ро░рпБроХрпНроХрпБроорпН ро╡ро┐ро╖роорпН  роОройрпНро▒рпБ родрпЖро░ро┐роирпНродро┐ро░рпБроирпНродрпБроорпН, роородрпБроХрпНроХроЯрпИроХро│ро┐ро▓рпН роЕро▓рпИроорпЛродрпБроорпН роХрпВроЯрпНроЯродрпНродрпИроХрпН роХрогрпНроЯро╛ро▓рпН...

рокрпКродрпБ роЗроЯроЩрпНроХро│ро┐ро▓рпН роОроЪрпНроЪро┐ро▓рпН родрпБрокрпНрокрпБрокро╡ро░рпНроХро│рпН, рокрпБроХрпИ рокро┐роЯро┐рокрпНрокро╡ро░рпНроХро│рпН, ро▓роЬрпНроЬрпИропро┐ройрпНро▒ро┐ 'роТродрпБроЩрпНроХрпБ'рокро╡ро░рпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

ро╡рпАроЯрпНроЯрпБроХрпН роХрпБрокрпНрокрпИроХро│рпИ родрпЖро░рпБро╡рпЛро░роХрпН роХрпБрокрпНрокрпИродрпН родрпКроЯрпНроЯро┐роХро│ро┐ро▓рпН роТро┤рпБроЩрпНроХро╛роХрокрпН рокрпЛроЯро╛рооро▓рпН (роорпВроХрпНроХрпИрокрпН рокро┐роЯро┐родрпНродрпБроХрпНроХрпКрогрпНроЯрпБ) ро╡рпАроЪро┐ ро╡ро┐роЯрпНроЯрпЖро▒ро┐рокро╡ро░рпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

рооро┐роХ рооро┐роХ рооро┐роХ роЖроЯроорпНрокро░рооро╛роХ родро┐ро░рпБроорогроорпН роироЯродрпНродро┐, рокро┐ройрпН роЕроирпНрод роХроЯройрпИропрпБроорпН рокрпЖрогрпН родро▓рпИропро┐ро▓рпЗропрпЗ роХроЯрпНроЯро┐ро╡ро┐роЯрпБроорпН рокрпЖро▒рпНро▒рпЛро░рпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпНтАж(роПро▒рпНроХрпЖройро╡рпЗ роЗро╡ро░рпНроХро│рпН роЪрпБропроиро▓родрпНродро╛ро▓рпН ро▓рпЗроЯрпН роорпЗро░рпЗроЬрпН тАж)

рокроЯро┐рокрпНрокрпБ, роЕроирпНродро╕рпНродро┐ро▓рпН  роХрпБро▒рпИроирпНрод роирогрпНрокро░рпН, роЙро▒ро╡ро┐ройро░рпНроХро│рпИ (рокрпЖро▒рпНро▒рпЛро░рпИропрпБроорпН роЪрпЗро░рпНродрпНродрпБ)  родрпЖро░ро┐роирпНродро╡ро░рпНроХро│ро┐роЯроорпН роЕро▒ро┐роорпБроХроорпН роЪрпЖропрпНроп ро╡рпЖроЯрпНроХрокрпНрокроЯрпБроорпН 'рокрпЖро░рпАроп' рооройро┐родро░рпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпНтАж

роЙро░рпБрокрпНрокроЯро┐ропро╛роХ роОродрпБро╡рпБроорпЗ родрпЖро░ро┐ропро╛ ро╡ро┐роЯрпНроЯро╛ро▓рпБроорпН, "роР роЯрпЛрогрпН роирпЛ роЯро╛рооро┐ро▓рпН" роОройрпНро▒рпБ ро╡рпЖроЯрпНроХрооро┐ройрпНро▒ро┐ роЪро┐ро▓рпБрокрпНрокро┐роХрпН роХрпКрогрпНроЯрпБ родро┐ро░ро┐ропрпБроорпН роЪро┐ро▓ ро▓рпВроЪрпБроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

роЪро░ро┐ропро╛роХ роЖро░ро╛ропро╛рооро▓рпН, роОродрпИропро╛ро╡родрпБ роОрокрпНрокроЯро┐ропро╛ро╡родрпБ роЪрпЖропрпНродро┐ропро╛роХ ро╡рпЖро│ро┐ропро┐роЯрпНроЯрпБ рокро░рокро░рокрпНрокрпИ  родрпЗроЯро┐роХрпНроХрпКро│рпНро│рпБроорпН роЪро┐ро▓ роКроЯроХроЩрпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

роХрпКро░рпКройро╛ роЙро▓роХрпИропрпЗ роЕроЪрпНроЪрпБро▒рпБродрпНрод, рооро╛ро╕рпНроХрпН роЕрогро┐ропро╛рооро▓рпН, родрпЗро╡рпИропро┐ро▓рпНро▓ро╛род рокрпЛродрпБроорпН рокрпКродрпБ роЗроЯроЩрпНроХро│ро┐ро▓рпН  роЕро▓роЯрпНроЪро┐ропрооро╛роХ роЪрпБро▒рпНро▒ро┐родрпН  родро┐ро░ро┐рокро╡ро░рпНроХро│рпИроХрпН роХрогрпНроЯро╛ро▓рпН...

роЗро╡рпИропрпЖро▓рпНро▓ро╛роорпН родрпЖро░ро┐роирпНродрпБроорпН рокрпБро░ро┐роирпНродрпБроорпН роЙрогро░рпНродрпНродрпБроорпН роХрогрпНроЯрпБроорпН роХро╛рогро╛рооро▓рпН рокрпЛроХрпБроорпН роОройрпН роХрпИропро╛ро▓ро╛роХро╛родрпНродройродрпНродрпИ роиро┐ройрпИродрпНродро╛ро▓рпЗ  роХрпЛрокроорпН роХрпЛрокроорпН роХрпЛрокрооро╛роХ ро╡ро░рпБроХро┐ро▒родрпБтАж.

** DONE роХро▓ро┐ роорпБродрпНродро┐рокрпН рокрпЛроЪрпНроЪрпБ :роЪро┐ро▒рпБроХродрпИ:
CLOSED: [2020-08-28 Fri 00:48]
:PROPERTIES:
:EXPORT_FILE_NAME: kali-muthi-pochu
:END:
*роЪрооро░рпНрокрпНрокрогроорпН* :  роОродро▒рпНроХрпЖроЯрпБродрпНродро╛ро▓рпБроорпН тАЬро╣рпНроорпНтАж роОроЩрпНроХ роХро╛ро▓роорпН рокрпЛро▓ ро╡ро░рпБрооро╛тАж.тАЭ роОройрпНро▒рпБ роЪродро╛ роЕроЩрпНроХро▓ро╛ропрпНрокрпНрокро╡ро░рпНроХро│рпБроХрпНроХрпБтАж!

*** роорпБроирпНродро╛роиро╛ро│рпН

тАЬроХро▓ро┐ роорпБродрпНродро┐рокрпН рокрпЛроЪрпНроЪрпБроЯрпА ро░рпБроХрпНроХрпБтАЭ

тАЬроОройрпНрой роЪрпКро▓рпНро▒рпЗро│рпНтАЭ

тАЬроироорпНрок рокро┐ро│рпНро│рпИропро╛рогрпНроЯройрпИропрпЗ рокро╛ро░рпЗройрпН. роХроЯрпНроЯрпБроХрпНроХрпБроЯрпБрооро┐ропрпБроорпН роХроЯрпБроХрпНроХройрпБрооро╛ роЬроорпНроорпБройрпНройрпБ роЗро░рпБроирпНродро╡ройрпН, роОрокрпНрокроЯро┐ роЕро▓роЩрпНроХрпЛро▓роорпН рокрогрпНрогро┐рогрпНроЯрпБ ро╡роирпНродрпБ роиро┐роХрпНроХро▒ро╛ройрпН рокро╛ро░рпБ.тАЭ

тАЬроРропрпИропрпЛ.. роЗродро╛ройрпН роХрпНро░ро╛рокрпНрокрпБ родро▓рпИропро╛... тАЬ

тАЬроЖрооро╛роорпНроЯрпА. ро╡рпЗро╖рпНроЯро┐ропроХрпНроХрпВроЯ роЗрокрпНрокро▓рпНро▓ро╛роорпН родро╛ро░рпН рокро╛ропрпНроЪрпНроЪро┐ роХроЯрпНроЯро┐роХрпНроХро┐ро▒родро┐ро▓рпНро▓рпИ. роЪрпБроорпНрооро╛ роТро░рпБ роЪрпБро▒рпНро▒рпБ. роЕро╡рпНро╡ро│ро╡рпБродро╛ройрпН.  роЗродрпБро▓ роТро░рпБ роЯрокрпНрокро╛роХрпНроХроЯрпНроЯрпБ ро╡рпЗро▒тАжтАЭ

тАЬроПродрпЛ рокрпБродрпБ родро┐ройрпБроЪро╛ рокро╛роЯрпНроЯрпБ рооро╛родро┐ро░ро┐ роорпБрогрпБроорпБрогрпБроХрпНроХро┐ро▒ро╛ройрпЗ.тАЭ

тАЬроЪро┐ройро┐рооро╛ рокро╛роЯрпНроЯрпБроЯрпА. рокрпБродрпБроЪро╛ ро╡ро╛роЩрпНроХро┐ роОрокрпНрокро╡рпБроорпН роХро╛родрпБ роХро┐роЯрпНроЯропрпЗ ро╡роЪрпНроЪрпБрогрпНроЯрпБ роироЯроХрпНроХро┐ро▒ро╛ройрпЗтАж. роЯрпНро░ро╛ройрпНро╕ро┐ро╕рпНроЯро░рпНройрпБ.  роЕродрпБро▓ роХрпЗроЯрпНроЯрпБроХрпНроХро▒родрпБ родро╛ройрпН роЗродрпЖро▓рпНро▓ро╛роорпН.тАЬ

тАЬроЕроЯ ро░ро╛рооро╛тАж роПройрпН родро╛ройрпН рокрпБродрпНродро┐ роЗрокрпНрокроЯро┐ рокрпЛро▒родрпЛтАЭ

тАЬродрпБро░рпИ роЖрокро┐ро╕рпН ро╡рпЗро▓рпИроХрпНроХрпБрокрпН рокрпЛро▒ро╛ройрпНро▓, роЕроирпНрод рокро╡ро┐ро╖рпБтАЭ

тАЬроЕродрпБ роЪро░ро┐, роЕро╡ройрпН рокрпКрогрпНроЯро╛роЯрпНроЯро┐ роороЯрпНроЯрпБроорпН роОройрпНройро╡ро╛роорпН? роорпБродро▓рпНро▓ роЗроирпНрод рокро╛роХрпАро░родро┐ропрпБроорпН роороЯро┐роЪро╛ро░рпБроорпН роХрпЛроЯро╛ро▓ро┐роХрпН роХрпКрогрпНроЯрпИропрпБрооро╛ рокродро╡ро┐роЪро╛родрпНродро╛ройрпЗ роЗро░рпБроирпНродро╛. рокрпЛрой рооро╛роЪроорпН роЕро╡ родроЩрпНроХрпИропрпИ рокро╛ро░рпНроХрпНроХ роородро░ро╛ро╕рпН рокрпЛропро┐роЯрпНроЯрпБ  ро╡роирпНродро╛ро▓рпБроорпН ро╡роирпНродро╛, родро╛роЩрпНроХро▓. ро╕ро╛ро░ро┐ройрпНройрпБ роТрогрпНрог роХроЯрпНроЯро┐роХрпНроХро┐ро▒ро╛ рокро╛ро░рпБроЩрпНроХ. роорпКродрпНрод роирпАро│роорпЗ роЖро▒рпБ роХроЬроорпНродро╛ройрпН. роЕродрпБро▓ роТро░рпБ роорпАроЯрпНроЯро░рпБроХрпНроХрпБ роорпЗро▓ропрпЗ родро▓рокрпНрокрпБройрпНройрпБ роЪрпКро▓рпНро▓ро┐ роХро╛ро▒рпНро▒рпБро▓ рокро▒роХрпНроХро▒родрпБ. роЕроирпНрод ро╕ро╛ро░ро┐ роХро▓ро░рпНро▓ропрпЗ роЪроЯрпНроЯрпИ. роорпЗроЯрпНроЪро┐роЩрпНроХро╛роорпН. роЕродрпБ роороЯрпНроЯрпБрооро╛, роЪро┐ройрпНройрокрпНрокрпЖрогрпН рооро╛родро┐ро░ро┐ роЬроЯрпИ рокро┐ройрпНройро┐ ро░ро┐рокрпНрокройрпН ро╡роЪрпНроЪрпБтАж рокрпЛродро╛роХрпНроХрпБро▒рпИроХрпНроХрпБ ро╕рпНройрпЛ, рокро╡рпБроЯро░рпНройрпБ роОройрпНройрпЖройрпНройро╡рпЛ роХрогрогро▒ро╛ро╡ро┐.тАЭ

тАЬроЖроЪро╛ро░роЩрпНроХро▒родрпБ ро╡ро┐роЯрпНроЯрпЗ рокрпЛроЪрпНроЪрпБ. роирпЗро▒рпНро▒рпБ ро╡ро┐роЪрпНроЪрпБро╡рокрпН рокро╛ро░рпНроХрпНроХ роЪро┐ройрпЗроХро┐родройрпН роироЯрпЗроЪройрпН ро╡роирпНродро┐ро░рпБроХрпНроХро╛ройрпН, роЙро│рпНродро┐рогрпНрогрпИ рокрпЖроЮрпНроЪрпНро▓ роЙроЯрпНроХро╛ро░ ро╡роЪрпНроЪрпБ роЗро╡ройрпН ро╡ро░рпНро▒ ро╡ро░рпИроХрпНроХрпБроорпН рокрпЗроЪро┐рогрпНроЯро┐ро░рпБроХрпНроХро╛тАЭ

тАЬроЗроЩрпНроХ ро░рпЗро┤ро┐ро▓ роЪро┐ро░ро┐роЪрпНроЪро╛ родро┐рогрпНрогрпИ ро╡ро░рпИроХрпНроХрпБроорпН роХрпЗроЯрпНроХрпБродрпБтАЭ

тАЬроЕроЯро┐роХрпНроХроЯро┐ ро░роХроЪро┐ропрооро╛ ро░рпЖрогрпНроЯрпБ рокрпЗро░рпБроорпН роЪро┐ройро┐рооро╛ роХрпВроЯрокрпН рокрпЛро▒ро╛ройрпНройро╛ рокро╛ро░рпНродрпНродрпБроХрпНроХрпЛ.тАЭ

тАЬроЪро┐ро╡роЪро┐ро╡ро╛, роОро▓рпНро▓ро╛роорпН роХрпИроорпАро▒ро┐рокрпН рокрпЛропро╛роЪрпНроЪрпБ. роОройрпНрой роЪрпЖропрпНроп?тАЭ

тАЬроХро▓ро┐роХро╛ро▓роорпН роХро▓ро┐роХро╛ро▓роорпНтАжтАЭ

*** роирпЗро▒рпНро▒рпБ

тАЬроХро▓ро┐ роорпБродрпНродро┐рокрпН рокрпЛроЪрпНроЪрпБроЯрпА рокро╛роХро┐тАЭ

тАЬроПройрпН? роОройрпНройро╛роЪрпНроЪрпБ?тАЭ

тАЬроироорпНрок роЪрпАройрпБро╡рпБроХрпНроХрпБ ро░рпЖрогрпНроЯрпБ ро╡рпЗро╖рпНроЯро┐ ро╡ро╛роЩрпНроХро┐роЯрпНроЯрпБ ро╡роирпНродрпЗройрпН. ро╡рпЗрогрпНроЯро╛роорпНройрпБ роЪрпКро▓рпНро▒ро╛ройрпН. роЖрокрпАроЪрпБроХрпНроХрпБ, ро╡рпЖро│ро┐ро▓ рокрпЛроХро╡ро░ рокрпЗрогрпНроЯрпН ро╖ро░рпНроЯрпН родро╛ройрпН роЪрпМроХро░рпНропрооро╛ роЗро░рпБроХрпНроХро╛роорпН. ро╡рпАроЯрпНро▓ роЗро░рпБроХрпНроХро▒роЪрпНроЪ роОрокрпНрокрокрпНрокро╛ро░рпБ роТро░рпБ роХрпИро▓ро┐ропрпБроорпН роТро░рпБ рокройро┐ропройрпБроорпН. родрпАро╡роЯрпНроЯро┐роХрпН  роХрпКро│рпНро│рпИроХрпНроХро╛ро░ройро╛роЯрпНроЯроорпН роЗро░рпБроХрпНроХрпБ.тАЭ

тАЬродро▓рпИропрпИрокрпН рокро╛ро░рпБ. роТро┤рпБроЩрпНроХро╛ роТро░рпБ роХрпНро░ро╛рокрпН ро╡рпЖроЯрпНроЯро┐роХрпНроХро╛роо, ро╕рпНроЯрпЖрокрпН роХроЯрпНроЯро┐роЩрпН, рокройрпН роХроЯрпНроЯро┐роЩрпНройрпБ рокрогрпНрогро┐рогрпНроЯрпБ ро╡роирпНродрпБ родро▓рпИроп роЪро┐ро▓рпБрокрпНрокро┐ роЪро┐ро▓рпБрокрпНрокро┐ роХро╛роЯрпНроЯро┐...тАЭ

тАЬроХро╛родрпБ роХро┐роЯрпНроЯ роХро┐ро░рпБродро╛, роорпВроХрпНроХрпБроХрпНроХроЯро┐ро▓ роорпАроЪрпИ роОро▓рпНро▓ро╛роорпН ро╡ро│ро░рпНроХрпНроХродрпН родрпКроЯроЩрпНроХро┐ропро┐ро░рпБроХрпНроХро╛ройрпЗ. рокропрооро╛родрпНродро╛ройро┐ро░рпБроХрпНроХрпБтАЭ

тАЬроОро▓рпНро▓ро╛роорпН роЗроирпНрод роЪро┐ройро┐рооро╛роХрпНроХро╛ро░ро╛ро│рпИроХрпН роХро╛рокрпНрокро┐ропроЯро┐роХрпНроХро┐ро▒родрпБроХро│рпН. роиро▓рпНро▓родрпБроХрпНроХро╛ роЗродрпЖро▓рпНро▓ро╛роорпН?тАЭ

тАЬроЕро╡ройрпН рокрпКрогрпНроЯро╛роЯрпНроЯро┐ ро░рооро╛ро╡рпБроорпН роЪро│рпИроЪрпНроЪро╡ро│ро┐ро▓рпНро▓рпИ. роЗроирпНрод рокроорпНрокро╛ропрпН роХро▓рпНропро╛рогродрпНродрпБроХрпНроХрпБрокрпН рокрпЛропро┐роЯрпНроЯрпБ ро╡роирпНродро╛ро▓рпБроорпН ро╡роирпНродро╛, роОро▓рпНро▓ро╛роорпЗ рооро╛ро▒ро┐рогрпНроЯро┐ро░рпБроХрпНроХрпБ. рокрпКроорпНрооройро╛роЯрпНроЯро┐роХрпНроХрпБ роЪрпЗро▓рпИ родро╛ройрпЗ роЕро┤роХрпБ. роЗроЩрпНроХ роОройрпНройроЯро╛ройрпНройро╛ роОрокрпНрокрокрпНрокро╛ро░рпБ ро╡роЯроХрпНроХродрпНродро┐рокрпН рокрпКроорпНрокро│рпИ рооро╛родро┐ро░ро┐ ро╕ро▓рпНро╡ро╛ро░рпН роХроорпАро╕рпН. ро╡рпАроЯрпНро▓ рокро╛родро┐ роирпЗро░роорпБроорпН роирпИроЯрпНроЯро┐ родро╛ройрпН. роЕродрпИ роирпИроЯрпНроЯро┐ роЗро▓рпНро▓, роЯрпЗроЯрпНроЯро┐ройрпНройрпБ родро╛ройрпН роЪрпКро▓рпНро▓рогрпБроорпНтАЭ

тАЬроироорпНрок роЪрпАройрпБро╡рпИ рокрпЗро░рпН роЪрпКро▓рпНро▓ро┐родрпНродро╛ройрпН роХрпВрокрпНрокро┐роЯро▒ро╛ рокрпЛро▓. ро╡рпЗро▓рпИроХрпНроХрпБ ро╡рпЗро▒ рокрпЛро▒ро╛ро│рпЛройрпНройрпЛтАЭ

тАЬроОродрпБроХрпНроХрпЖроЯрпБродрпНродро╛ро▓рпБроорпН роЗродрпБ роТро░рпБ роЪро╛роХрпНроХрпБ. родро▓рпИро╡ро╛ро░ро┐рокрпН рокро┐ройрпНройро┐роХрпНроХроЪрпН роЪрпКройрпНройро╛, роирпЗро░рооро┐ро▓рпНро▓рпИропро╛роорпН. рокрпЛройро┐ роЯрпЖропрпНро▓рпНройрпБ роТро░рпБ роХрпНро│ро┐рокрпН рооро╛роЯрпНроЯро┐роХрпНроХро┐ро▒родрпБ. ро╡ро┐родро╡ро┐родрооро╛ роЬро┐рооро┐роХрпНроХро┐, роЯрпНро░ро╛рокрпНро╕рпНройрпБ рооро╛роЯрпНроЯро┐роХрпНроХ роороЯрпНроЯрпБроорпН роирпЗро░рооро┐ро░рпБроХрпНроХрпБ.тАЭ

тАЬро╣рпБроорпНтАЭ

тАЬроЙроЩрпНроХро│рпБроХрпНроХрпБ родрпЖро░ро┐ропрпБрооро╛, роорпБроЯро┐ропрпИ роЕроЯро┐роХрпНроХроЯро┐ ро╡рпЖроЯрпНроЯро┐ ро╡ро┐роЯрпНроЯрпБроХрпНроХро▒ро╛. роиро░рпИроХрпНроХродрпН родрпКроЯроЩрпНроХро┐ропро╛роЪрпНроЪрпБ. ро╡рпЖро│ро┐ро▓ родрпЖро░ро┐ропро╛роо роЪро╛ропроорпН рокрпВроЪро┐роХрпНроХро┐ро▒ро╛.тАЭ

тАЬроЗроирпНрод роЯро┐ро╡ро┐ройрпНройрпБ роТройрпНро▒рпБ ро╡рпАроЯрпНроЯрпБроХрпНроХрпБро│рпНро│ ро╡роирпНродро╛ро▓рпБроорпН ро╡роирпНродродрпБ. роЪро░рпНро╡роиро╛роЪроорпНтАЭ

тАЬроОро▓рпНро▓ро╛роорпН роОроЩрпНроХрпЗ рокрпЛропрпН роорпБроЯро┐ропрокрпН рокрпЛроХро┐ро▒родрпЛ, роИро╕рпНро╡ро░ро╛...тАЭ

тАЬроХро▓ро┐роХро╛ро▓роорпН роХро▓ро┐роХро╛ро▓роорпНтАжтАЭ


*** роЗройрпНро▒рпБ

тАЬроХро▓ро┐ роорпБродрпНродро┐рокрпН рокрпЛроЪрпНроЪрпБ ро░рооро╛тАЭ

тАЬроОройрпНрой роЪрпАройрпБ?тАЭ

тАЬроироорпНрок ро╡рпАроЯрпНроЯрпИропрпЗ рокро╛ро░рпБ. роЗроирпНрод роЕрокро┐ роХрпКроЮрпНроЪрооро╛ро╡родрпБ роТро┤рпБроЩрпНроХро╛ роЗро░рпБроХрпНроХро╛ройро╛? ро╡ро╛ро░роХрпНроХрогроХрпНроХрпБро▓ родрпЛропрпНроХрпНроХро╛род роЬрпАройрпНро╕рпБроорпН, ро╡рпЖро│ро▒ро┐рой роТро░рпБ роЯрпАро╖ро░рпНроЯрпНроЯрпБроорпН, роЕро╡ройрпН родро╛роЯро┐ропрпБроорпНтАж  роиро▓рпНро▓ро╛ро╡ро╛ роЗро░рпБроХрпНроХрпБ?тАЭ

тАЬроТро┤рпБроЩрпНроХро╛ рокрпЗрогрпНроЯрпН роЪро░рпНроЯрпН роЕропро░рпНройрпН рокрогрпНрогро┐ рокрпЛроЯрпНроЯроХрпНроХроХрпНроХрпВроЯро╛родрпЛ?тАЭ

тАЬроЗройрпНройро┐роХрпНроХрпБ ро╣рпЗро░рпНроХроЯрпН рокрогрпНрогро┐роЯрпНроЯрпБ ро╡роирпНродро┐ро░рпБроХрпНроХро╛ройрпН рокро╛ро░рпНродрпНродро┐ропро╛? роОройрпНройро╡рпЛ роЕрогрпНроЯро░рпНроХроЯрпНроЯро╛роорпН. роОро▓ро┐ ро╡роирпНродрпБ роХро▒рпБро╡ро┐роЯрпНроЯрпБрокрпН рокрпЛрой рооро╛родро┐ро░ро┐ роЗро░рпБроХрпНроХрпБ.тАЭ

тАЬроЕройрпБро╡рпБроорпН роЗродрпЗродро╛ройрпЗ. роорпБроЯро┐ройрпНройро╛ роХро▒рпБрокрпНрокро╛родрпНродро╛ройрпЗ роЗро░рпБроХрпНроХрогрпБроорпН? роЪрпБро╡ро▒рпНро▒рпБроХрпНроХрпБ роЕроЯро┐роХрпНроХро┐ро▒ рокрпЖропро┐рогрпНроЯрпН рооро╛родро┐ро░ро┐ родро▓рпИропро┐ро▓ропрпБроорпН роЕроЯро┐роЪрпНроЪрпБ, ро▓рпВро╕рпН ро╣рпЗро░рпНройрпБ роорпБроЯро┐ропрпИ ро╡ро┐ро░ро┐роЪрпНроЪрпБрокрпН рокрпЛроЯрпНроЯрпБрогрпНроЯрпБ ро╡роирпНродрпБ роиро┐роХрпНроХро▒ро╛. роЪро╛рокрпНрокро┐роЯрпБроорпНрокрпЛродрпБ родро┐роХрпНроХрпБ родро┐роХрпНроХрпБройрпНройрпБ  роЗро░рпБроХрпНроХрпБ. роЬрпЖро▓рпН рокрпЛроЯрпНроЯро┐ро░рпБроХрпНроХрпЗройрпН, роорпБроЯро┐ропрпЖро▓рпНро▓ро╛роорпН роЙродро┐ро░ро╛родрпБройрпНройрпБ ро╡ро┐ро│роХрпНроХроорпН ро╡рпЗро▒.тАЭ

тАЬроЯрпНро░ро╕рпН роЕродрпБроХрпНроХрпБроорпН роорпЗро▓. роОрокрпНрок рокро╛ро░рпБ роЖроорпНрокро│ рооро╛родро┐ро░ро┐ роТро░рпБ ро╖ро╛ро░рпНроЯрпНро╕рпН, ро╖ро░рпНроЯрпН. роХро╛родрпБро▓ роХрпИро▓ роХро┤рпБродрпНродрпБро▓ройрпНройрпБ роОродрпБро╡рпБроорпН роХро┐роЯрпИропро╛родрпБ. ро▓рпЖройрпНро╕ ро╡роЪрпНроЪрпБ роЙро▒рпНро▒рпБрокрпН рокро╛ро░рпНродрпНродро╛роХрпНроХрпВроЯ родрпЖро░ро┐ропро╛род роТро░рпБ роЪро┐ройрпНройрпНрой рокрпКроЯрпНроЯрпБ.тАЭ

тАЬроХрпИро▓ роЯро╛роЯрпНроЯрпВройрпНройрпБ роТро░рпБ рокроЯроорпН рокроЪрпНроЪрпИроХрпН роХрпБродрпНродро┐рой рооро╛родро┐ро░ро┐тАЭ

тАЬрооро░ро┐ропро╛родрпИройрпНро▒родрпБ роХроЯрпБроХро│ро╡рпБроорпН роЗро▓рпНро▓ро┐ропрпЗ. роироорпНрок роЕрокро┐ропрпИ ро╡ро╛роЯро╛ рокрпЛроЯро╛ройрпНройрпБродро╛ройрпН рокрпЗроЪро▒ро╛. роОро▓рпНро▓ро╛роорпН роЙро░рпБрокрпНрокроЯрпНроЯро╛ рооро╛родро┐ро░ро┐ родро╛ройрпНтАЭ

тАЬроОро▓рпНро▓ро╛ ро╡рпЗро▓рпИроХрпНроХрпБроорпН роорпЖро╖ро┐ройрпН. роЙроЯроорпНрокрпБ роКродро╛роо роОройрпНрой роЖроХрпБроорпН? роЕрокрпНрокрпБро▒роорпН роЕродрпБроХрпНроХрпБройрпНройрпБ родройро┐ропро╛ ро╡ро╛роХрпНроХро┐роЩрпН, роЬро┐роорпНройрпБ..тАЭ

тАЬроОроЩрпНроХро░рпБроирпНродрпБ родро╛ройрпН роХродрпНродрпБроХрпНроХро▒ро╛роЩрпНроХро│рпЛ..тАЭ

тАЬроХрпИро▓ роЪрпЖро▓рпНроГрокрпЛройрпН, роороЯро┐ро▓ ро▓ро╛рокрпНроЯро╛рокрпН. роиро┐рооро┐ро░рпНроирпНродрпБ рокро╛ро░рпНродрпНродро╛родрпНродро╛ройрпЗ. роЗроирпНрод роЗройрпНроЯро░рпНроирпЖроЯрпН ро╡роирпНродро╛ро▓рпБроорпН ро╡роирпНродродрпБ. роЪроХро▓роорпБроорпН роЪро░рпНро╡роиро╛роЪроорпНтАЭ

тАЬроЖрооро╛, роЪрпБропрооро╛ ропрпЛроЪро┐роХрпНроХро╛роо, роОродрпБроХрпНроХрпЖроЯрпБродрпНродро╛ро▓рпБроорпН роЕроирпНрод роХрпВроХро┐ро│рпНро▓ родро╛рой родрпЗроЯро▒родрпБроХро│рпНтАЭ

тАЬро░ро╛рооро╛тАж роОроЩрпНроХ рокрпЛропрпН роиро┐ро▒рпНроХрокрпН рокрпЛро▒родрпБроХро│рпЛ..тАЭ

тАЬроХро▓ро┐роХро╛ро▓роорпН роХро▓ро┐роХро╛ро▓роорпНтАжтАЭ

*** роиро╛ро│рпИ

"роХро▓ро┐ роорпБродрпНродро┐рокрпН рокрпЛроЪрпНроЪрпБ роЕройрпБ  "

"роПройрпНроЯро╛ роЕрокрпА?"

"рокро┐ройрпНройрпЗ роОройрпНрой? роироорпНрок ро╢рпНро░рпА роЗройрпНройро┐роХрпНроХрпБ роЖроГрокрпАроЪрпБроХрпНроХрпБ ро╡рпЗро╖рпНроЯро┐ропрпЛроЯ ро╡роирпНродрпБ роиро┐роХрпНроХро▒ро╛ройрпН. рооро╛ройроорпН рокрпЛроЪрпНроЪрпБ роОройроХрпНроХрпБ.тАЭ

тАЬроРропрпИропрпЛтАЭ

тАЬроЗродрпБ роороЯрпНроЯрпБрооро╛, рокро╛роХро╡родро░рпН ро╕рпНроЯрпИро▓рпНройрпБ роЬроЯрпИ ро╡ро│ро░рпНродрпНродрпБтАж роЕрокрпНрокрокрпНрок роХрпБроЯрпБрооро┐роХрпНроХроЯрпНроЯрпБ ро╡рпЗро▒. роХро╛родрпБро▓ роТро░рпБ ро╕рпНроЯроЯрпН. роЪрпЖропро┐ройрпНро▓ роЯрпИроХро░рпН роирпЖропрпНро▓рпН рооро╛родро┐ро░ро┐ роЯро╛ро▓ро░рпН. роОройрпНройроЯро┐ роХрпЛро▓роорпН роЗродрпБ?тАЭ

тАЬроОро▓рпНро▓ро╛роорпН роЕро╡ройрпН ро╡рпКропрпНроГрокрпН ро╡рпЗро▓рпИроЯро╛. роЕро╡ро│рпБроХрпНроХрпБроорпН роЯрпАро╕рогрпНроЯро╛ роЬрпАройрпНро╕рпН, ро╖ро╛ро░рпНроЯрпНро╕рпН, ро╖ро░рпНроЯрпНро╕рпНройрпБ роОро╡рпНро╡ро│ро╡рпЛ роЗро░рпБроХрпНроХрпБ. родрпЗроЯро┐родрпНродрпЗроЯро┐ роороЯро┐роЪро╛ро░рпНройрпБ  роТро░рпБ роЯроЬройрпН ро╡ро╛роЩрпНроХро┐роЯрпНроЯрпБ ро╡роирпНродро┐ро░рпБроХрпНроХро╛. роирпАро│ роирпАро│рооро╛. роОрокрпНрокроЯро┐родрпНродро╛ройрпН роХроЯрпНроЯро┐рогрпНроЯро╛ро│рпЛ, рокро╛ро░рпНродрпНродро╛ро▓рпЗ родро▓рпИ роЪрпБродрпНродрпБродрпБ. роХрпЗроЯрпНроЯро╛ роЗродрпБро▓родро╛ройрпН тАШроГрокрпЖрооро┐ройрпИройрпН ро▓рпБроХрпНтАЩ роЗро░рпБроХрпНроХрпБройрпНройрпБ роЪрпКро▓рпНро▒ро╛.тАЭ

тАЬро╕ро┐роорпНрокрпНро▓ро┐ ро╡рпЗро╕рпНроЯро┐роЩрпН роЯрпИроорпН роЕрогрпНроЯрпН роОройро░рпНроЬро┐.тАЭ

тАЬроЕроирпНродродрпН родро▓рпИ роорпБроЯро┐роп роТро┤рпБроЩрпНроХро╛ роХрпНро░ро╛рокрпН рокрогрпНрогро┐ роЯрпНро░ро┐роорпНрооро╛ роЗро░рпБроХрпНроХ ро╡рпЗрогрпНроЯро╛рооро╛? роОройрпНройро╡рпЖро▓рпНро▓ро╛роорпЛ родроЯро╡ро┐, роорпБроЯро┐ропрпИрокрпН рокрпЛропрпН роорпБроЯрпНроЯро┐ ро╡ро░рпИроХрпНроХрпБроорпН ро╡ро│ро░рпНродрпНродрпБ ро╡роЪрпНроЪро┐ро░рпБроХрпНроХро╛. родро┐ройроорпН роЕрод ро╡ро╛ро░ро┐, ро╡ро┐родро╡ро┐родрооро╛ рокро┐ройрпНройро┐, роЕродрпБро▓ рокрпВ ро╡рпЗро▒ ро╡роЪрпНроЪрпБ тАж. роЕродро┐ро▓рпНро▓рпИройрпНройро╛ роЪрпЗро░рпНродрпНродрпБ рокро┐роЯро┐родрпНродрпБ роОройрпНройро╡рпЛ рокрогрпНрогро┐ роХрпКрогрпНроЯрпИ, роХрпЛроЯро╛ро▓ро┐ роорпБроЯро┐роЪрпНроЪрпБройрпНройрпБ... роорпБроХродрпНродрпБро▓ роЗро╡рпНро╡ро│ро╡рпБ роороЮрпНроЪро│рпИ роЕрокрпНрокро┐рогрпНроЯрпБ.. роЗродрпБроХрпНроХрпБройрпНройрпБ роПродрпЗродрпЛ роорпВро▓ро┐роХрпИропрпЖро▓рпНро▓ро╛роорпН родрпЛроЯрпНроЯродрпНродрпБро▓ ро╡ро│ро░рпНродрпНродрпБ ро╡роЪрпНроЪро┐ро░рпБроХрпНроХро╛. рокро╛ро░рпНродрпНродрпЗройрпНтАЭ

тАЬроЖро░рпНроХро╛ройро┐роХрпН ро╣рпЖро░рпНрокрпНро╕рпН..тАЭ

тАЬроиро╛ройрпН ропрпВро╕рпН рокрогрпНро▒родрпБ роОро▓рпНро▓ро╛роорпН роХрпЖрооро┐роХрпНроХро▓ро╛роорпН. роЗродрпБ роороЯрпНроЯрпБрооро╛, роХро╛родрпБро▓ роорпВроХрпНроХрпБро▓ роОро▓рпНро▓ро╛роорпН роУроЯрпНроЯрпИ рокрпЛроЯрпНроЯрпБтАж роЕродрпБроХрпНроХрпБ родройро┐ропро╛ родроЩрпНроХроорпН, ро╡рпИро░роорпНройрпБ роОроХрпНро╕рпНроЯрпНро░ро╛ роГрокро┐роЯрпНроЯро┐роЩрпН. ро╖ро┐роЯрпНтАЭ

тАЬроЗродрпЖро▓рпНро▓ро╛роорпН ро╡ро┐роЯрпБ. роХрпБро┤роирпНродрпИропрпИ роЕро┤роХро╛ ро╡ро┐ро╖рпНройрпБ роХрпВрокрпНрокро┐роЯроХрпН роХрпВроЯро╛родро╛роорпН. ро╡ро┐ро╕рпНро╡роиро╛родройрпНройрпБ роТро╡рпНро╡рпКро░рпБ родроЯро╡рпИропрпБроорпН роЗро┤рпБродрпНродро╛родрпНродро╛ройрпН рокрпЗро░рпЛроЯ роорпАройро┐роЩрпН рокрпБро░ро┐ропрпБрооро╛роорпН. роЯроЩрпН ро╕рпНро▓ро┐рокрпН роЖроХро┐роЯрпБродрпБ.тАЭ

тАЬро╣рпНроорпН. роЗройрпНройрпБроорпН роОройрпНройрпЖройрпНрой рокро╛роХрпНроХро┐ роЗро░рпБроХрпНроХрпЛ? роХро╛роЯрпН роТройрпНро▓ро┐ роирпЛро╕рпНтАЭ

тАЬроХро▓ро┐роХро╛ро▓роорпН роХро▓ро┐роХро╛ро▓роорпНтАжтАЭ
** DONE роЗрокрпНрокроЯро┐роХрпНроХрпБ ро░ро╛роорпБ :роЪро┐ро▒рпБроХродрпИ:
CLOSED: [2021-06-06 Sun 20:16]
:PROPERTIES:
:EXPORT_FILE_NAME: ippadikku-ramu
:END:
 6/1994

   роТро░рпБ рокрпКройрпНрооро╛ро▓рпИрокрпН рокрпКро┤рпБродро┐ро▓рпН ро░ро╛роорпБро╡ро╛роХро┐роп роиро╛ройрпН роЗроирпНрод роЙро▓роХродрпНродрпИ роОроЯрпНроЯро┐рокрпН рокро╛ро░рпНродрпНродродрпБроорпН роорпБродро▓ро┐ро▓рпН роХрпЗроЯрпНроЯродрпБ, тАЬроиро▓рпНро▓ ро╡рпЗро│рпИ роЖрогрпНрокро┐ро│рпНро│рпИ. ро░роЩрпНроХройрпБроХрпНроХрпБ роЗройро┐ роХро╡ро▓рпИропро┐ро▓рпНро▓рпИ. роороХройрпН роЪроорпНрокро╛ро░ро┐роЪрпНроЪрпБрокрпН рокрпЛроЯрпНроЯрпБроЯрпБро╡ро╛ройрпНтАЭ

   \\

 6/1999

   ро╕рпНроХрпВро▓рпБроХрпНроХрпБрокрпН рокрпЛроХродрпН родрпКроЯроЩрпНроХро┐ропро┐ро░рпБроХрпНроХрпЗройрпН. роорпБродро▓рпНро▓ рокропрооро╛роХ, роЪроЩрпНроХроЯрооро╛роХ роЗро░рпБроирпНродро╛ро▓рпБроорпН роЗрокрпНрокрпЛ роЬро╛ро▓ро┐ропро╛родрпНродро╛ройрпН роЗро░рпБроХрпНроХрпБ. роОрокрпНрокро╡рпБроорпН ро╡ро┐ро│рпИропро╛роЯрпНроЯрпБродрпНродро╛ройрпН. роТро░рпБ рооро╛ро╕рпНроЯро░рпБроорпН роТро░рпБ роЯрпАроЪрпНроЪро░рпБроорпН роЗро░рпБроХрпНроХро╛роЩрпНроХ. рооро╛ро╕рпНроЯро░рпН роТройрпНро▒ро╛роорпН родрпЗродро┐ роороЯрпНроЯрпБроорпН ро╡ро░рпБро╡ро╛ро░рпН. роЯрпАроЪрпНроЪро░рпН роЕрокрпНрокрокрпНрокрпЛ ро╡роирпНродрпБроЯрпНроЯрпБ роЙроЯройрпЗ роХро┐ро│роорпНрокро┐роЯрпБро╡ро╛роЩрпНроХ. ро░рпЖрогрпНроЯрпБ рокрпЗро░рпБроорпН роПродрпЛ ро╡роЯрпНроЯро┐ ро╡ро┐ропро╛рокро╛ро░роорпН рокрогрпНро▒родро╛ рокроЪроЩрпНроХ роЪрпКро▓рпНро▒ро╛роЩрпНроХ.

   \\

6/2004

   роЕрокрпНрокро╛ро╡рпБроХрпНроХрпБ роЯро┐ро░ро╛ройрпНро╕рпНрокро░рпН роЖроХро┐ропро┐ро░рпБроХрпНроХрпБ. роЗродрпБ роХрпКроЮрпНроЪроорпН рокрпЖро░ро┐роп роКро░рпН. роТро░рпБ роорпЖроЯрпНро░ро┐роХрпБро▓рпЗро╖ройрпН ро╕рпНроХрпВро▓рпНро▓ роЖро▒ро╛роорпН ро╡роХрпБрокрпНрокрпБ роЪрпЗро░рпНроирпНродро┐ро░рпБроХрпНроХрпЗройрпН. рокрпБродрпБ ро╕рпНроХрпВро▓рпН, рокрпБродрпБ ропрпВройро┐роГрокро╛ро░рпНроорпН, рокрпБродрпБ рокрпЗроХрпН роЪрпВрокрпНрокро░ро╛родрпНродро╛ройрпН роЗро░рпБроХрпНроХрпБ. ро░ро┐роХрпНтАМро╖ро╛ро▓ родро╛ройрпН роЗроЯроорпН рокродрпНродро▓. ро░рпКроорпНрок роирпЖро░рпБроХрпНроХроЯро┐. рокро▓ роЪрооропроЩрпНроХро│ро┐ро▓рпН рокропрооро╛ роЗро░рпБроХрпНроХрпБроорпН.

   роЖройро╛ роЕроорпНрооро╛ роПройрпН роЗрокрпНрокроЯро┐ роХро╡ро▓рпИропрпЛроЯ роЗро░рпБроХрпНроХро╛роЩрпНроХройрпНройрпБ рокрпБро░ро┐ропро▓. "роПроЩрпНроХ, ро░ро╛роорпБро╡ роЗрокрпНрок роЗрокрпНрокроЯро┐ рокро┐ро░рпИро╡рпЗроЯрпН ро╕рпНроХрпВро▓рпНро▓ роХрпКрогрпНроЯрпБ роЪрпЗро░рпНродрпНродро┐ро░рпБроХрпНроХрпАроЩрпНроХро│рпЗ. роироороХрпНроХрпБ роХроЯрпНроЯрпБрокрпНрокроЯро┐ропро╛роХрпБрооро╛"ройрпНройрпБ рокрпБро▓роорпНрокро▒ро╛роЩрпНроХ.

   "роПрогрпНроЯро┐, роиро╛ройрпН родро╛ройрпН роиро▓рпНро▓ро╛ рокроЯро┐роХрпНроХро╛роо рокро┐ропрпВройро╛ро╡рпЗ роЗро░рпБроХрпНроХрпЗройрпН. роЗро╡ройрпИропро╛ро╡родрпБ роиро▓рпНро▓ро╛ рокроЯро┐роХрпНроХ ро╡роЪрпНроЪрпБ роЯро╛роХрпНроЯро░рпЛ, роЗройрпНроЬро┐ройро┐ропро░рпЛ роЖроХрпНроХ ро╡рпЗрогрпНроЯро╛рооро╛? роХрпКроЮрпНроЪроорпН роЪро┐ро░роорокрпН рокроЯрпНроЯро╛ро╡родрпБ роГрокрпАро╕рпН роХроЯрпНроЯро┐роЯро▓ро╛роорпН. роХро╡ро▓рпИрокрпНрокроЯро╛родрпЗ. рокрпЖро░ро┐ропро╡ройро╛ройродрпБроорпН роЕро╡ройрпН роироорпНрооро│ родроЩрпНроХродрпН родро╛роорпНрокро╛ро│родрпНродрпБро▓ ро╡роЪрпНроЪрпБ родро╛роЩрпНроХрокрпН рокрпЛро▒ро╛ройрпН рокро╛ро░рпБ"

   роЖройро╛ роХрпКроЮрпНроЪ роиро╛ро│ро╛ роОройроХрпНроХрпБ роЗроирпНрод ро╕рпНроХрпВро▓рпН рокро┐роЯро┐роХрпНроХро▓. роПрокро┐роЪро┐роЯро┐, роЖройро╛ роЖро╡ройрпНройро╛ роХрпВроЯ роТро┤рпБроЩрпНроХро╛ роОро┤рпБродродрпН родрпЖро░ро┐ропро▓рпИройрпНройрпБ рокроЪроЩрпНроХро│рпБроорпН рооро┐ро╕рпНро╕рпБроорпН ро░рпКроорпНрок роХрпЗро▓ро┐ рокрогрпНро▒ро╛роЩрпНроХ. роГрокрпЖропро┐ро▓ро╛ропро┐роЯрпБро╡рпЗройрпНройрпБ   рокропроорпБро▒рпБродрпНродро▒ро╛роЩрпНроХ.  рокро┤рпИроп ро╕рпНроХрпВро▓рпНро▓ рокро┐ро░роЪрпНроЪройрпИропрпЗ роХро┐роЯрпИропро╛родрпБ. роЪрпБроорпНрооро╛ ро╕рпНроХрпВро▓рпБроХрпНроХрпБ рокрпЛройро╛ро▓рпЗ 'роЖро▓рпНрокро╛ро╕рпН' родро╛ройрпН.

   \\

6/2006

   роЗроирпНрод ро╡ро░рпБро╖родрпНродро┐ро▓ро┐ро░рпБроирпНродрпБ ропрпВройро┐роГрокро╛ро░рпНроорпН роГрокрпБро▓рпН рокрпЗрогрпНроЯрпН, роГрокрпБро▓рпН ро╖ро░рпНроЯрпН. роОроЯрпНроЯро╛ро╡родрпБ ро╡роирпНродро╛роЪрпНроЪрпБ роЗро▓рпНро▓ро┐ропро╛?

   роХро┐ро│ро╛ро╕рпНро▓ роХрпЗро░рпНро│рпНро╕рпН роОро▓рпНро▓ро╛роорпН роХро┐роЯрпБроХро┐роЯрпБройрпНройрпБ ро╡ро│ро░рпНроирпНродрпБроЯрпНроЯро┐ро░рпБроХрпНроХро╛роЩрпНроХ. рокроЪроЩрпНроХро│рпБроХрпНроХрпБроорпН роиро┐ро▒рпИроп рокрпЗро░рпБроХрпНроХрпБ роорпАроЪрпИ ро╡роирпНродрпБроЯрпНроЯро┐ро░рпБроХрпНроХрпБ. роОройроХрпНроХрпБ роороЯрпНроЯрпБроорпН ро╡ро░ро▓ро┐ропрпЗ. роорпАроЪрпИ ро╡ро│ро░ роОройрпНрой роЪрпЖропрпНропрогрпБроорпН? ропро╛ро░рпНроХро┐роЯрпНроЯ роХрпЗроЯрпНрокродрпБ? роХрпВроЪрпНроЪрооро╛ роЗро░рпБроХрпНроХрпБ. роХро┐рогрпНроЯро▓роЯро┐рокрпНрокро╛роЩрпНроХро│рпЛ? родроЩрпНроХроЪрпНроЪро┐ропрпЛроЯ роХрогрпНроорпИропро╛ро▓ ро▓рпЗроЪро╛ ро╡ро░рпИроЮрпНроЪрпБрокрпН рокро╛ро░рпНродрпНродрпЗройрпН. роЪрпЛро│роХрпН роХрпКро▓рпНро▓рпИ рокрпКроорпНроорпИ рооро╛родро┐ро░ро┐ роЗро░рпБроирпНродродрпБ. родрогрпНрогрпАро░рпН ро╡ро┐роЯрпНроЯрпБ роЕро┤ро┐роЪрпНроЪродрпБро▓ роЗройрпНройрпБроорпН роЕроЪро┐роЩрпНроХрооро╛ рокро░ро╡ро┐роЯрпБроЪрпНроЪрпБ. роорпБроХродрпНродрпИ роорпВроЯро┐роХрпНроХро┐роЯрпНроЯрпБ рокроЯрпБродрпНродрпБроЯрпНроЯрпЗройрпН.

   \\



6/2007

   роТройрпНрокродро╛роорпН ро╡роХрпБрокрпНрокрпБ рокрпБроХрпНро╕рпН ро╡ро╛роЩрпНроХродрпН родрпЗро╡рпИропро┐ро▓рпНро▓рпИ. роЯрпЖройрпНродрпН рокрпЛро░рпНро╖ройрпИ роЗрокрпНрокро╡рпЗ родрпКроЯроЩрпНроХро┐ропро╛роЪрпНроЪрпБ. рокрпБро░ро┐ропро╡рпЗ рооро╛роЯрпНроЯрпЗроЩрпНроХрпБродрпБ. роХрпЗроЯрпНроЯро╛ роЕроЯро┐роХрпНроХро┐ро▒ро╛роЩрпНроХ. роЯро┐ропрпВро╖ройрпН ро╡роЪрпНроЪро╛ роиро▓рпНро▓родрпБройрпНройрпБ ро╕рпНроХрпВро▓рпНро▓ роЪрпКро▓рпНро▓, рооро┐ро╕рпНроХро┐роЯрпНроЯропрпЗ роЯро┐ропрпВро╖ройрпБроХрпНроХрпБ роЪрпЗро░рпНроирпНродро┐ро░рпБроХрпНроХрпЗройрпН.

   ро╕рпНроХрпВро▓рпН рооро╛родро┐ро░ро┐ропрпЗ родро╛ройрпН роЗроЩрпНроХрпЗропрпБроорпН рооро┐ро╕рпН роЪрпКро▓рпНро▓ро┐родрпН родро░рпНро▒ро╛роЩрпНроХ. ро╕рпНроХрпВро▓рпНро▓ропро╛ро╡родрпБ роиро╛ро▒рпНрокродрпБ рокрпЗро░рпН родро╛ройрпН. роЗроЩрпНроХрпЗ роРроорпНрокродрпНродрпИроирпНродрпБ рокрпЗро░рпН. роЪрпБродрпНрод рокрпЛро░рпН.

   ро░ро╛родрпНродро┐ро░ро┐ роЖропро┐роЯрпНроЯро╛ роЬро╛ро▓ро┐родро╛ройрпН. роОройрпНройрпИропрпБроорпН родроЩрпНроХроЪрпНроЪро┐ропрпИропрпБроорпН рокроЯро┐роХрпНроХроЪрпН роЪрпКро▓рпНро▓ро┐роЯрпНроЯрпБ роЕроорпНрооро╛, роЕрокрпНрокро╛ роЯрпАро╡ро┐ роЪрпАро░ро┐ропро▓рпНро▓ роорпВро┤рпНроХро┐роЯрпБро╡ро╛роЩрпНроХ. ро╣рпЛроорпНро╡ро░рпНроХрпН рокрогрпНро▒ рооро╛родро┐ро░ро┐ роУро░рооро╛ роЙроЯрпНроХро╛ро░рпНроирпНродрпБ роиро╛ройрпБроорпН рокро╛ро░рпНродрпНродрпБроЯрпНроЯро┐ро░рпБрокрпНрокрпЗройрпН. ро╡ро┐ро│роорпНрокро░роорпН ро╡ро░рпНро▒рокрпНрок роороЯрпНроЯрпБроорпН родро▓рпИроп рокрпБроХрпНро╕рпНро▓ рокрпБродрпИроЪрпНроЪрпБроЯрпБро╡рпЗройрпН. родроЩрпНроХроЪрпНроЪро┐ропрпБроорпН роЕрокрпНрокроЯро┐родрпНродро╛ройрпН. роЖройро╛ роТро░рпБродрпНродро░рпИропрпКро░рпБродрпНродро░рпН роХро╛роЯрпНроЯро┐роХрпН роХрпКроЯрпБроХрпНроХ рооро╛роЯрпНроЯрпЛроорпН. роЯрпАро╡ро┐ро▓ роЪро┐ройро┐рооро╛, роЪрпАро░ро┐ропро▓рпН роОро▓рпНро▓ро╛роорпЗ роиро▓рпНро▓ро╛ роЗро░рпБроХрпНроХрпБроорпН. роиро╛ро│рпИ роОройрпНрой ро╡ро░рпБроорпЛройрпНройрпБ ро╡ро┐ро▒рпБро╡ро┐ро▒рпБрокрпНрокро╛роХ роЗро░рпБроХрпНроХрпБроорпН.

   \\



6 / 2008

   рокродрпНродро╛роорпН ро╡роХрпБрокрпНрокрпБ роЗро▓рпНро▓рпИропро╛? рокрпКродрпБродрпНродрпЗро░рпНро╡рпБ роОро┤рпБродрогрпБроорпН. рокроЯро┐рокрпНрокрпБ рокроЯро┐рокрпНрокрпБ рокроЯро┐рокрпНрокрпБродро╛ройрпН. роЪро░ро┐ропро╛ роХрпБро│ро┐роХрпНроХ, роЪро╛рокрпНрокро┐роЯ, роПройрпН рокро╛родрпНро░рпВроорпН рокрпЛроХроХрпНроХрпВроЯ роирпЗро░рооро┐ро▓рпНро▓рпИ. родро┐ройроорпН роХро╛ро▓рпИропро┐ро▓ роЯро┐ропрпВро╖ройрпН, ро╕рпНроХрпВро▓рпН, роОроХрпНро╕рпНроЯрпНро░ро╛ роХро┐ро│ро╛ро╕рпН, рооро▒рпБрокроЯро┐ роЯро┐ропрпВро╖ройрпН, ро╣рпЛроорпН ро╡рпКро░рпНроХрпН... роХрогрпНрогрпИ роорпВроЯро┐ройро╛ рокрпВроЪрпНроЪро┐ рокро▒роХрпНроХро┐ро▒ рооро╛родро┐ро░ро┐ роЗро░рпБроХрпНроХрпБ. ро░рпКроорпНрок  роЕроЪродро┐ропро╛ роЗро░рпБроХрпНроХрпБ. рокро╛роЯроЩрпНроХро│рпИ рокрпБро░ро┐роЮрпНроЪро┐роХрпНроХро╡рпЗ роирпЗро░рооро┐ро▓рпНро▓рпИ. роирпЖроЯрпНроЯрпБро░рпБ рокрпЛроЯрпНроЯро╛ро▓рпБроорпН рооро▒рпБроиро╛ро│рпН рооро▒роирпНродрпБроЯрпБродрпБ. родрпВроХрпНроХроорпЗ ро╡ро░рооро╛роЯрпНроЯрпЗроЩрпНроХрпБродрпБ..

   рооро╛роЯро▓рпН роЯрпЖро╕рпНроЯрпНро▓ ро╡ро░рпБрогрпН роиро▓рпНро▓ рооро╛ро░рпНроХрпН ро╡ро╛роЩрпНроХро┐ропро┐ро░рпБроХрпНроХро╛ройрпН. роиро╛ройрпН ро╡ро┤роХрпНроХроорпН рокрпЛро▓ роЪро░ро╛роЪро░ро┐ родро╛ройрпН. роЕрокрпНрокро╛ родро┐роЯрпНроЯро▒ро╛ро░рпН. "роЕродрпЗ ро╕рпНроХрпВро▓рпНро▓ рокроЯро┐роЪрпНроЪ роЕро╡ройрпН роороЯрпНроЯрпБроорпН роиро▓рпНро▓ рооро╛ро░рпНроХрпН ро╡ро╛роЩрпНроХро▒ро╛ройрпЗ. роЙройроХрпНроХрпБ роОройрпНрой роХрпЗроЯрпБ?".. родрпЖро░ро┐ропро▓рпИропрпЗ

   \\

5 / 2009

  рокрпКродрпБродрпН родрпЗро░рпНро╡рпБродрпН 58% родро╛ройрпН. роЕроорпНрооро╛ро╡рпБроорпН роЕрокрпНрокро╛ро╡рпБроорпН роТро░рпБ ро╡ро╛ро░рооро╛ рокрпЗроЪро╡рпЗропро┐ро▓рпНро▓рпИ. роОройрпНройро╛ро▓рпН роЗро╡рпНро╡ро│ро╡рпБродро╛ройрпЗ роорпБроЯро┐роЮрпНроЪродрпБ??

  \\

6 / 2009

   рокро┤рпИроп ро╕рпНроХрпВро▓рпНро▓ роГрокро░рпНро╕рпНроЯрпН роХрпНро░рпВрокрпН роЗроЯроорпН роХро┐роЯрпИроХрпНроХро▓рпИ. роХрпКроЮрпНроЪроорпН родрпВро░родрпНродро┐ро▓ ро╡рпЗро▒ ро╕рпНроХрпВро▓рпНро▓ роЪрпЗро░рпНроирпНродро┐ро░рпБроХрпНроХрпЗройрпН. роЗродрпБ роХрпВроЯ роЕрокрпНрокро╛ рокро╛ро░рпНроЯрпН роГрокрпИройро▓рпН ро▓рпЛройрпН роПродрпЛ роОроЯрпБродрпНродрпБ роЯрпКройрпЗро╖ройрпН роХрпКроЯрпБродрпНродрпБродрпНродро╛ройрпН роХро┐роЯрпИродрпНродродрпБ. ро░рпЖрогрпНроЯрпБ рокрпЗро░рпН ро╕рпНроХрпВро▓рпН рокрпАро╕рпН,  ро╡ро╛роЯроХрпИ, роЗройрпНройрпБроорпН роиро┐ро▒рпИроп роЪрпЖро▓ро╡рпБроХро│рпНтАж роЕрокрпНрокро╛ родро┐рогро▒рпБро╡родрпИрокрпН рокро╛ро░рпНроХрпНроХ роХро╖рпНроЯрооро╛роХ роЗро░рпБроХрпНроХрпБ.

   ро╕рпНроХрпВро▓рпН родро┐ро▒роирпНродродрпБроорпЗ рокройрпНройро┐ро░рогрпНроЯро╛роорпН ро╡роХрпБрокрпНрокрпБ рокро╛роЯроорпН роЖро░роорпНрокро┐роЪрпНроЪро╛роЪрпНроЪрпБ. рокродро┐ройрпКройрпНро▒ро╛роорпН ро╡роХрпБрокрпНрокрпБ рокро╛роЯроЩрпНроХро│рпИ ро╡ро┐роЯрпНроЯрпБ ро╡ро┐роЯрпНроЯрпБ роЕроЯрпБродрпНрод ро╡ро░рпБроЯ рокро╛роЯроЩрпНроХро│рпИ роОроЯрпБроХрпНроХрпБроорпНрокрпЛродрпБ роТройрпНро▒рпБроорпЗ рокрпБро░ро┐ро╡родро┐ро▓рпНро▓рпИ роОройрпНрокродрпИ ропро╛ро░рпН родро╛ройрпН роОроЯрпБродрпНродрпБ роЪрпКро▓рпНро╡родрпБ? роорпАрогрпНроЯрпБроорпН роЯро┐ропрпВро╖ройрпН, ро╕рпНроХрпВро▓рпН, роЯро┐ропрпВро╖ройрпН, ро╕рпНроХрпВро▓рпНтАж.

   \\

3 / 2011

   роиро╛ро│рпИ рооро▒рпБроиро╛ро│рпН рокро┐ро│ро╕рпН роЯрпВ родрпЗро░рпНро╡рпБ. роирпЗро▒рпНро▒рпБ ро╣рпЖроЯрпН рооро╛ро╕рпНроЯро░рпН роЕрокрпНрокро╛ро╡рпИ роЕро┤рпИродрпНродрпБ рокрпЗроЪро┐ропро┐ро░рпБроХрпНроХро┐ро▒ро╛ро░рпН.

   "роЗроЩрпНроХрпЗ рокро╛ро░рпБроЩрпНроХ роЙроЩрпНроХ роороХройрпН роорпЗродрпНро╕рпН, роХрпЖрооро┐ро╕рпНроЯрпНро░ро┐ ро░рпЖрогрпНроЯрпБро▓ропрпБроорпН ро░рпКроорпНрок ро╡рпАроХрпНроХро╛ роЗро░рпБроХрпНроХро╛ройрпН. роЗро╡ройрпН роЗрокрпНрок роОроХрпНро╕ро╛роорпН роОро┤рпБродро┐ роОройрпНрой рокро┐ро░ропрпЛроЬройроорпН? рокро╛ро╕ро╛роХро┐ро▒родрпЗ рокрпЖро░ро┐роп ро╡ро┐ро╖ропроорпН. роЗродрпБро▓ роорпЗро▒рпНрокроЯро┐рокрпНрокрпБроХрпНроХрпБ роОроЩрпНроХ роЗроЯроорпН роХро┐роЯрпИроХрпНроХрокрпН рокрпЛроХрпБродрпБ?"

   роЕрокрпНрокро╛ роЕро┤родрпН родрпКроЯроЩрпНроХро┐ ро╡ро┐роЯрпНроЯро╛ро░рпН рокрпЛро▓рпБроорпН.

   "роЕро┤ро╛родрпАроЩрпНроХ роЙроЩрпНроХро│рпИрокрпН рокро╛ро░рпНродрпНродро╛ро▓рпБроорпН рокро╛ро╡рооро╛родрпНродро╛ройрпН роЗро░рпБроХрпНроХрпБ. ро╡рпЗрогрпНроЯрпБрооро╛ройро╛ро▓рпН роТро░рпЗ роТро░рпБ ро╡ро┤ро┐ роЗро░рпБроХрпНроХрпБ."

   "роОройрпНрой роЪро╛ро░рпН? роЪрпКро▓рпНро▓рпБроЩрпНроХ роЪро╛ро░рпН."

   "роОроХрпНро╕ро╛роорпН родрпКроЯроЩрпНроХро┐ рокродрпНродрпБ роиро┐рооро┐роЯродрпНродрпБроХрпНроХрпБро│рпНро│ роОро▓рпНро▓ро╛ роХрпЗро│рпНро╡ро┐роХро│рпБроХрпНроХрпБроорпН ро╡ро┐роЯрпИроХро│рпИ роТро░рпБ рокрпЗрокрпНрокро░ро┐ро▓рпН рокро┐ро░ро┐рогрпНроЯрпН роОроЯрпБродрпНродрпБ роЕро╡ройрпН роХрпИропро┐ро▓ роХро┐роЯрпИроХрпНроХ роПро▒рпНрокро╛роЯрпБ роЪрпЖропрпНроХро┐ро▒рпЗройрпН. роЖройро╛ро▓рпН роЕродрпБроХрпНроХрпБ роХрпКроЮрпНроЪроорпН роЪрпЖро▓ро╡ро╛роХрпБроорпН. рокро░ро╡ро╛ропро┐ро▓рпНро▓рпИропро╛?"

   "роОро╡рпНро╡ро│ро╡рпБ роЪро╛ро░рпН?"

   роЕро╡ро░рпН роЪрпКройрпНрой родрпКроХрпИропрпИ роХрпЗроЯрпНроЯрпБ роЕрокрпНрокро╛ рооро┐ро░ро│, "роЙроЩрпНроХро│ро╛ро▓рпН роорпБроЯро┐ропро╛родрпБройрпНройро╛ ро╡ро┐роЯрпНроЯрпБроЯрпБроЩрпНроХ" роОройрпНро▒ро╛ро░рпН.

   рооро▒рпБрокрпЗроЪрпНроЪро┐ройрпНро▒ро┐ роЕро╡ро░рпН роХрпЗроЯрпНроЯродрпИ роЕрокрпНрокро╛ роЗройрпНро▒рпБ роХрпКроЯрпБродрпНродро╛ропро┐ро▒рпНро▒рпБ. роОроЩрпНроХрпЗ роХроЯройрпН ро╡ро╛роЩрпНроХро┐ройро╛ро░рпЛ родрпЖро░ро┐ропро▓рпИ.

   \\

8 / 2011

   рокрпНро│ро╕рпН роЯрпВ роОроХрпНро╕ро╛роорпН 'роиройрпНро▒ро╛роХ' роОро┤рпБродро┐ропродро╛ро▓рпН ро░рпКроорпНрок роиро▓рпНро▓ роородро┐рокрпНрокрпЖрогрпН. роиро▓рпНро▓ ро░рпЗроЩрпНроХрпН. роХрпЗроЯрпНроЯ роХро╛ро▓рпЗроЬро┐ро▓ роХрпЗроЯрпНроЯ роХрпБро░рпВрокрпН роХро┐роЯрпИродрпНродрпБро╡ро┐роЯрпНроЯродрпБ. роХро╛ро▓рпЗроЬрпН роГрокрпАро╕рпН роХроЯрпНроЯ роЕрокрпНрокро╛ роХроирпНродрпБро╡роЯрпНроЯро┐роХрпНроХро╛ро░ройро┐роЯроорпН роХроЯройрпН ро╡ро╛роЩрпНроХро┐ропро┐ро░рпБроХрпНроХро┐ро▒ро╛ро░рпН рокрпЛро▓ро┐ро░рпБроХрпНроХрпБ. родрпЖро│ро┐ро╡ро╛ роЪрпКро▓рпНро▓ рооро╛роЯрпНроЯрпЗройрпНроХро┐ро▒ро╛ро░рпН.

   \\

10 / 2011

   рокро╛роЯроЩрпНроХро│рпН роОродрпБро╡рпБроорпН роЪрпБродрпНродрооро╛ рокро┐роЯро┐рокроЯ рооро╛роЯрпНроЯрпЗроЩрпНроХрпБродрпБ. родро┐ройроорпН роЯрпЖро╕рпНроЯрпН, роЕро╕рпИройрпНроорпЖройрпНроЯрпН, рокрпНро░ро╛роХрпНроЯро┐роХро▓рпНро╕рпНтАж ропро╛ро░ро┐роЯроорпБроорпН роЪроирпНродрпЗроХроорпН роХрпЗроЯрпНроХ ро╡рпЖроЯрпНроХрооро╛ роЗро░рпБроХрпНроХрпБ. 'роЗроирпНрод роЕроЯро┐рокрпНрокроЯрпИ роХрпВроЯро╡ро╛ родрпЖро░ро┐ропро╛родрпБ'ройрпНройрпБ роХро┐рогрпНроЯро▓рпН рокрогрпНро▒ро╛роЩрпНроХ.

   \\

1 / 2012

   роГрокро░рпНро╕рпНроЯрпН роЪрпЖрооро╕рпНроЯро░рпН ро░ро┐ро╕ро▓рпНроЯрпН ро╡роирпНродрпБ ро╡ро┐роЯрпНроЯродрпБ. роиро╛ройрпНроХро┐ро▓рпН роорпВройрпНро▒рпБ рокро╛роЯроЩрпНроХро│ро┐ро▓рпН роГрокрпЖропро┐ро▓рпН. роЕрокрпНрокро╛ро╡ро┐роЯроорпН роЪрпКро▓рпНро▓ родрпИро░ро┐ропрооро┐ро▓рпНро▓рпИ. роОрокрпНрокро╛роЯрпБ рокроЯрпНроЯро╛ро╡родрпБ роЕроЯрпБродрпНрод роорпБро▒рпИ роОро▓рпНро▓ро╛ рокрпЗрокрпНрокро░рпБроорпН рокро╛ро╕ро╛ропро┐роЯрогрпБроорпН.

   \\

4 / 3 / 2012

   роХрпБрооро╛ро░рпН роКро░рпБроХрпНроХрпБ рокрпЛропрпН ро╡ро┐роЯрпНроЯрпБ роЗройрпНро▒рпБ роХро╛ро▓рпИ ро╡роирпНродро╛ройрпН. роОроЩрпНроХроорпНрооро╛ро╡рпБроХрпНроХрпБ роЙроЯроорпНрокрпБ роЪро░ро┐ропро┐ро▓рпНро▓рпИропро╛роорпН. роПродрпЛ роЖрокрпНро░рпЗро╖ройрпН рокрогрпНрогрогрпБрооро╛роорпН. рокрогроорпН роЗро▓рпНро▓ро╛родродро╛ро▓рпН рокрогрпНрогро╡ро┐ро▓рпНро▓рпИ рокрпЛро▓ро┐ро░рпБроХрпНроХрпБ роОройрпНро▒рпБ роЕро╡ройрпН роЕроорпНрооро╛ роЪрпКройрпНройро╛ро░рпНроХро│ро╛роорпН.          роЕроорпНрооро╛ро╡рпИ роЙроЯройрпЗ рокро╛ро░рпНроХрпНроХ ро╡рпЗрогрпНроЯрпБроорпН рокрпЛро▓ро┐ро░рпБроХрпНроХрпБ.

   роЕрокрпНрокро╛ро╡рпБроХрпНроХрпБ роГрокрпЛройрпН рокрогрпНрогро┐ройрпЗройрпН. роОроЯрпБродрпНродродрпБроорпЗ, "роиро▓рпНро▓ро╛ рокроЯро┐роХрпНроХро┐ро▒ро┐ропро╛рокрпНрокро╛? рокрпЛрой родроЯро╡рпИ рокрпЛро▓ро╡рпЗ роОро▓рпНро▓ро╛ рокро╛роЯродрпНродрпБро▓ропрпБроорпН роиро▓рпНро▓ рооро╛ро░рпНроХрпН ро╡ро╛роЩрпНроХрогрпБроорпНроЯро╛ ро░ро╛роЬро╛" роОройрпНроХро┐ро▒ро╛ро░рпН. роОродрпНродройрпИ роОродро┐ро░рпНрокро╛ро░рпНрокрпНрокрпБ, роироорпНрокро┐роХрпНроХрпИтАж

      ро╡рпАроЯрпНроЯрпИрокрпН рокро▒рпНро▒ро┐ роХрпЗроЯрпНроЯро╛ро▓рпН, "роирпА роПрогрпНроЯро╛ роЗродрпЖро▓рпНро▓ро╛роорпН ропрпЛроЪро┐роЪрпНроЪрпБроХрпНроХро┐роЯрпНроЯрпБ? роЖроЪрпНроЪрпБ, роЗройрпНройрпБроорпН роорпВрогрпБ ро╡ро░рпБро╖роорпН родро╛ройрпЗ? роиро▓рпНро▓ ро╡рпЗро▓рпИро▓ роЪрпЗро░рпНроирпНродрпБроЯрпНроЯро╛ роОро▓рпНро▓ро╛роорпН роЪро░ро┐ропро╛ропро┐роЯрпБроорпН."

   "роЕ.. роЖрооро╛роорпНрокро╛.."

   "роЖрооро╛, роиро▓рпНро▓ рокроЯро┐роХрпНроХро┐ро▒рпЗропро┐ро▓рпНро▓рпЗ?"

   роиро╛ройрпН роОройрпНройро╡рпЖройрпНро▒рпБ роЪрпКро▓рпНро╡рпЗройрпН? рокрпЛрой роЪрпЖрооро╕рпНроЯро░ро┐ройрпН роорпВройрпНро▒рпБ роЕро░ро┐ропро░рпНроЪрпИропро╛? роЗроирпНрод роЪрпЖрооро╕рпНроЯро░рпН роЕродрпИро╡ро┐роЯ роХроЯро┐ройрооро╛роХ роЗро░рпБрокрпНрокродрпИропро╛?

   \\

4 / 4 / 2012

   роОроХрпНро╕ро╛роорпБроХрпНроХрпБ роЗройрпНройрпБроорпН роорпВройрпНро▒рпБ роиро╛ро│рпН роЗро░рпБроХрпНроХрпБ.   роЕро▒рпИропро┐ро▓рпН роиро╛ройрпНроХрпБ рокроХрпНроХроорпБроорпН рокрпБродрпНродроХроЩрпНроХро│рпН. роХрпБро┤рокрпНрокрооро╛роХ роЗро░рпБроХрпНроХрпБ. роЕроЯро┐ро╡ропро┐ро▒рпНро▒рпИ  рокро┐роЪрпИроХро┐ро▒родрпБ. роЕро┤рпБроХрпИ роЕро┤рпБроХрпИропро╛роХ ро╡ро░рпБроХро┐ро▒родрпБ. роиро╛ройрпН роОройрпНрой родрокрпНрокрпБ роЪрпЖропрпНродрпЗройрпН?

   рокрпНро░рпИрооро░ро┐ ро╕рпНроХрпВро▓ро┐ро▓рпН роЯрпАроЪрпНроЪро░рпНро╕рпН роТро┤рпБроЩрпНроХро╛роХ роЕроЯро┐рокрпНрокроЯрпИ рокро╛роЯроЩрпНроХро│рпИ роЪрпКро▓рпНро▓ро┐ родроирпНродро┐ро░рпБроХрпНроХроХрпН роХрпВроЯро╛родро╛?

   ро╣рпИро╕рпНроХрпВро▓ро┐ро▓ро╛ро╡родрпБ роЙро░рпБрокрпНрокрпЛроЯ ро╡рпИроХрпНроХро╛рооро▓рпН рокро╛роЯроЩрпНроХро│рпИ рокрпБро░ро┐роп ро╡рпИродрпНродро┐ро░рпБроХрпНроХроХрпН роХрпВроЯро╛родро╛?

   ро╣рпЖроЯрпН рооро╛ро╕рпНроЯро░рпН роЪроорпНрокро╛родро┐роХрпНроХ роОройрпН роЗропро▓ро╛роорпИ родро╛ройрпН роХро┐роЯрпИродрпНродродро╛? роЕродро▒рпНроХрпБ роЕрокрпНрокро╛, роирпАроЩрпНроХ роПройрпН роЪроорпНроородро┐роЪрпНроЪрпАроЩрпНроХ?

   роОройрпНройро╛ро▓рпН роорпБроЯро┐ропрпБрооро╛ роОройрпНро▒рпБ ропрпЛроЪро┐роХрпНроХро╛рооро▓рпН роороХройрпИ рокрпЖро░ро┐роп роОройрпНроЬро┐ройрпАропро░рпН роЖроХрогрпБроорпНройрпБ роирпАроЩрпНроХро│ро╛ро╡рпЗ роПройрпНрокро╛ роорпБроЯро┐ро╡рпБ роЪрпЖроЮрпНроЪрпАроЩрпНроХ?

   роЕрокрпНрокро╛.. роЕроорпНрооро╛тАж роЗрокрпНрок роОройрпНройро╛ро▓рпН роорпБроЯро┐ропро▓ро┐ропрпЗ.

   родроЩрпНроХроЪрпНроЪро┐ рокроЯро┐рокрпНрокрпБ, роХро▓рпНропро╛рогроорпН, роЕроорпНрооро╛ ро╡рпИродрпНродро┐ропроорпН.. роПро▒рпНроХройро╡рпЗ роОройроХрпНроХро╛роХ роОройрпНройрпИ роироорпНрокро┐ роПроХрокрпНрокроЯрпНроЯ роХроЯройрпНроХро│рпНтАж роРропрпЛ, роиро╛ройрпН роОройрпНрой роЪрпЖропрпНро╡рпЗройрпН?

   роиро╛ройрпН роОройрпНрой роЪрпЖропрпНро╡рпЗройрпНтАж?

...

   ро▓рпКроЯро▓рпКроЯро╡рпЖройрпНро▒рпБ рооро┐ройрпНро╡ро┐роЪро┐ро▒ро┐ роЪрпБро┤ро▓, роХроЯрпНроЯро┐ро▓ро┐ро▓рпН роЕро╡ро┐ро┤рпНродрпНродрпБрокрпН рокрпЛроЯрпНроЯро┐ро░рпБроирпНрод роХрпИро▓ро┐ропрпИрокрпН рокро╛ро░рпНродрпНродродрпБроорпН роОройрпНрой роЪрпЖропрпНропро▓ро╛роорпН роОройрпНрокродрпБ рокрпБро░ро┐роирпНродрпБ ро╡ро┐роЯрпНроЯродрпБ.

   роТро░рпБ рокрпЗрокрпНрокро░рпИ роХро┐ро┤ро┐родрпНродрпБ роОро┤рпБродродрпН родрпКроЯроЩрпНроХро┐ройрпЗройрпН, 'роХро╛ро╡ро▓рпН родрпБро▒рпИропро┐ройро░рпБроХрпНроХрпБ роОройрпН родро▒рпНроХрпКро▓рпИроХрпНроХрпБ ропро╛ро░рпБроорпН рокрпКро▒рпБрокрпНрокро┐ро▓рпНро▓рпИ - роЗрокрпНрокроЯро┐роХрпНроХрпБ ро░ро╛роорпБ'

   " роЯрпЗропрпН ро░ро╛роорпБ.  роорпБро░рпБроХройрпН родрпВроХрпНроХ рооро╛родрпНродро┐ро░рпИ роЪро╛рокрпНрокро┐роЯрпНроЯрпБроЯрпНроЯро╛ройро╛роорпН. роУроЯро┐ ро╡ро╛" роХродро╡рпИродрпН родроЯрпНроЯро┐ропро╡ро╛ро▒рпБ роХродрпНродро┐роХрпНроХрпКрогрпНроЯрпЗ роУроЯро┐ройро╛ройрпН роХрпБрооро╛ро░рпН.

   роОройрпНрой? роироорпНроо роорпБро░рпБроХройро╛? роПройрпН? роУ.. роЕро╡ройрпБроХрпНроХрпБ роОро▓рпНро▓ро╛ рокрпЗрокрпНрокро░рпБроорпН роЕро░ро┐ропро░рпНро╕рпН. рокрпБродрпБроЪро╛ ро╡роирпНрод роХро╛родро▓рпБроорпН роКродрпНродро┐роХрпНроХро┐роЪрпНроЪрпБ. роЖройро╛ро▓рпН роЕродрпБроХрпНроХро╛роХ роЗрокрпНрокроЯро┐ропро╛? роорпБроЯрпНроЯро╛ро│рпН.. роХрпЛро┤рпИ..

   роЙроЯрпНроХро╛ро░рпНроирпНродрпБ ропрпЛроЪро┐роЪрпНроЪро╛ роорпБроЯро┐ро╡рпБ роХро┐роЯрпИроХрпНроХро╛род рокро┐ро░роЪрпНройрпИройрпНройрпБ роПродрпБроорпН роЗро░рпБроХрпНроХро╛ роОройрпНрой?

   роХрпИропро┐ро▓ро┐ро░рпБроирпНрод рокрпЗрокрпНрокро░рпИ роХроЪроХрпНроХро┐ роОро▒ро┐роирпНродрпБ ро╡ро┐роЯрпНроЯрпБ роорпБро░рпБроХройрпН ро░рпВроорпБроХрпНроХрпБ роУроЯро┐ройрпЗройрпН.

   роиро┐роЪрпНроЪропроорпН роЕро╡ройрпИроХрпН роХро╛рокрпНрокро╛ро▒рпНро▒ро┐ ро╡ро┐роЯрпБро╡рпЛроорпН.

   (роПрокрпНро░ро▓рпН 1-15, 2014,  роороЩрпНроХрпИропро░рпН рооро▓ро░рпН роЗродро┤ро┐ро▓рпН рокро┐ро░роЪрпБро░рооро╛ройродрпБ.)




**
